//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.osci.xinneres.behoerde._6;

import java.util.ArrayList;
import java.util.List;
import de.osci.xinneres.kommunikation._5.Kommunikation;
import de.osci.xinneres.postanschrift._5.PostalischeInlandsanschrift;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Typ enthält Angaben über den Namen und die Erreichbarkeit einer Behörde. Eine Behörde im Sinne des Verwaltungsverfahrensgesetzes ist jede Stelle, die Aufgaben der öffentlichen Verwaltung wahrnimmt.
 * 
 * <p>Java class for Behoerde complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Behoerde">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="behoerdenkennung" type="{http://www.osci.de/xinneres/behoerde/6}Behoerdenkennung"/>
 *         <element name="erreichbarkeit" type="{http://www.osci.de/xinneres/kommunikation/5}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="anschrift" type="{http://www.osci.de/xinneres/postanschrift/5}PostalischeInlandsanschrift" minOccurs="0"/>
 *         <element name="behoerdenname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behoerde", propOrder = {
    "behoerdenkennung",
    "erreichbarkeit",
    "anschrift",
    "behoerdenname"
})
@XmlSeeAlso({
    BehoerdeErreichbar.class
})
public class Behoerde {

    @XmlElement(required = true)
    protected Behoerdenkennung behoerdenkennung;
    protected List<Kommunikation> erreichbarkeit;
    protected PostalischeInlandsanschrift anschrift;
    @XmlElement(required = true)
    protected String behoerdenname;

    /**
     * Gets the value of the behoerdenkennung property.
     * 
     * @return
     *     possible object is
     *     {@link Behoerdenkennung }
     *     
     */
    public Behoerdenkennung getBehoerdenkennung() {
        return behoerdenkennung;
    }

    /**
     * Sets the value of the behoerdenkennung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behoerdenkennung }
     *     
     */
    public void setBehoerdenkennung(Behoerdenkennung value) {
        this.behoerdenkennung = value;
    }

    /**
     * Gets the value of the erreichbarkeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the erreichbarkeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErreichbarkeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kommunikation }
     * 
     * 
     * @return
     *     The value of the erreichbarkeit property.
     */
    public List<Kommunikation> getErreichbarkeit() {
        if (erreichbarkeit == null) {
            erreichbarkeit = new ArrayList<>();
        }
        return this.erreichbarkeit;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link PostalischeInlandsanschrift }
     *     
     */
    public PostalischeInlandsanschrift getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalischeInlandsanschrift }
     *     
     */
    public void setAnschrift(PostalischeInlandsanschrift value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the behoerdenname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehoerdenname() {
        return behoerdenname;
    }

    /**
     * Sets the value of the behoerdenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehoerdenname(String value) {
        this.behoerdenname = value;
    }

}
