<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xpersonenstand="http://xpsw.domap.de/xpsw2611"
           xmlns:bn-uq-g2g="http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1"
           xmlns:din91379="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"
           xmlns:xida="http://www.osci.de/xinneres/datum/2"
           xmlns:xig="http://www.osci.de/xinneres/geschlecht/1"
           xmlns:xink="http://www.osci.de/xinneres/basisnachricht/7"
           xmlns:xirts="http://www.osci.de/xinneres/rueckweisung/6"
           targetNamespace="http://xpsw.domap.de/xpsw2611"
           version="26.11"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
   <xs:annotation>
      <xs:appinfo>
         <standard>
            <nameLang>XPersonenstand</nameLang>
            <nameKurz>XPersonenstand</nameKurz>
            <nameTechnisch>xinneres.xpersonenstand</nameTechnisch>
            <kennung>urn:xoev-de:kosit:standard:xinneres.xpersonenstand</kennung>
            <beschreibung>Projektziel ist die elektronische Kommunikation der Standesämter untereinander und mit anderen Behörden und Institutionen, welche Daten von den Standesämtern erhalten oder an Standesämter senden. Der Nutzen des Projektes besteht in der Kostenreduktion und einer Verbesserung der Qualität der Personenstandsdaten sowie einer Verbesserung der Interoperabilität in der Kommunikation der Standesämter untereinander und zu weiteren Kommunikationspartnern.
</beschreibung>
         </standard>
         <versionStandard>
            <version>26.11</version>
            <versionXOEVProfil>3.0.3</versionXOEVProfil>
            <versionXOEVHandbuch>2.4</versionXOEVHandbuch>
            <versionXGenerator>3.0.1</versionXGenerator>
            <versionModellierungswerkzeug>19.0 SP4</versionModellierungswerkzeug>
            <nameModellierungswerkzeug>MagicDraw</nameModellierungswerkzeug>
         </versionStandard>
      </xs:appinfo>
   </xs:annotation>
   <xs:include schemaLocation="xpersonenstand-baukasten.xsd"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/basisnachricht/7/xinneres-basisnachricht.xsd"
              namespace="http://www.osci.de/xinneres/basisnachricht/7"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/datum/2/xinneres-datum.xsd"
              namespace="http://www.osci.de/xinneres/datum/2"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/geschlecht/1/xinneres-geschlecht.xsd"
              namespace="http://www.osci.de/xinneres/geschlecht/1"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/rueckweisung/6/xinneres-rueckweisung.xsd"
              namespace="http://www.osci.de/xinneres/rueckweisung/6"/>
   <xs:import schemaLocation="http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1/xoev-basisnachricht-unqualified-g2g_1.1.xsd"
              namespace="http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1"/>
   <xs:import schemaLocation="https://xoev.de/schemata/din/91379/2022-08/din-norm-91379-datatypes.xsd"
              namespace="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"/>
   <xs:complexType name="Datenabruf2StA.Abruf.Allgemeines">
      <xs:annotation>
         <xs:appinfo>
            <title>Allgemeine Angaben zu einem Datenabruf</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält alle Informationen, die in jeder Abrufnachricht angegeben werden müssen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="abrufendePerson" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier muss die nach § 14 PStV zum Abruf berechtigte Person zusätzlich zum Feld ansprechpartner angegeben werden. Dies wird zur Revisionierung nach § 64 PStV benutzt. Das Feld muss durch das Fachverfahren befüllt werden, muss den angemeldeten Benutzer wiedergeben, der den Abruf startet und darf durch den Benutzer nicht mehr veränderbar sein.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="zuordnung" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann eine Zeichenkette übermittelt werden, die die technische Zuordnung der Abruf- zur Antwortnachricht vereinfacht.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="registernummer"
                     minOccurs="0"
                     type="xpersonenstand:Registereintrag.Datenabruf">
            <xs:annotation>
               <xs:documentation>Ist im abfragenden Standesamt eine Registernummer des Eintrags vorhanden, für den angefragt wird, so ist diese hier zu übermitteln. Dies ist im Allgemeinen der Fall, wenn mit der Abfrage eine Folgebeurkundung vorbereitet wird. Die Registernummer wird hier nur zum Zwecke der Revisionierung übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Abruf.Allgemeines.EU">
      <xs:annotation>
         <xs:appinfo>
            <title>Allgemeine Angaben zu einem Datenabruf</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält alle Informationen, die in jeder Abrufnachricht aus dem EU-Ausland angegeben werden müssen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="abrufendePerson" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier muss eine verantwortliche Person bei der abrufenden Stelle genannt werden. Dies wird zur Revisionierung nach § 64 PStV benutzt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="abrufendeStelle" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier muss die abrufende Stelle angegeben werden, d. h. die Stelle in deren Auftrag der Online-Dienst im EU-Ausland betrieben wird. Dies wird zur Revisionierung nach § 64 PStV benutzt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="zuordnung" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann eine Zeichenkette übermittelt werden, die die technische Zuordnung der Abruf- zur Antwortnachricht vereinfacht.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.EheLP">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zu einer Ehe oder LP</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Angaben zu einer Ehe oder einer Lebenspartnerschaft, die dem Registereintrag entnommen werden.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ereignisdatum" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Hier wird das Ereignisdatum übermittelt. Es handelt sich immer um ein exaktes Datum, da dieses bei Eheschließungen und der Begründung von Lebenspartnerschaften immer bekannt ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ereignisort" type="xpersonenstand:Ereignisort">
            <xs:annotation>
               <xs:documentation>Hier wird der Ereignisort übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Eintragsidentifikation.EheLP">
      <xs:annotation>
         <xs:appinfo>
            <title>Identifikation des Ehe- oder LPeintrags</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp identifiziert den gesuchten Ehe- oder Lebenspartnerschaftseintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
      </xs:annotation>
      <xs:choice>
         <xs:element name="eintragsnummer"
                     type="xpersonenstand:Datenabruf2StA.Registernummer">
            <xs:annotation>
               <xs:documentation>Falls bekannt, wird der gesuchte Ehe- oder Lebenspartnerschaftseintrag über die hier eingetragene Eintragsnummer identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="suchdaten" type="xpersonenstand:Datenabruf2StA.Suchdaten.EheLP">
            <xs:annotation>
               <xs:documentation>Falls die Eintragsnummer nicht bekannt ist, wird der gesuchte Ehe- oder Lebenspartnerschaftseintrag über die hier eingetragenen Suchdaten identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Eintragsidentifikation.Geburt">
      <xs:annotation>
         <xs:appinfo>
            <title>Identifikation des Geburteneintrags</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp identifiziert den gesuchten Geburtenregistereintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
      </xs:annotation>
      <xs:choice>
         <xs:element name="eintragsnummer"
                     type="xpersonenstand:Datenabruf2StA.Registernummer">
            <xs:annotation>
               <xs:documentation>Falls bekannt, wird der gesuchte Geburtseintrag über die hier eingetragene Eintragsnummer identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="suchdaten" type="xpersonenstand:Datenabruf2StA.Suchdaten.Geburt">
            <xs:annotation>
               <xs:documentation>Falls die Eintragsnummer nicht bekannt ist, wird der gesuchte Geburtseintrag über die hier eingetragenen Suchdaten identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Eintragsidentifikation.Sterbefall">
      <xs:annotation>
         <xs:appinfo>
            <title>Identifikation des Sterbeeintrags</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp identifiziert den gesuchten Sterbeeintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
      </xs:annotation>
      <xs:choice>
         <xs:element name="eintragsnummer"
                     type="xpersonenstand:Datenabruf2StA.Registernummer">
            <xs:annotation>
               <xs:documentation>Falls bekannt, wird der gesuchte Sterbeeintrag über die hier eingetragene Eintragsnummer identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="suchdaten"
                     type="xpersonenstand:Datenabruf2StA.Suchdaten.Sterbefall">
            <xs:annotation>
               <xs:documentation>Falls die Eintragsnummer nicht bekannt ist, wird der gesuchte Sterbeeintrag über die hier eingetragenen Suchdaten identifiziert.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Elternteil">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zu einem leiblichen Elternteil</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Angaben zu einem Kind, die dem Geburtseintrag entnommen werden.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Hier werden die Namen eines Elternteils übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="identitaetNichtNachgewiesen"
                     minOccurs="0"
                     fixed="true"
                     type="xs:boolean">
            <xs:annotation>
               <xs:documentation>Hier wird übermittelt, ob die Identität des Elternteils nicht nachgewiesen ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Elternteil.Rechtlich">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zu einem rechtlichen Elternteil</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Angaben zu einem Kind, die dem Geburtseintrag entnommen werden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Datenabruf2StA.Elternteil">
            <xs:sequence>
               <xs:element name="familienrechtlicheBezeichnung"
                           type="xpersonenstand:Code.FamilienrechtlicheBezeichnungGeburtenregister">
                  <xs:annotation>
                     <xs:documentation>Hier wird die familienrechtliche Bezeichnung eines Elternteils übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Geburt">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zur Geburt</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Ort und Tag eines Ereignisses, über das in einer Antwort auf einen Datenabruf Auskunft gegeben wird. Die Daten werden dem angefragten Registereintrag entnommen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="geburtstag" type="xida:TeilbekanntesDatum">
            <xs:annotation>
               <xs:documentation>Hier wird das Geburtsdatum übermittelt. Hier können auch teilbekannte Daten angegeben werden, z. B. bei Nachbeurkundungen von Geburten aus dem Ausland.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsort" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird der Geburtsort übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Geburt.EU">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zur Geburt</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält die Angaben zum EU-Nachweis Proof-of-Birth zur Antwort auf einen Datenabruf aus dem EU-Ausland.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen des Kindes werden dem Geburtseintrag entnommen. Das Feld familienname darf hier nicht verwendet werden, da im Geburtseintrag ein solcher nicht eingetragen ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtstag" type="xida:TeilbekanntesDatum">
            <xs:annotation>
               <xs:documentation>Hier wird das Geburtsdatum übermittelt. Hier können auch teilbekannte Daten angegeben werden, z. B. bei Nachbeurkundungen von Geburten aus dem Ausland.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsort" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird der Geburtsort übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geschlecht" type="xig:Code.Geschlecht">
            <xs:annotation>
               <xs:documentation>Das Geschlecht des Kindes wird dem Geburtseintrag entnommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Hinweis.Ehe">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zum Hinweis auf eine Ehe</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Angaben zu einer Ehe, einschließlich dem Hinweis auf Eintrag im Eheregister.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="eheschliessungstag" minOccurs="0" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Hier wird der Tag der Eheschließung mitgeteilt, falls er im Register gespeichert ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="eheschliessungsort" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird der Ort der Eheschließung mitgeteilt, falls er im Register gespeichert ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="eheeintrag"
                     minOccurs="0"
                     type="xpersonenstand:Datenabruf2StA.Registereintrag.Hinweis">
            <xs:annotation>
               <xs:documentation>Hier kann der Hinweis auf den Eheeintrag übermittelt werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Partner">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zum Partner</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Namen eines Partners vor und in der Partnerschaft, sowie Ort und Tag der Geburt des Partners. Der Datentyp kann dabei sowohl für Lebenspartner unverändert verwendet werden, für Ehepartner existiert eine Ableitung mit zusätzlichen Angaben. Die Daten werden dem Registereintrag entnommen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="familienrechtlicheBezeichnung">
            <xs:annotation>
               <xs:documentation>In diesem Feld wird die familienrechtliche Bezeichnung des Partners übertragen.</xs:documentation>
            </xs:annotation>
            <xs:complexType>
               <xs:choice>
                  <xs:element name="lebenspartnerschaft"
                              type="xpersonenstand:Code.FamilienrechtlicheBezeichnungLPregister">
                     <xs:annotation>
                        <xs:documentation>Hier wird die familienrechtliche Bezeichnung übermittelt, wenn es sich um eine Nachricht aus dem Lebenspartnerschaftsregister handelt..</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="ehe"
                              type="xpersonenstand:Code.FamilienrechtlicheBezeichnungEheregister">
                     <xs:annotation>
                        <xs:documentation>Hier wird die familienrechtliche Bezeichnung übermittelt, wenn es sich um eine Nachricht aus dem Eheregister handelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:choice>
            </xs:complexType>
         </xs:element>
         <xs:element name="namenVorPartnerschaft" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen vor Beginn der Partnerschaft (Eheschließung oder Eintragung der Lebenspartnerschaft) werden dem Registereintrag entnommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="namenInPartnerschaft" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen innerhalb der Partnerschaft (Ehe oder Lebensparterschaft) werden dem Registereintrag entnommen. Nach der Auflösung der Partnerschaft werden hier die Namen nach Auflösung mitgeteilt.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburt" type="xpersonenstand:Datenabruf2StA.Geburt">
            <xs:annotation>
               <xs:documentation>Geburtsort und -tag des Ehe- bzw. Lebenspartners werden dem Registereintrag entnommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="hinweisGeburt"
                     minOccurs="0"
                     type="xpersonenstand:Datenabruf2StA.Registereintrag.Hinweis">
            <xs:annotation>
               <xs:documentation>Hier sind die Hinweisdaten zum Geburtseintrag des Partners zu übermitteln, falls diese vorhanden sind.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Partner.Ehe">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zum Ehepartner</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Namen eines Ehepartners vor und in der Ehe, sowie Ort und Tag der Geburt des Ehepartners und, sofern der Ehepartner verstorben ist, den Hinweis auf den Sterbeeintrag. Die Daten werden dem Registereintrag und Hinweisteil entnommen.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Datenabruf2StA.Partner">
            <xs:sequence>
               <xs:element name="hinweisSterbeeintrag"
                           minOccurs="0"
                           type="xpersonenstand:Datenabruf2StA.Registereintrag.Hinweis">
                  <xs:annotation>
                     <xs:documentation>Ist der Ehepartner verstorben, kann hier der Hinweis auf den Sterbeeintrag übermittelt werden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Registereintrag.Hinweis">
      <xs:annotation>
         <xs:appinfo>
            <title>Hinweis auf einen Registereintrag</title>
         </xs:appinfo>
         <xs:documentation>Dieser Container enthält die Identifikationsdaten für einen Registereintrag. Dabei kann es sich auch um ausländische Registereinträge handeln. Dieser Container kann verwendet werden, um Hinweise auf Registereinträge zu übermitteln. Die Modellierung und auch die Dokumentation der Felder folgt der Modellierung des Tys "TEintragKurz" aus XPSR, und kann daher von den Gepflogenheiten in XPS abweichen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="behoerde" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier ist die Funktionsbezeichnung der Behörde, z.B. "Standesamt" zu übermitteln.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="name" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier ist der Name der Behörde zu übermitteln.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="land" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier ist der Staat zu übermitteln, in dem sich das beurkundete Ereignis ereignet hat.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="registerart"
                     minOccurs="0"
                     type="xpersonenstand:Code.Registerart">
            <xs:annotation>
               <xs:documentation>Hier ist die Art des Personenstandsregisters bzw. des Personenstandsbuchs zu übermitteln.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="jahr" minOccurs="0" type="xs:gYear">
            <xs:annotation>
               <xs:documentation>Hier ist das Jahr des Eintrags zu übermitteln.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="eintragsnummer" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier ist die Eintragsnummer zu übermitteln. Hier sind nicht nur die in Deutschland üblichen Eintragsnummern möglich, sondern auch Eintragsnummern ausländischer Behörden, die völlig anderen Nummerierungsschemata folgen.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Registernummer">
      <xs:annotation>
         <xs:appinfo>
            <title>Registernummer</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp wird verwendet, um den angefragten Registereintrag über dessen Nummer zu identifizieren.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="standesamtsnummer" type="xpersonenstand:Code.Standesamtsnummer">
            <xs:annotation>
               <xs:documentation>Die Standesamtsnummer (Nummer 0010 in Anlage 1 der PStV) ist Teil der zusammengesetzten Eintragsnummer und muss deswegen angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="standesamtsname" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Der Standesamtsname (Nummer 0001 in Anlage 1 der PStV) hilft der praktischen Arbeit des Standesamts und kann deswegen angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="registerart" type="xpersonenstand:Code.Registerart">
            <xs:annotation>
               <xs:documentation>Die Registerart (Nummer 0011 in Anlage 1 der PStV) ist Teil der zusammengesetzten Eintragsnummer und muss deswegen angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="erstbeurkundungsjahr" type="xs:gYear">
            <xs:annotation>
               <xs:documentation>Das Erstbeurkundungsjahr (Nummer 0013 in Anlage 1 der PStV) ist Teil der zusammengesetzten Eintragsnummer und muss deswegen angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="eintragsnummer" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Die Eintragsnummer (Nummer 0012 in Anlage 1 der PStV) ist Teil der zusammengesetzten Eintragsnummer und muss deswegen angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Suchdaten.EheLP">
      <xs:annotation>
         <xs:appinfo>
            <title>Suchdaten im Ehe- oder LPregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp wird verwendet, um den abgerufenen Ehe- bzw. Lebenspartnerschaftseintrag über Inhaltsdaten zu identifizieren.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="partner" maxOccurs="2">
            <xs:annotation>
               <xs:documentation>Hier müssen Daten zu mindestens einem der eingetragenen Partner übermittelt werden, um die Suche nach dem Eintrag zu ermöglichen.</xs:documentation>
            </xs:annotation>
            <xs:complexType>
               <xs:sequence>
                  <xs:element name="namen" type="xpersonenstand:PersonName">
                     <xs:annotation>
                        <xs:documentation>Enthält die Namen des im Register eingetragenen Partners. Diese sind zur Auffindung eines Ehe- oder Lebenspartnerschaftseintrags zwingend notwendig.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtsdatum" minOccurs="0" type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Das Geburtsdatum des im Register eingetragen Partners. Das Datum muss, zur Verbesserung der Suchergebnisse im Großteil der Fälle, exakt angegeben werden. Die Verschlechterung in den seltenen Fällen, in denen das Datum teilbekannt ist, wird dafür in Kauf genommen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:complexType>
         </xs:element>
         <xs:element name="ereignisdatum" minOccurs="0" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Der Tag, an dem die Lebenspartnerschaft eingetragen bzw. die Ehe geschlossen wurde. Falls das Datum bekannt ist, muss es übermittelt werden. Falls es nicht bekannt ist, kann auch nach den anderen Suchdaten gesucht werden. Um die Wahrscheinlichkeit für Mehrfachtreffer zu verringern, muss der Tag exakt angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ereignisort" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann der Ort der Eheschließung bzw. Eintragung der Lebenspartnerschaft angegeben werden. Dies ist nur sinnvoll bei Eingemeindungen, in denen sich der Ereignisort vom Standort des Standesamtes unterscheiden kann, sowie bei nachbeurkundeten Eheschließungen aus dem Ausland.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="standesamt"
                     minOccurs="0"
                     type="xpersonenstand:Datenabruf2StA.Suchdaten.Standesamt">
            <xs:annotation>
               <xs:documentation>Mit Standesamtsname und -nummer kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Suchdaten.Geburt">
      <xs:annotation>
         <xs:appinfo>
            <title>Suchdaten im Geburtenregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp wird verwendet, um den abgerufenen Geburtseintrag über Inhaltsdaten zu identifizieren.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen des Kindes sind zur Suche unbedingt erforderlich, deswegen ist das Feld verpflichtend. Das Feld geburtsname darf bei Kindern nicht befüllt werden, da der Familienname erst nach der ersten Änderung des Familiennamens zum Geburtsnamen wird.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtstag" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Der Geburtstag ist für die Suche unbedingt erforderlich und ist deswegen ein Pflichtfeld. Um die Wahrscheinlichkeit von Mehrfachtreffern zu verringern muss der Tag exakt angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsort" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann der Geburtsort übermittelt werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="namenElternteil"
                     minOccurs="0"
                     type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Hier können die Namen eines Elternteils angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="standesamt"
                     minOccurs="0"
                     type="xpersonenstand:Datenabruf2StA.Suchdaten.Standesamt">
            <xs:annotation>
               <xs:documentation>Mit Standesamtsname und -nummer kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Suchdaten.Standesamt">
      <xs:annotation>
         <xs:appinfo>
            <title>Suchdaten zu einem Standesamt</title>
         </xs:appinfo>
         <xs:documentation>Mit Standesamtsname und -nummer kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll. Diese Angaben sind bei der Suche in allen Registern möglich.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="standesamtsname"
                     minOccurs="0"
                     type="xpersonenstand:Behoerdenbezeichnung">
            <xs:annotation>
               <xs:documentation>Mit dem Namen des Standesamts kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="standesamtsnummer" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Mit der Standesamtsnummer kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Suchdaten.Sterbefall">
      <xs:annotation>
         <xs:appinfo>
            <title>Suchdaten im Sterberegister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp wird verwendet, um den abgerufenen Sterbeeintrag über Inhaltsdaten zu identifizieren.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen des Verstorbenen sind zur Suche unbedingt erforderlich, deswegen ist das Feld verpflichtend.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="todestag" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Der Todestag ist für die Suche unbedingt erforderlich und ist deswegen ein Pflichtfeld. Um die Wahrscheinlichkeit von Mehrfachtreffern zu verringern, muss der Tag exakt angegeben werden. Der Todestag ist der Tag, an dem die Person gesichert tot war (nicht zuletzt gesehen).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="sterbeort" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann der Sterbeort angegeben werden. Der Sterbeort ist nur wichtig bei Eingemeindungen, in denen er sich vom Standort des Standesamtes unterscheiden kann.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsdatum" minOccurs="0" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Hier kann das Geburtsdatum des Verstorbenen angegeben werden. Das Datum muss, zur Verbesserung der Suchergebnisse im Großteil der Fälle, exakt angegeben werden. Die Verschlechterung in den seltenen Fällen, in denen das Datum teilbekannt ist, wird dafür in Kauf genommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="standesamt"
                     minOccurs="0"
                     type="xpersonenstand:Datenabruf2StA.Suchdaten.Standesamt">
            <xs:annotation>
               <xs:documentation>Mit Standesamtsname und -nummer kann gesteuert werden, ob über alle verwalteten Standesämter oder nur in einem spezifischen gesucht werden soll.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Template.AntwortEhe" abstract="true">
      <xs:annotation>
         <xs:appinfo>
            <title>Template für die Antwort aus dem Eheregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp dient zur Ableitung von Nachrichten, mit denen ein Datenabruf aus einem Eheeintrag beantwortet werden. Der Datenumfang entspricht dem der Eheurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Nachricht.G2GXP">
            <xs:sequence>
               <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="abrufzweck" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Hier wird der Zweck des ursprünglichen Abrufs aus dem Eheregister mitgeteilt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identifikationEheeintrag"
                           type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.EheLP">
                  <xs:annotation>
                     <xs:documentation>Die Eintragsidentifikation aus der Abrufnachricht an ein Eheregister wird in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="registernummer"
                           type="xpersonenstand:Datenabruf2StA.Registernummer">
                  <xs:annotation>
                     <xs:documentation>Hier wird die Registernummer des Registereintrags übermittelt, aus dem die Daten übernommen wurden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ehe" type="xpersonenstand:Datenabruf2StA.EheLP">
                  <xs:annotation>
                     <xs:documentation>Hier werden Tag und Ort der Eheschließung übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="ehepartner"
                           minOccurs="2"
                           maxOccurs="2"
                           type="xpersonenstand:Datenabruf2StA.Partner.Ehe">
                  <xs:annotation>
                     <xs:documentation>Angaben zu den beiden Ehepartnern. Es werden Namen vor der Ehe, Geburtstag und -ort sowie Namen innerhalb der Ehe mitgeteilt. Die Angaben werden dem Eheeintrag entnommen. Die Ehepartner sind in der Abfolge zu übermitteln, die der Eintragung im Eheregister entspricht.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="vermerkAufloesung"
                           minOccurs="0"
                           type="xpersonenstand:Datenabruf2StA.VermerkAufloesung">
                  <xs:annotation>
                     <xs:documentation>Falls die Ehe aufgelöst wurde, wird hier ein Vermerk über die Auflösung übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Template.AntwortGeburt" abstract="true">
      <xs:annotation>
         <xs:appinfo>
            <title>Template für die Antwort aus dem Geburtsregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp dient zur Ableitung von Nachrichten, mit denen ein Datenabruf aus einem Geburtseintrag beantwortet werden. Der Datenumfang entspricht dem der Geburtsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Nachricht.G2GXP">
            <xs:sequence>
               <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="abrufzweck" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Hier wird der Zweck des ursprünglichen Abrufs aus dem Geburtenregister mitgeteilt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identifikationGeburtseintrag"
                           type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Geburt">
                  <xs:annotation>
                     <xs:documentation>Die Eintragsidentifikation aus der Abrufnachricht an ein Geburtenregister wird in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="registernummer"
                           type="xpersonenstand:Datenabruf2StA.Registernummer">
                  <xs:annotation>
                     <xs:documentation>Hier wird die Registernummer des Registereintrags übermittelt, aus dem die Daten übernommen wurden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="geburt" type="xpersonenstand:Datenabruf2StA.Geburt">
                  <xs:annotation>
                     <xs:documentation>Hier werden Angaben zur Geburt übermittelt. Sie werden dem Geburtsregistereintrag entnommen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="kind">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp enthält Angaben zu einem Kind, die dem Geburtseintrag entnommen werden.</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                     <xs:sequence>
                        <xs:element name="kindNamen" type="xpersonenstand:PersonName">
                           <xs:annotation>
                              <xs:documentation>Die Namen des Kindes werden dem Geburtseintrag entnommen. Das Feld familienname darf hier nicht verwendet werden, da im Geburtseintrag ein solcher nicht eingetragen ist.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="kindGeschlecht" type="xig:Code.Geschlecht">
                           <xs:annotation>
                              <xs:documentation>Das Geschlecht des Kindes wird dem Geburtseintrag entnommen.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="namensfuehrungNichtNachgewiesen"
                                    minOccurs="0"
                                    fixed="true"
                                    type="xs:boolean">
                           <xs:annotation>
                              <xs:documentation>Hier wird übermittelt, ob die Namensführung des Kindes nicht nachgewiesen ist. Dies ist der Fall, wenn die Identität mindestens eines der beiden Elternteile nicht nachgewiesen ist.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                     </xs:sequence>
                  </xs:complexType>
               </xs:element>
               <xs:element name="eltern"
                           maxOccurs="2"
                           type="xpersonenstand:Datenabruf2StA.Elternteil.Rechtlich">
                  <xs:annotation>
                     <xs:documentation>Hier werden Informationen zu den Elternteilen übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="elternLeiblich"
                           minOccurs="0"
                           maxOccurs="2"
                           type="xpersonenstand:Datenabruf2StA.Elternteil">
                  <xs:annotation>
                     <xs:documentation>Hier werden Informationen zu den leiblichen Elternteilen übermittelt. Das Feld darf nur befüllt werden, wenn in der Abrufnachricht der boolsche Wert für "mitElternLeiblich" mit "True" übermittelt wurde.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="eheDesKindes"
                           minOccurs="0"
                           type="xpersonenstand:Datenabruf2StA.Hinweis.Ehe">
                  <xs:annotation>
                     <xs:documentation>Hier können Hinweisdaten zur letzten Ehe des Kindes (maßgeblich ist das Ereignisdatum) übermittelt werden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Template.AntwortLP" abstract="true">
      <xs:annotation>
         <xs:appinfo>
            <title>Template für die Antwort aus dem Lebenspartnerschaftsregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp dient zur Ableitung von Nachrichten, mit denen ein Datenabruf aus einem Lebenspartnerschaftseintrag beantwortet werden. Der Datenumfang entspricht dem der Lebenspartnerschaftsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Nachricht.G2GXP">
            <xs:sequence>
               <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="abrufzweck" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Hier wird der Zweck des ursprünglichen Abrufs aus dem Lebenspartnerschaftsregister mitgeteilt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identifikationLPeintrag"
                           type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.EheLP">
                  <xs:annotation>
                     <xs:documentation>Die Suchdaten aus der Abrufnachricht werden in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="registernummer"
                           type="xpersonenstand:Datenabruf2StA.Registernummer">
                  <xs:annotation>
                     <xs:documentation>Hier wird die Registernummer des Registereintrags übermittelt, aus dem die Daten übernommen wurden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="lebenspartnerschaft" type="xpersonenstand:Datenabruf2StA.EheLP">
                  <xs:annotation>
                     <xs:documentation>Hier werden Tag und Ort der Eheschließung übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="lebenspartner"
                           minOccurs="2"
                           maxOccurs="2"
                           type="xpersonenstand:Datenabruf2StA.Partner">
                  <xs:annotation>
                     <xs:documentation>Angaben zu den beiden Lebenspartnern. Es werden Namen vor der LP, Geburtstag und -ort sowie Namen innerhalb der LP mitgeteilt. Die Angaben werden dem Registereintrag entnommen. Die Lebenspartner sind in der Abfolge zu übermitteln, die der Eintragung im Lebenspartnerschaftseintrag entspricht.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="vermerkAufloesung"
                           minOccurs="0"
                           type="xpersonenstand:Datenabruf2StA.VermerkAufloesung">
                  <xs:annotation>
                     <xs:documentation>Falls die Lebenspartnerschaft aufgelöst wurde, wird hier ein Vermerk über die Auflösung übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Template.AntwortSterbefall" abstract="true">
      <xs:annotation>
         <xs:appinfo>
            <title>Template für die Antwort aus dem Sterberegister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp dient zur Ableitung von Nachrichten, mit denen ein Datenabruf aus einem Sterbeeintrag beantwortet werden. Der Datenumfang entspricht dem der Sterbeurkunde, wobei zusätzliche Angaben aus der Abrufachricht zur Zuordnung der Abrufachricht zur Antwortnachricht übermittelt werden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Nachricht.G2GXP">
            <xs:sequence>
               <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="abrufzweck" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Hier wird der Zweck des ursprünglichen Abrufs aus dem Sterberegister mitgeteilt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identifikationSterbeeintrag"
                           type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Sterbefall">
                  <xs:annotation>
                     <xs:documentation>Die Eintragsidentifikation aus der Abrufnachricht an ein Sterberegister wird in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="registernummer"
                           type="xpersonenstand:Datenabruf2StA.Registernummer">
                  <xs:annotation>
                     <xs:documentation>Hier wird die Registernummer des Registereintrags übermittelt, aus dem die Daten übernommen wurden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="tod">
                  <xs:annotation>
                     <xs:documentation>Hier werden Angaben zum Sterbefall (Zeit und Ort des Todes) übermittelt.</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                     <xs:sequence>
                        <xs:element name="todestag" type="xida:TeilbekanntesDatumMitUnbekannt">
                           <xs:annotation>
                              <xs:documentation>Falls bekannt, ist hier der Todestag anzugeben. Ist der Todestag nicht bekannt, muss hier das Datum des Tages, an dem die Person mit Sicherheit tot war, angegeben werden.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="todeszeit" type="xpersonenstand:Uhrzeit">
                           <xs:annotation>
                              <xs:documentation>Falls bekannt, ist hier die Todeszeit anzugeben. Ist die Todeszeit nicht bekannt, muss hier die Uhrzeit, an der die Person mit Sicherheit tot war, angegeben werden.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="letzterTagLebend"
                                    minOccurs="0"
                                    type="xida:TeilbekanntesDatumMitUnbekannt">
                           <xs:annotation>
                              <xs:documentation>Sofern angegeben, ist in diesem optionalen Element das Datum des letzten Tages lebend anzugeben. Das Datum des Tages, an dem die Person mit Sicherheit tot war, ist im Element todestag anzugeben.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="letzteUhrzeitLebend"
                                    minOccurs="0"
                                    type="xpersonenstand:Uhrzeit">
                           <xs:annotation>
                              <xs:documentation>Sofern angegeben, ist in diesem optionalen Element die Uhrzeit anzugeben, an der die Person das letzte mal gelebt hat. Die Uhrzeit, an der die Person mit Sicherheit tot war, ist im Element todeszeit anzugeben.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="sterbeort" type="xpersonenstand:Ereignisort">
                           <xs:annotation>
                              <xs:documentation>Hier ist der Sterbeort anzugeben.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                     </xs:sequence>
                  </xs:complexType>
               </xs:element>
               <xs:element name="verstorbener" type="xpersonenstand:Datenabruf2StA.Verstorbener">
                  <xs:annotation>
                     <xs:documentation>Hier werden Namen, letzter Wohnort, Geburtsort und -tag sowie Familienstand des Verstorbenen aus dem Sterberegistereintrag übermittelt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="partnerNamen" minOccurs="0" type="xpersonenstand:PersonName">
                  <xs:annotation>
                     <xs:documentation>Hier werden die Namen des Ehepartners oder Lebenspartners aus dem Registereintrag mitgeteilt. Liegt keine Ehe oder Lebenspartnerschaft vor, wird dieses Feld nicht verwendet.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identitaetPartnerNichtNachgewiesen"
                           minOccurs="0"
                           fixed="true"
                           type="xs:boolean">
                  <xs:annotation>
                     <xs:documentation>Hier wird übermittelt, ob die Identität des Partners des Verstorbenen nicht nachgewiesen ist.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="eheDesVerstorbenen"
                           minOccurs="0"
                           type="xpersonenstand:Datenabruf2StA.Hinweis.Ehe">
                  <xs:annotation>
                     <xs:documentation>Hier können Hinweisdaten zur Ehe der verstorbenen Person übermittelt werden.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Template.Fehlernachricht" abstract="true">
      <xs:annotation>
         <xs:appinfo>
            <title>Template für die Fachliche Fehlernachricht zu einem Datenabruf</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp dient zur Ableitung von Nachrichten, die das abrufende Standesamt über den Art des Fehlers informiert, der bei der Bearbeitung des Datenabrufs aufgetreten ist. Dies ermöglicht dem abrufenden Standesamt, darauf angemessen zu reagieren, z. B. indem die Abrufnachricht modifiziert wird, oder ein anderes Standesamt angefragt wird. Die Fehlernachricht enthält alle Daten zur Zuordnung zur Abrufnachricht, die auch die registerspezifischen Antwortnachrichten enthalten. Da sie jedoch registerübergreifend ist, gibt es hier die Möglichkeit, alle möglichen Arten von Eintragsidentifikationen zu versenden.</xs:documentation>
      </xs:annotation>
      <xs:complexContent>
         <xs:extension base="xpersonenstand:Nachricht.G2GXP">
            <xs:sequence>
               <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                  <xs:annotation>
                     <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="abrufzweck" type="din91379:datatypeC">
                  <xs:annotation>
                     <xs:documentation>Hier wird der Zweck der Abrufnachricht, die zu der Fehlernachricht geführt hat, mitgeteilt.</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="identifikation">
                  <xs:annotation>
                     <xs:documentation>Die Eintragsidentifikation aus der Abrufnachricht an ein Register wird in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                  </xs:annotation>
                  <xs:complexType>
                     <xs:choice>
                        <xs:element name="identifikationGeburt"
                                    type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Geburt">
                           <xs:annotation>
                              <xs:documentation>Dieses Suchdaten werden aus der Abrufnachricht an ein Geburtenregister übernommen, um die Fehlernachricht der Abrufnachricht zuzuordnen.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="identifikationEheLP"
                                    type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.EheLP">
                           <xs:annotation>
                              <xs:documentation>Dieses Suchdaten werden aus der Abrufnachricht an ein Ehe- oder Lebenspartnerschaftsregister übernommen, um die Fehlernachricht der Abrufnachricht zuzuordnen.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                        <xs:element name="identifikationSterbefall"
                                    type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Sterbefall">
                           <xs:annotation>
                              <xs:documentation>Dieses Suchdaten werden aus der Abrufnachricht an ein Sterberegister übernommen, um die Fehlernachricht der Abrufnachricht zuzuordnen.</xs:documentation>
                           </xs:annotation>
                        </xs:element>
                     </xs:choice>
                  </xs:complexType>
               </xs:element>
               <xs:element name="fehlerart" type="xpersonenstand:Code.Fehlerart.Code">
                  <xs:annotation>
                     <xs:documentation>Hier wird die Art des Fehlers angegeben.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:extension>
      </xs:complexContent>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.VermerkAufloesung">
      <xs:annotation>
         <xs:appinfo>
            <title>Vermerk über eine Auflösung</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp kann dazu benutzt werden, Angaben zur Auflösung einer Lebenspartnerschaft oder einer Ehe zu übermitteln.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="datum" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Hier wird das Datum der Auflösung der Lebenspartnerschaft oder Ehe übermittelt. Aus dem Eheregister kann gesichert hier nur das Datum der Entscheidung über die Auflösung oder das Todesdatum des Ehepartners übermittelt werden. Damit wird unterschlagen, dass bei einer Todeserklärung das Todesdatum des Ehegatten nicht das Auflösungsdatum der Ehe ist. Das ist jedoch für die Prüfung der Ehefähigkeit nicht von Bedeutung, da auch bei einer Todeserklärung nach dem Tod des Partners eine neue Ehe eingegangen werden kann.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="art" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird die Art der Auflösung der Lebenspartnerschaft oder Ehe übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Verstorbener">
      <xs:annotation>
         <xs:appinfo>
            <title>Angaben zum Verstorbenen</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp enthält Namen, Geburtsort, Geburtstag, letzten Wohnort sowie Familienstand eines Verstorbenen. Die Daten werden dem Sterbeeintrag entnommen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen des Verstorbenen werden dem Sterbeeintrag entnommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="letzterWohnort" type="xpersonenstand:Ereignisort">
            <xs:annotation>
               <xs:documentation>Der letzte Wohnort des Verstorbenen wird dem Sterbeeintrag entnommen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburt" type="xpersonenstand:Datenabruf2StA.Geburt">
            <xs:annotation>
               <xs:documentation>Geburtsort sowie -tag des Verstorbenen werden dem Sterbeeintrag entnommen. Der Geburtstag kann teilbekannt sein, z. B. bei nachbeurkundeten Sterbefällen aus dem Ausland.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="familienstand"
                     minOccurs="0"
                     type="xpersonenstand:Code.FamilienstandPersonenstandswesen">
            <xs:annotation>
               <xs:documentation>Ist der Familienstand des Verstorbenen im Sterbeeintrag beurkundet, wird er hier übertragen.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="identitaetNichtNachgewiesen"
                     minOccurs="0"
                     fixed="true"
                     type="xs:boolean">
            <xs:annotation>
               <xs:documentation>Hier wird übermittelt, ob die Identität des Verstorbenen nicht nachgewiesen ist.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Datenabruf2StA.Zuordnung">
      <xs:annotation>
         <xs:appinfo>
            <title>Zuordnung</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuordnen zu können. Neben den hier aufgeführten allgemeinen Angaben muss die Antwortnachricht zur Zuordnung zur Abrufnachricht noch die Suchdaten aus der Abrufnachricht enthalten, diese sind je nach Register unterschiedlich.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="nachrichtenUUID" type="bn-uq-g2g:UUID" form="unqualified">
            <xs:annotation>
               <xs:documentation>Hier wird zum Zweck der Zuordnung die UUID der Abrufnachricht eingetragen, auf die diese Nachricht antwortet.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="vorgangsidentifikation" type="xink:Identifikation.Ereignis">
            <xs:annotation>
               <xs:documentation>Hier werden zum Zwecke der Zuordnung der Antwortnachricht zur Abrufnachricht die Angaben zur Vorgangsidentifikation aus der Abrufnachricht in der Antwortnachricht übermittelt. Diese Angaben werden durch das Fachverfahren ohne weiteres Zutun des Standesbeamten in die Nachricht übernommen. Im Kindelement ereignis.zeitpunkt wird der Erstellungszeitpunkt der Abrufnachricht übernommen. Im Kindelement ereignis.zeichen wird eine Zeichenkette übermittelt, die die Identifikation des auslösenden Geschäftsvorfalles im stamt ermöglicht (z. B. Vorgangsidentifikation oder Registereintragsidentifikation).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="zuordnung" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird die Zeichenkette zur Zuordnung aus der Abfragenachricht übermittelt, falls die Abfragenachricht eine solche enthielt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="datenabruf2StA.AbrufGeburt.018010">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Abruf eines Eintrags aus dem Geburtenregister</title>
         </xs:appinfo>
         <xs:documentation>Benötigt ein Standesamt, das eine Beurkundung in einem eigenen Personenstandsregister vorbereitet, Angaben über die Geburtsdaten einer beteiligten Person, dann können mit dieser Nachricht Daten aus einem Geburtenregistereintrag abgerufen werden. Die Nachricht enthält zusätzlich zu den Daten, die den gesuchten Geburtseintrag identifizieren sollen, Angaben zum Vorgang, die der Protokollierung des Abrufs, der Zuordnung einer etwaigen Antwortnachricht zu der Abrufnachricht, sowie der Prozesskontrolle dienen. Das Feld vorgangsidentifikation des Nachrichtenkopfes ist in der Abrufnachricht an das Geburtenregister verpflichtend zu benutzen. Gemeinsam mit nachrichtenkopf.identifikation.nachricht.nachrichtenUUID und eines Teils der Angaben in registerunabhaengigeAngaben dient es zur Zuordnung der Abrufnachricht zur Antwortnachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="registerunabhaengigeAngaben"
                              type="xpersonenstand:Datenabruf2StA.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Daten zum Vorgang und zum Abruf eingetragen, die für Abrufe aus allen Registern notwendig sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Zweck des Abrufs aus dem Geburtenregister mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="identifikationGeburtseintrag"
                              type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Geburt">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp identifiziert den gesuchten Geburtenregistereintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="mitElternLeiblich"
                              minOccurs="0"
                              fixed="true"
                              type="xs:boolean">
                     <xs:annotation>
                        <xs:documentation>Hier wird "True" übermittelt, wenn der Abruf (unter Anderem) zur Prüfung auf das Vorliegen des Ehehindernisses nach §§ 1307 und 1308 BGB dient. Damit wird die Information über die leiblichen Eltern auf die Fälle beschränkt, in denen ein besonderer Grund dies nach § 1758 BGB zulässt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortGeburtSynchron.018011">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Geburtenregister (Synchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs eines anderen Standesamtes Daten aus einem Geburtseintrag diesem übermittelt werden. Der Datenumfang entspricht dem der Geburtsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort synchron erfolgt. Für asynchrone Antworten wird die nachricht.ref.018012 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortGeburt"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortGeburtAsynchron.018012">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Geburtenregister (Asynchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs asynchron Daten aus einem Geburtseintrag übermittelt werden. Der Datenumfang entspricht dem der Geburtsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort asynchron erfolgt. Für synchrone Antworten wird die nachricht.ref.018011 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortGeburt"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AbrufGeburt.018015">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. Art. 13 SDG-VO und § 64 PStV</rechtsgrundlage>
            <title>Abruf eines Eintrags aus dem Geburtenregister aus dem EU-Ausland heraus</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können Daten aus einem Geburtenregistereintrag abgerufen werden, wobei die Nachricht ursprünglich aus dem EU-Ausland stammt und über die Intermediäre Plattform an das Standesamt geleitet wird. Die Nachricht enthält zusätzlich zu den Daten, die den gesuchten Geburtseintrag identifizieren sollen, Angaben zum Vorgang, die der Protokollierung des Abrufs, der Zuordnung einer etwaigen Antwortnachricht zu der Abrufnachricht, sowie der Prozesskontrolle dienen. Das Feld vorgangsidentifikation des Nachrichtenkopfes ist in der Abrufnachricht an das Geburtenregister verpflichtend zu benutzen. Gemeinsam mit nachrichtenkopf.identifikation.nachricht.nachrichtenUUID und eines Teils der Angaben in registerunabhaengigeAngaben dient es zur Zuordnung der Abrufnachricht zur Antwortnachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="registerunabhaengigeAngaben"
                              type="xpersonenstand:Datenabruf2StA.Abruf.Allgemeines.EU">
                     <xs:annotation>
                        <xs:documentation>Hier werden Daten zum Vorgang und zum Abruf eingetragen, die für Abrufe aus allen Registern notwendig sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Online-Dienst im EU-Ausland übermittelt, der den Nachweis benötigt. Diese Angabe wird zur Protokollierung des Anlass nach § 64 PStV genutzt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="suchdaten" type="xpersonenstand:Datenabruf2StA.Suchdaten.Geburt">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp identifiziert den gesuchten Geburtenregistereintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortGeburt.018016">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. Art. 13 SDG-VO und § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Geburtenregister an das EU-Ausland</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs aus dem EU-Ausland die Daten aus einem Geburtseintrag übermittelt werden, die dem Nachweis "Proof-of-Birth" entsprechen, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="zuordnung" type="xpersonenstand:Datenabruf2StA.Zuordnung">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp fasst die Informationen zusammen, die in allen Antwortnachrichten angegeben werden müssen, um sie der Abrufnachricht zuzuordnen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Zweck des ursprünglichen Abrufs aus dem Geburtenregister mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="suchdaten" type="xpersonenstand:Datenabruf2StA.Suchdaten.Geburt">
                     <xs:annotation>
                        <xs:documentation>Die Suchdaten aus der Abrufnachricht an ein Geburtenregister werden in die Antwortnachricht zur Zuordnung der Nachrichten übernommen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="registernummer"
                              type="xpersonenstand:Datenabruf2StA.Registernummer">
                     <xs:annotation>
                        <xs:documentation>Hier wird die Registernummer des Registereintrags übermittelt, aus dem die Daten übernommen wurden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtsnachweis" type="xpersonenstand:Datenabruf2StA.Geburt.EU">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben zur Geburt übermittelt. Sie werden dem Geburtsregistereintrag entnommen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AbrufEhe.018020">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Abruf eines Eintrags aus dem Eheregister</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können Daten aus einem Eheeintrag abgerufen werden. Die Nachricht enthält zusätzlich zu den Daten, die den gesuchten Eheeintrag identifizieren sollen, Angaben zum Vorgang, die der Protokollierung des Abrufs, der Zuordnung einer etwaigen Antwortnachricht zu der Abrufnachricht, sowie der Prozesskontrolle dienen. Das Feld vorgangsidentifikation des Nachrichtenkopfes ist in der Abrufnachricht an das Eheregister verpflichtend zu benutzen. Gemeinsam mit nachrichtenkopf.identifikation.nachricht.nachrichtenUUID und eines Teils der Angaben in registerunabhaengigeAngaben dient es zur Zuordnung der Abrufnachricht zur Antwortnachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="registerunabhaengigeAngaben"
                              type="xpersonenstand:Datenabruf2StA.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Daten zum Vorgang und zum Abruf eingetragen, die für Abrufe aus allen Registern notwendig sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Zweck des Abrufs aus dem Eheregister mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="identifikationEheeintrag"
                              type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.EheLP">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp identifiziert den gesuchten Eheeintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortEheSynchron.018021">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Eheregister (Synchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs eines anderen Standesamtes Daten aus einem Eheeintrag übermittelt werden. Der Datenumfang entspricht dem der Eheurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort synchron erfolgt. Für asynchrone Antworten wird die nachricht.ref.018022 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortEhe"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortEheAsynchron.018022">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Eheregister (Asynchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs asynchron Daten aus einem Eheeintrag übermittelt werden. Der Datenumfang entspricht dem der Eheurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort asynchron erfolgt. Für synchrone Antworten wird die nachricht.ref.018011 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortEhe"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AbrufLP.018030">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Abruf eines Eintrags aus dem Lebenspartnerschaftsregister</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können Daten aus einem Lebenspartnerschaftseintrag abgerufen werden. Die Nachricht enthält zusätzlich zu den Daten, die den gesuchten Lebenspartnerschaftseintrag identifizieren sollen, Angaben zum Vorgang, die der Protokollierung des Abrufs, der Zuordnung einer etwaigen Antwortnachricht zu der Abrufnachricht, sowie der Prozesskontrolle dienen. Das Feld vorgangsidentifikation des Nachrichtenkopfes ist in der Abrufnachricht an das Lebenspartnerschaftsregisterregister verpflichtend zu benutzen. Gemeinsam mit nachrichtenkopf.identifikation.nachricht.nachrichtenUUID und eines Teils der Angaben in registerunabhaengigeAngaben dient es zur Zuordnung der Abrufnachricht zur Antwortnachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="registerunabhaengigeAngaben"
                              type="xpersonenstand:Datenabruf2StA.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Daten zum Vorgang und zum Abruf eingetragen, die für Abrufe aus allen Registern notwendig sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Zweck des Abrufs aus dem Lebenspartnerschaftsregister mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="identifikationLPeintrag"
                              type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.EheLP">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp identifiziert den gesuchten Lebenspartnerschaftseintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortLPSynchron.018031">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Lebenspartnerschaftsregister (Synchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs eines anderen Standesamtes Daten aus einem Lebenspartnerschaftseintrag übermittelt werden. Der Datenumfang entspricht dem der Lebenspartnerschaftsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort synchron erfolgt. Für asynchrone Antworten wird die nachricht.ref.018032 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortLP"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortLPAsynchron.018032">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Lebenspartnerschaftsregister (Asynchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs asynchron Daten aus einem Lebenspartnerschaftseintrag übermittelt werden. Der Datenumfang entspricht dem der Lebenspartnerschaftsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort asynchron erfolgt. Für synchrone Antworten wird die nachricht.ref.018031 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortLP"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AbrufSterbefall.018040">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Abruf eines Eintrags aus dem Sterberegister</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können Daten aus einem Sterbeeintrag abgerufen werden. Die Nachricht enthält zusätzlich zu den Daten, die den gesuchten Sterbeeintrag identifizieren sollen, Angaben zum Vorgang, die der Protokollierung des Abrufs, der Zuordnung einer etwaigen Antwortnachricht zu der Abrufnachricht, sowie der Prozesskontrolle dienen. Das Feld vorgangsidentifikation des Nachrichtenkopfes ist in der Abrufnachricht an das Sterberegister verpflichtend zu benutzen. Gemeinsam mit nachrichtenkopf.identifikation.nachricht.nachrichtenUUID und eines Teils der Angaben in registerunabhaengigeAngaben dient es zur Zuordnung der Abrufnachricht zur Antwortnachricht.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="registerunabhaengigeAngaben"
                              type="xpersonenstand:Datenabruf2StA.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Daten zum Vorgang und zum Abruf eingetragen, die für Abrufe aus allen Registern notwendig sind.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="abrufzweck" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Zweck des Abrufs aus dem Sterberegister mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="identifikationSterbeeintrag"
                              type="xpersonenstand:Datenabruf2StA.Eintragsidentifikation.Sterbefall">
                     <xs:annotation>
                        <xs:documentation>Dieser Datentyp identifiziert den gesuchten Sterbeeintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortSterbefallSynchron.018041">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Sterberegister (Synchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs eines anderen Standesamtes Daten aus einem Sterbeeintrag übermittelt werden. Der Datenumfang entspricht dem der Sterbeurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort synchron erfolgt. Für asynchrone Antworten wird die nachricht.ref.018042 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortSterbefall"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.AntwortSterbefallAsynchron.018042">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Antwort aus einem Eintrag im Sterberegister (Asynchron)</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht können zur Beantwortung eines Datenabrufs asynchron Daten aus einem Sterbeeintrag übermittelt werden. Der Datenumfang entspricht dem der Sterbeurkunde, wobei zusätzliche Angaben aus der Abrufachricht zur Zuordnung der Abrufachricht zur Antwortnachricht übermittelt werden. Diese Nachricht wird verwendet, wenn die Antwort asynchron erfolgt. Für synchrone Antworten wird die nachricht.ref.018041 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.AntwortSterbefall"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.FehlernachrichtSynchron.018050">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Fachliche Fehlernachricht nach einem Datenabruf (Synchron)</title>
         </xs:appinfo>
         <xs:documentation>Die Fehlernachricht informiert das abrufende Standesamt synchron über den Art des Fehlers, der bei der Bearbeitung des Datenabrufs aufgetreten ist. Dies ermöglicht dem abrufenden Standesamt, darauf angemessen zu reagieren, z. B. indem die Abrufnachricht modifiziert wird, oder ein anderes Standesamt angefragt wird. Die Fehlernachricht enthält alle Daten zur Zuordnung zur Abrufnachricht, die auch die registerspezifischen Antwortnachrichten enthalten. Da sie jedoch registerübergreifend ist, gibt es hier die Möglichkeit, alle möglichen Arten von Eintragsidentifikationen zu versenden. Diese Nachricht wird verwendet, wenn die Antwort synchron erfolgt. Für asynchrone Antworten wird die nachricht.ref.018052 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.Fehlernachricht"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.FehlernachrichtAsynchron.018052">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Fachliche Fehlernachricht nach einem Datenabruf (Asynchron)</title>
         </xs:appinfo>
         <xs:documentation>Die Fehlernachricht informiert das abrufende Standesamt asynchron über den Art des Fehlers, der bei der Bearbeitung des Datenabrufs aufgetreten ist. Dies ermöglicht dem abrufenden Standesamt, darauf angemessen zu reagieren, z. B. indem die Abrufnachricht modifiziert wird, oder ein anderes Standesamt angefragt wird. Die Fehlernachricht enthält alle Daten zur Zuordnung zur Abrufnachricht, die auch die registerspezifischen Antwortnachrichten enthalten. Da sie jedoch registerübergreifend ist, gibt es hier die Möglichkeit, alle möglichen Arten von Eintragsidentifikationen zu versenden. Diese Nachricht wird verwendet, wenn die Antwort asynchron erfolgt. Für synchrone Antworten wird die nachricht.ref.018050 verwendet.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Datenabruf2StA.Template.Fehlernachricht"/>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="datenabruf2StA.Fehlernachricht.018060">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt</autor>
            <leser>Standesamt</leser>
            <rechtsgrundlage>§ 68 PStG i.V.m. § 64 PStV</rechtsgrundlage>
            <title>Technische Fehlernachricht nach einem Datenabruf</title>
         </xs:appinfo>
         <xs:documentation>Die technische Fehlernachricht informiert das abrufende Standesamt darüber, dass die Bearbeitung des Datenabrufs aufgrund eines technischen Fehlers in der Datenübermittlung nicht möglich ist. Dies ermöglicht dem abrufenden Standesamt, darauf angemessen zu reagieren, z. B. indem die Abrufnachricht modifiziert wird, oder das Standesamt zu einem späteren Zeitpunkt erneut angefragt wird. Die technische Fehlernachricht für die Datenabrufe enthält die Nachricht, die zurückgewiesen wurde, sowie den Rückweisungsgrund.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="ursprungsnachricht" type="xs:base64Binary">
                     <xs:annotation>
                        <xs:documentation>Hier wird das XML der Ursprungsnachricht als base64 zurückgesendet.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="fehler" type="xirts:Code.Fehlercode.XInneres">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Fehlercode übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
</xs:schema>
