//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.osci.xinneres.rueckweisung._6;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.osci.xinneres.rueckweisung._6 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.osci.xinneres.rueckweisung._6
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CodeFehlercodeXInneres }
     * 
     * @return
     *     the new instance of {@link CodeFehlercodeXInneres }
     */
    public CodeFehlercodeXInneres createCodeFehlercodeXInneres() {
        return new CodeFehlercodeXInneres();
    }

    /**
     * Create an instance of {@link RueckweisungAsynchron0010 }
     * 
     * @return
     *     the new instance of {@link RueckweisungAsynchron0010 }
     */
    public RueckweisungAsynchron0010 createRueckweisungAsynchron0010() {
        return new RueckweisungAsynchron0010();
    }

    /**
     * Create an instance of {@link NachrichtG2GRueckweisung }
     * 
     * @return
     *     the new instance of {@link NachrichtG2GRueckweisung }
     */
    public NachrichtG2GRueckweisung createNachrichtG2GRueckweisung() {
        return new NachrichtG2GRueckweisung();
    }

    /**
     * Create an instance of {@link RueckweisungTemplateAsynchron }
     * 
     * @return
     *     the new instance of {@link RueckweisungTemplateAsynchron }
     */
    public RueckweisungTemplateAsynchron createRueckweisungTemplateAsynchron() {
        return new RueckweisungTemplateAsynchron();
    }

    /**
     * Create an instance of {@link CodeFehlercodeSpezifisch }
     * 
     * @return
     *     the new instance of {@link CodeFehlercodeSpezifisch }
     */
    public CodeFehlercodeSpezifisch createCodeFehlercodeSpezifisch() {
        return new CodeFehlercodeSpezifisch();
    }

    /**
     * Create an instance of {@link RueckweisungEinzelfall }
     * 
     * @return
     *     the new instance of {@link RueckweisungEinzelfall }
     */
    public RueckweisungEinzelfall createRueckweisungEinzelfall() {
        return new RueckweisungEinzelfall();
    }

    /**
     * Create an instance of {@link RueckweisungGrundSpezifisch }
     * 
     * @return
     *     the new instance of {@link RueckweisungGrundSpezifisch }
     */
    public RueckweisungGrundSpezifisch createRueckweisungGrundSpezifisch() {
        return new RueckweisungGrundSpezifisch();
    }

    /**
     * Create an instance of {@link RueckweisungRueckweisendeStelle }
     * 
     * @return
     *     the new instance of {@link RueckweisungRueckweisendeStelle }
     */
    public RueckweisungRueckweisendeStelle createRueckweisungRueckweisendeStelle() {
        return new RueckweisungRueckweisendeStelle();
    }

    /**
     * Create an instance of {@link RueckweisungRueckweisungsgrund }
     * 
     * @return
     *     the new instance of {@link RueckweisungRueckweisungsgrund }
     */
    public RueckweisungRueckweisungsgrund createRueckweisungRueckweisungsgrund() {
        return new RueckweisungRueckweisungsgrund();
    }

    /**
     * Create an instance of {@link RueckweisungTemplate }
     * 
     * @return
     *     the new instance of {@link RueckweisungTemplate }
     */
    public RueckweisungTemplate createRueckweisungTemplate() {
        return new RueckweisungTemplate();
    }

    /**
     * Create an instance of {@link RueckweisungTransportinformationen }
     * 
     * @return
     *     the new instance of {@link RueckweisungTransportinformationen }
     */
    public RueckweisungTransportinformationen createRueckweisungTransportinformationen() {
        return new RueckweisungTransportinformationen();
    }

}
