//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.osci.xinneres.rueckweisung._6;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * In diesem Datentyp wird ein Grund für die Rückweisung der Nachricht in Form eines beliebigen kontextspezifischen Fehlercodes (bspw. aus dem BZSt-Fehlerkatalog) oder einer Fehlerbeschreibung genauer spezifiziert. Sofern in einem (fachlichen) Prozess kontextspezifische Fehlercodes verwendet werden, ist dies durch das xinneres-fachmodul in der Prozessbeschreibung vorzugeben und die zu verwendende Schlüsseltabelle festzulegen.
 * 
 * <p>Java class for Rueckweisung.GrundSpezifisch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Rueckweisung.GrundSpezifisch">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="fehlercode" type="{http://www.osci.de/xinneres/rueckweisung/6}Code.Fehlercode.Spezifisch" minOccurs="0"/>
 *         <element name="fehlerbeschreibung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rueckweisung.GrundSpezifisch", propOrder = {
    "fehlercode",
    "fehlerbeschreibung"
})
public class RueckweisungGrundSpezifisch {

    protected CodeFehlercodeSpezifisch fehlercode;
    protected String fehlerbeschreibung;

    /**
     * Gets the value of the fehlercode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFehlercodeSpezifisch }
     *     
     */
    public CodeFehlercodeSpezifisch getFehlercode() {
        return fehlercode;
    }

    /**
     * Sets the value of the fehlercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFehlercodeSpezifisch }
     *     
     */
    public void setFehlercode(CodeFehlercodeSpezifisch value) {
        this.fehlercode = value;
    }

    /**
     * Gets the value of the fehlerbeschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFehlerbeschreibung() {
        return fehlerbeschreibung;
    }

    /**
     * Sets the value of the fehlerbeschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFehlerbeschreibung(String value) {
        this.fehlerbeschreibung = value;
    }

}
