//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import com.vertama.xpersonenstand._2511.model.de.osci.xinneres.auslandsanschrift._5.AuslandsanschriftDruckbild;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese Klasse Anschrift.InlandAusland ermöglicht im Standard XPersonenstand als Auswahl der zu nutzenden Anschrift die Nutzung der Klasse Anschrift.Inland zur Übermittlung von inländischen Anschriften oder der Klassen Auslandsanschrift.Druckbild (XI) bzw. Auslandsanschrift.Strukturiert zur Übermittlung von ausländischen Anschriften.
 * 
 * <p>Java class for Anschrift.InlandAusland complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Anschrift.InlandAusland">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="anschriftInland" type="{http://xpsw.domap.de/xpsw2511}Anschrift.Inland"/>
 *         <element name="anschriftAusland" type="{http://www.osci.de/xinneres/auslandsanschrift/5}Auslandsanschrift.Druckbild"/>
 *         <element name="anschriftAuslandStrukturiert" type="{http://xpsw.domap.de/xpsw2511}Auslandsanschrift.Strukturiert"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anschrift.InlandAusland", propOrder = {
    "anschriftInland",
    "anschriftAusland",
    "anschriftAuslandStrukturiert"
})
public class AnschriftInlandAusland {

    protected AnschriftInland anschriftInland;
    protected AuslandsanschriftDruckbild anschriftAusland;
    protected AuslandsanschriftStrukturiert anschriftAuslandStrukturiert;

    /**
     * Gets the value of the anschriftInland property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftInland() {
        return anschriftInland;
    }

    /**
     * Sets the value of the anschriftInland property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftInland(AnschriftInland value) {
        this.anschriftInland = value;
    }

    /**
     * Gets the value of the anschriftAusland property.
     * 
     * @return
     *     possible object is
     *     {@link AuslandsanschriftDruckbild }
     *     
     */
    public AuslandsanschriftDruckbild getAnschriftAusland() {
        return anschriftAusland;
    }

    /**
     * Sets the value of the anschriftAusland property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuslandsanschriftDruckbild }
     *     
     */
    public void setAnschriftAusland(AuslandsanschriftDruckbild value) {
        this.anschriftAusland = value;
    }

    /**
     * Gets the value of the anschriftAuslandStrukturiert property.
     * 
     * @return
     *     possible object is
     *     {@link AuslandsanschriftStrukturiert }
     *     
     */
    public AuslandsanschriftStrukturiert getAnschriftAuslandStrukturiert() {
        return anschriftAuslandStrukturiert;
    }

    /**
     * Sets the value of the anschriftAuslandStrukturiert property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuslandsanschriftStrukturiert }
     *     
     */
    public void setAnschriftAuslandStrukturiert(AuslandsanschriftStrukturiert value) {
        this.anschriftAuslandStrukturiert = value;
    }

}
