//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Abstrakter Basisnachrichtentyp für Datenübermittlungen zwischen dem Standesamt I in Berlin und anderen Standesämtern. Bei jeder Mitteilung werden übermittelt: Nachrichtenkopf mit Angaben zum Absender und zum Empfänger und zum Erstellungszeitpunkt und Grund der Nachricht Angaben, um den Registereintrag auf Seiten des empfangenden stamtgen zu identifizieren, bei dem eine personenstandsrechtliche Veränderung und / oder Ergänzung vorzunehmen ist Optional Angaben zum Auffinden des zum Eheeintrag umgewidmeten Familienbuches
 * 
 * <p>Java class for Nachricht.StA1B2StA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Nachricht.StA1B2StA">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="registereintrag" type="{http://xpsw.domap.de/xpsw2511}StA1B2StA.Identifikation.Zieleintrag"/>
 *         <element name="familienbuch" type="{http://xpsw.domap.de/xpsw2511}Identifikation.Familienbuch" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachricht.StA1B2StA", propOrder = {
    "registereintrag",
    "familienbuch"
})
@XmlSeeAlso({
    StA1B2StASammlungUeberTodeserklaerungen094014 .class,
    StA1B2StASammlungUeberTodeserklaerungen094013 .class,
    StA1B2StASammlungUeberTodeserklaerungen094012 .class,
    StA1B2StASammlungUeberTodeserklaerungen094011 .class
})
public abstract class NachrichtStA1B2StA
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected StA1B2StAIdentifikationZieleintrag registereintrag;
    protected IdentifikationFamilienbuch familienbuch;

    /**
     * Gets the value of the registereintrag property.
     * 
     * @return
     *     possible object is
     *     {@link StA1B2StAIdentifikationZieleintrag }
     *     
     */
    public StA1B2StAIdentifikationZieleintrag getRegistereintrag() {
        return registereintrag;
    }

    /**
     * Sets the value of the registereintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA1B2StAIdentifikationZieleintrag }
     *     
     */
    public void setRegistereintrag(StA1B2StAIdentifikationZieleintrag value) {
        this.registereintrag = value;
    }

    /**
     * Gets the value of the familienbuch property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationFamilienbuch }
     *     
     */
    public IdentifikationFamilienbuch getFamilienbuch() {
        return familienbuch;
    }

    /**
     * Sets the value of the familienbuch property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationFamilienbuch }
     *     
     */
    public void setFamilienbuch(IdentifikationFamilienbuch value) {
        this.familienbuch = value;
    }

}
