//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.vertama.xpersonenstand._2511.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2G">
 *       <sequence>
 *         <element name="antragsteller" type="{http://xpsw.domap.de/xpsw2511}Urkundenanforderung.Antragsteller.Papier"/>
 *         <element name="modalitaeten" type="{http://xpsw.domap.de/xpsw2511}Urkundenanforderung.Modalitaeten" minOccurs="0"/>
 *         <element name="verwendungszweck" type="{http://xpsw.domap.de/xpsw2511}Code.VerwendungszweckLPurkunde" minOccurs="0"/>
 *         <element name="beurkundeteLP">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="lebenspartner1" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *                   <element name="lebenspartner2" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *                   <element name="datumBegruendung" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *                   <element name="ortBegruendung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                   <element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="angeforderteUrkunden" type="{http://xpsw.domap.de/xpsw2511}Urkundenanforderung.EL"/>
 *         <element name="anhang" type="{http://xpsw.domap.de/xpsw2511}AnhangInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "antragsteller",
    "modalitaeten",
    "verwendungszweck",
    "beurkundeteLP",
    "angeforderteUrkunden",
    "anhang"
})
@XmlRootElement(name = "portal2StA.LP.083030")
public class Portal2StALP083030
    extends NachrichtG2G
{

    @XmlElement(required = true)
    protected UrkundenanforderungAntragstellerPapier antragsteller;
    protected UrkundenanforderungModalitaeten modalitaeten;
    protected CodeVerwendungszweckLPurkunde verwendungszweck;
    @XmlElement(required = true)
    protected Portal2StALP083030 .BeurkundeteLP beurkundeteLP;
    @XmlElement(required = true)
    protected UrkundenanforderungEL angeforderteUrkunden;
    protected List<AnhangInformation> anhang;

    /**
     * Gets the value of the antragsteller property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungAntragstellerPapier }
     *     
     */
    public UrkundenanforderungAntragstellerPapier getAntragsteller() {
        return antragsteller;
    }

    /**
     * Sets the value of the antragsteller property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungAntragstellerPapier }
     *     
     */
    public void setAntragsteller(UrkundenanforderungAntragstellerPapier value) {
        this.antragsteller = value;
    }

    /**
     * Gets the value of the modalitaeten property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungModalitaeten }
     *     
     */
    public UrkundenanforderungModalitaeten getModalitaeten() {
        return modalitaeten;
    }

    /**
     * Sets the value of the modalitaeten property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungModalitaeten }
     *     
     */
    public void setModalitaeten(UrkundenanforderungModalitaeten value) {
        this.modalitaeten = value;
    }

    /**
     * Gets the value of the verwendungszweck property.
     * 
     * @return
     *     possible object is
     *     {@link CodeVerwendungszweckLPurkunde }
     *     
     */
    public CodeVerwendungszweckLPurkunde getVerwendungszweck() {
        return verwendungszweck;
    }

    /**
     * Sets the value of the verwendungszweck property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeVerwendungszweckLPurkunde }
     *     
     */
    public void setVerwendungszweck(CodeVerwendungszweckLPurkunde value) {
        this.verwendungszweck = value;
    }

    /**
     * Gets the value of the beurkundeteLP property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StALP083030 .BeurkundeteLP }
     *     
     */
    public Portal2StALP083030 .BeurkundeteLP getBeurkundeteLP() {
        return beurkundeteLP;
    }

    /**
     * Sets the value of the beurkundeteLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StALP083030 .BeurkundeteLP }
     *     
     */
    public void setBeurkundeteLP(Portal2StALP083030 .BeurkundeteLP value) {
        this.beurkundeteLP = value;
    }

    /**
     * Gets the value of the angeforderteUrkunden property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungEL }
     *     
     */
    public UrkundenanforderungEL getAngeforderteUrkunden() {
        return angeforderteUrkunden;
    }

    /**
     * Sets the value of the angeforderteUrkunden property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungEL }
     *     
     */
    public void setAngeforderteUrkunden(UrkundenanforderungEL value) {
        this.angeforderteUrkunden = value;
    }

    /**
     * Gets the value of the anhang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anhang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnhang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnhangInformation }
     * 
     * 
     * @return
     *     The value of the anhang property.
     */
    public List<AnhangInformation> getAnhang() {
        if (anhang == null) {
            anhang = new ArrayList<>();
        }
        return this.anhang;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="lebenspartner1" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
     *         <element name="lebenspartner2" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
     *         <element name="datumBegruendung" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
     *         <element name="ortBegruendung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *         <element name="registernummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lebenspartner1",
        "lebenspartner2",
        "datumBegruendung",
        "ortBegruendung",
        "registernummer"
    })
    public static class BeurkundeteLP {

        @XmlElement(required = true)
        protected PersonName lebenspartner1;
        @XmlElement(required = true)
        protected PersonName lebenspartner2;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateAdapter.class)
        @XmlSchemaType(name = "date")
        protected LocalDate datumBegruendung;
        @XmlElement(required = true)
        protected String ortBegruendung;
        protected String registernummer;

        /**
         * Gets the value of the lebenspartner1 property.
         * 
         * @return
         *     possible object is
         *     {@link PersonName }
         *     
         */
        public PersonName getLebenspartner1() {
            return lebenspartner1;
        }

        /**
         * Sets the value of the lebenspartner1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonName }
         *     
         */
        public void setLebenspartner1(PersonName value) {
            this.lebenspartner1 = value;
        }

        /**
         * Gets the value of the lebenspartner2 property.
         * 
         * @return
         *     possible object is
         *     {@link PersonName }
         *     
         */
        public PersonName getLebenspartner2() {
            return lebenspartner2;
        }

        /**
         * Sets the value of the lebenspartner2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonName }
         *     
         */
        public void setLebenspartner2(PersonName value) {
            this.lebenspartner2 = value;
        }

        /**
         * Gets the value of the datumBegruendung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public LocalDate getDatumBegruendung() {
            return datumBegruendung;
        }

        /**
         * Sets the value of the datumBegruendung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumBegruendung(LocalDate value) {
            this.datumBegruendung = value;
        }

        /**
         * Gets the value of the ortBegruendung property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrtBegruendung() {
            return ortBegruendung;
        }

        /**
         * Sets the value of the ortBegruendung property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrtBegruendung(String value) {
            this.ortBegruendung = value;
        }

        /**
         * Gets the value of the registernummer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegisternummer() {
            return registernummer;
        }

        /**
         * Sets the value of the registernummer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegisternummer(String value) {
            this.registernummer = value;
        }

    }

}
