//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import com.vertama.xpersonenstand._2511.model.de.osci.xinneres.datum._2.TeilbekanntesDatumMitUnbekannt;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2StA1B.Nachbeurkundung">
 *       <sequence>
 *         <element name="verstorbener" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatumMitUnbekannt"/>
 *         <element name="nachbeurkundeterSterbefall" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Quelleintrag"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "verstorbener",
    "geburtsdatum",
    "nachbeurkundeterSterbefall"
})
@XmlRootElement(name = "stA1B.Sterbefall.024010")
public class StA1BSterbefall024010
    extends NachrichtStA2StA1BNachbeurkundung
{

    @XmlElement(required = true)
    protected PersonName verstorbener;
    @XmlElement(required = true)
    protected TeilbekanntesDatumMitUnbekannt geburtsdatum;
    @XmlElement(required = true)
    protected BeurkundeteDatenQuelleintrag nachbeurkundeterSterbefall;

    /**
     * Gets the value of the verstorbener property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getVerstorbener() {
        return verstorbener;
    }

    /**
     * Sets the value of the verstorbener property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setVerstorbener(PersonName value) {
        this.verstorbener = value;
    }

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public TeilbekanntesDatumMitUnbekannt getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public void setGeburtsdatum(TeilbekanntesDatumMitUnbekannt value) {
        this.geburtsdatum = value;
    }

    /**
     * Gets the value of the nachbeurkundeterSterbefall property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenQuelleintrag }
     *     
     */
    public BeurkundeteDatenQuelleintrag getNachbeurkundeterSterbefall() {
        return nachbeurkundeterSterbefall;
    }

    /**
     * Sets the value of the nachbeurkundeterSterbefall property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenQuelleintrag }
     *     
     */
    public void setNachbeurkundeterSterbefall(BeurkundeteDatenQuelleintrag value) {
        this.nachbeurkundeterSterbefall = value;
    }

}
