//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2StA">
 *       <sequence>
 *         <element name="anschriftDesKindes" type="{http://xpsw.domap.de/xpsw2511}Anschrift.Inland" minOccurs="0"/>
 *         <element name="erklaerung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="einwilligungElternteil" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="einwilligung" type="{http://xpsw.domap.de/xpsw2511}StA2StA.Erklaerung.Einwilligung"/>
 *                   <element name="sterbefall" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Zeitraum.Registereintrag.Flexibel"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "anschriftDesKindes",
    "erklaerung",
    "einwilligungElternteil"
})
@XmlRootElement(name = "stA2StA.Erklaerung.011211")
public class StA2StAErklaerung011211
    extends NachrichtStA2StA
{

    protected AnschriftInland anschriftDesKindes;
    @XmlElement(required = true)
    protected String erklaerung;
    protected StA2StAErklaerung011211 .EinwilligungElternteil einwilligungElternteil;

    /**
     * Gets the value of the anschriftDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftDesKindes() {
        return anschriftDesKindes;
    }

    /**
     * Sets the value of the anschriftDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftDesKindes(AnschriftInland value) {
        this.anschriftDesKindes = value;
    }

    /**
     * Gets the value of the erklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErklaerung() {
        return erklaerung;
    }

    /**
     * Sets the value of the erklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErklaerung(String value) {
        this.erklaerung = value;
    }

    /**
     * Gets the value of the einwilligungElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link StA2StAErklaerung011211 .EinwilligungElternteil }
     *     
     */
    public StA2StAErklaerung011211 .EinwilligungElternteil getEinwilligungElternteil() {
        return einwilligungElternteil;
    }

    /**
     * Sets the value of the einwilligungElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2StAErklaerung011211 .EinwilligungElternteil }
     *     
     */
    public void setEinwilligungElternteil(StA2StAErklaerung011211 .EinwilligungElternteil value) {
        this.einwilligungElternteil = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="einwilligung" type="{http://xpsw.domap.de/xpsw2511}StA2StA.Erklaerung.Einwilligung"/>
     *         <element name="sterbefall" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Zeitraum.Registereintrag.Flexibel"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "einwilligung",
        "sterbefall"
    })
    public static class EinwilligungElternteil {

        protected StA2StAErklaerungEinwilligung einwilligung;
        protected BeurkundeteDatenZeitraumRegistereintragFlexibel sterbefall;

        /**
         * Gets the value of the einwilligung property.
         * 
         * @return
         *     possible object is
         *     {@link StA2StAErklaerungEinwilligung }
         *     
         */
        public StA2StAErklaerungEinwilligung getEinwilligung() {
            return einwilligung;
        }

        /**
         * Sets the value of the einwilligung property.
         * 
         * @param value
         *     allowed object is
         *     {@link StA2StAErklaerungEinwilligung }
         *     
         */
        public void setEinwilligung(StA2StAErklaerungEinwilligung value) {
            this.einwilligung = value;
        }

        /**
         * Gets the value of the sterbefall property.
         * 
         * @return
         *     possible object is
         *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
         *     
         */
        public BeurkundeteDatenZeitraumRegistereintragFlexibel getSterbefall() {
            return sterbefall;
        }

        /**
         * Sets the value of the sterbefall property.
         * 
         * @param value
         *     allowed object is
         *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
         *     
         */
        public void setSterbefall(BeurkundeteDatenZeitraumRegistereintragFlexibel value) {
            this.sterbefall = value;
        }

    }

}
