//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese Klasse bildet die Grundlage zur Übermittlung von statistischen Daten zum Ehegatten oder Lebenspartner.
 * 
 * <p>Java class for StA2Stat.Partner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2Stat.Partner">
 *   <complexContent>
 *     <restriction base="{http://xpsw.domap.de/xpsw2511}Statistik.Partner">
 *       <sequence>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2511}Statistik.Anschrift"/>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatumMitUnbekannt"/>
 *         <element name="bisherigerFamilienstand" type="{http://xpsw.domap.de/xpsw2511}Code.FamilienstandPersonenstandswesen"/>
 *         <element name="staatsangehoerigkeit" type="{http://xpsw.domap.de/xpsw2511}Code.Staatsangehoerigkeit"/>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2Stat.Partner")
public class StA2StatPartner
    extends StatistikPartner
{


}
