//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import com.vertama.xpersonenstand._2511.model.de.osci.xinneres.allgemeinername._4.AllgemeinerName;
import com.vertama.xpersonenstand._2511.model.de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2MB">
 *       <sequence>
 *         <element name="geschlechtNeu" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht" minOccurs="0"/>
 *         <element name="aenderungName" type="{http://xpsw.domap.de/xpsw2511}StA2MB.Nachweisdaten" minOccurs="0"/>
 *         <element name="vornamenNeu" type="{http://www.osci.de/xinneres/allgemeinername/4}AllgemeinerName" minOccurs="0"/>
 *         <element name="rechtsgrundlage" type="{http://xpsw.domap.de/xpsw2511}Code.Rechtsgrundlage" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geschlechtNeu",
    "aenderungName",
    "vornamenNeu",
    "rechtsgrundlage"
})
@XmlRootElement(name = "stA2MB.Geburt.031030")
public class StA2MBGeburt031030
    extends NachrichtStA2MB
{

    protected CodeGeschlecht geschlechtNeu;
    protected StA2MBNachweisdaten aenderungName;
    protected AllgemeinerName vornamenNeu;
    protected CodeRechtsgrundlage rechtsgrundlage;

    /**
     * Gets the value of the geschlechtNeu property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlechtNeu() {
        return geschlechtNeu;
    }

    /**
     * Sets the value of the geschlechtNeu property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlechtNeu(CodeGeschlecht value) {
        this.geschlechtNeu = value;
    }

    /**
     * Gets the value of the aenderungName property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public StA2MBNachweisdaten getAenderungName() {
        return aenderungName;
    }

    /**
     * Sets the value of the aenderungName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public void setAenderungName(StA2MBNachweisdaten value) {
        this.aenderungName = value;
    }

    /**
     * Gets the value of the vornamenNeu property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerName }
     *     
     */
    public AllgemeinerName getVornamenNeu() {
        return vornamenNeu;
    }

    /**
     * Sets the value of the vornamenNeu property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerName }
     *     
     */
    public void setVornamenNeu(AllgemeinerName value) {
        this.vornamenNeu = value;
    }

    /**
     * Gets the value of the rechtsgrundlage property.
     * 
     * @return
     *     possible object is
     *     {@link CodeRechtsgrundlage }
     *     
     */
    public CodeRechtsgrundlage getRechtsgrundlage() {
        return rechtsgrundlage;
    }

    /**
     * Sets the value of the rechtsgrundlage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeRechtsgrundlage }
     *     
     */
    public void setRechtsgrundlage(CodeRechtsgrundlage value) {
        this.rechtsgrundlage = value;
    }

}
