//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import com.vertama.xpersonenstand._2511.model.de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese Klasse enthält die Daten, die in der Kommunikation zwischen Standesämtern und Meldebehörden eine Person kennzeichnen. Durch die hier übermittelten Daten soll der Empfänger in die Lage versetzt werden, eine eindeutige Identifikation des Betroffenen auf Basis der im eigenen Register vorliegenden Daten vorzunehmen. Für die Kindelemente namen und geburtsangaben wird jeweils der aktuelle Stand der Daten aus dem Personenstandsregister übermittelt. D. h. insbesondere Daten, die aus vorgelegten Dokumenten, etwa Aufenthaltsbescheinigungen, entnommen wurden, werden nicht übermittelt.
 * 
 * <p>Java class for StA2MB.Person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2MB.Person">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namen" type="{http://xpsw.domap.de/xpsw2511}StA2MB.PersonName"/>
 *         <element name="geburtsangaben" type="{http://xpsw.domap.de/xpsw2511}StA2MB.Geburt"/>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2MB.Person", propOrder = {
    "namen",
    "geburtsangaben",
    "geschlecht"
})
@XmlSeeAlso({
    StA2MBPersonMitAnschrift.class
})
public class StA2MBPerson {

    @XmlElement(required = true)
    protected StA2MBPersonName namen;
    @XmlElement(required = true)
    protected StA2MBGeburt geburtsangaben;
    @XmlElement(required = true)
    protected CodeGeschlecht geschlecht;

    /**
     * Gets the value of the namen property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBPersonName }
     *     
     */
    public StA2MBPersonName getNamen() {
        return namen;
    }

    /**
     * Sets the value of the namen property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBPersonName }
     *     
     */
    public void setNamen(StA2MBPersonName value) {
        this.namen = value;
    }

    /**
     * Gets the value of the geburtsangaben property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBGeburt }
     *     
     */
    public StA2MBGeburt getGeburtsangaben() {
        return geburtsangaben;
    }

    /**
     * Sets the value of the geburtsangaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBGeburt }
     *     
     */
    public void setGeburtsangaben(StA2MBGeburt value) {
        this.geburtsangaben = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlecht(CodeGeschlecht value) {
        this.geschlecht = value;
    }

}
