//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2AB">
 *       <sequence>
 *         <element name="ansprechpartner" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="bemerkung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="aufenthaltsStatusElternteil" type="{http://xpsw.domap.de/xpsw2511}StA2AB.AufenthaltsrechtlicherStatusAB"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ansprechpartner",
    "bemerkung",
    "aufenthaltsStatusElternteil"
})
@XmlRootElement(name = "stA2AB.Geburt.071020")
public class StA2ABGeburt071020
    extends NachrichtStA2AB
{

    @XmlElement(required = true)
    protected String ansprechpartner;
    protected String bemerkung;
    @XmlElement(required = true)
    protected StA2ABAufenthaltsrechtlicherStatusAB aufenthaltsStatusElternteil;

    /**
     * Gets the value of the ansprechpartner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsprechpartner() {
        return ansprechpartner;
    }

    /**
     * Sets the value of the ansprechpartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsprechpartner(String value) {
        this.ansprechpartner = value;
    }

    /**
     * Gets the value of the bemerkung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBemerkung() {
        return bemerkung;
    }

    /**
     * Sets the value of the bemerkung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBemerkung(String value) {
        this.bemerkung = value;
    }

    /**
     * Gets the value of the aufenthaltsStatusElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link StA2ABAufenthaltsrechtlicherStatusAB }
     *     
     */
    public StA2ABAufenthaltsrechtlicherStatusAB getAufenthaltsStatusElternteil() {
        return aufenthaltsStatusElternteil;
    }

    /**
     * Sets the value of the aufenthaltsStatusElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2ABAufenthaltsrechtlicherStatusAB }
     *     
     */
    public void setAufenthaltsStatusElternteil(StA2ABAufenthaltsrechtlicherStatusAB value) {
        this.aufenthaltsStatusElternteil = value;
    }

}
