//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.vertama.xpersonenstand._2511.adapters.LocalDateAdapter;
import com.vertama.xpersonenstand._2511.model.de.xoev.schemata.basisnachricht.unqualified.g2g._1_1.KommunikationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Mit diesem Datentyp können die Angaben zur Leichenschau und dem durchführenden Arzt übermittelt werden .
 * 
 * <p>Java class for Todesbescheinigung.Leichenschau complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Todesbescheinigung.Leichenschau">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namenArzt" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="anschriftArzt" type="{http://xpsw.domap.de/xpsw2511}Anschrift.Inland"/>
 *         <element name="kontaktArzt" type="{http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1}KommunikationType" maxOccurs="unbounded"/>
 *         <element name="datum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *         <element name="uhrzeit" type="{http://xpsw.domap.de/xpsw2511}Uhrzeit"/>
 *         <element name="ort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Todesbescheinigung.Leichenschau", propOrder = {
    "namenArzt",
    "anschriftArzt",
    "kontaktArzt",
    "datum",
    "uhrzeit",
    "ort"
})
public class TodesbescheinigungLeichenschau {

    @XmlElement(required = true)
    protected PersonName namenArzt;
    @XmlElement(required = true)
    protected AnschriftInland anschriftArzt;
    @XmlElement(required = true)
    protected List<KommunikationType> kontaktArzt;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate datum;
    @XmlElement(required = true)
    protected Uhrzeit uhrzeit;
    @XmlElement(required = true)
    protected String ort;

    /**
     * Gets the value of the namenArzt property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNamenArzt() {
        return namenArzt;
    }

    /**
     * Sets the value of the namenArzt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNamenArzt(PersonName value) {
        this.namenArzt = value;
    }

    /**
     * Gets the value of the anschriftArzt property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftArzt() {
        return anschriftArzt;
    }

    /**
     * Sets the value of the anschriftArzt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftArzt(AnschriftInland value) {
        this.anschriftArzt = value;
    }

    /**
     * Gets the value of the kontaktArzt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the kontaktArzt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKontaktArzt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KommunikationType }
     * 
     * 
     * @return
     *     The value of the kontaktArzt property.
     */
    public List<KommunikationType> getKontaktArzt() {
        if (kontaktArzt == null) {
            kontaktArzt = new ArrayList<>();
        }
        return this.kontaktArzt;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(LocalDate value) {
        this.datum = value;
    }

    /**
     * Gets the value of the uhrzeit property.
     * 
     * @return
     *     possible object is
     *     {@link Uhrzeit }
     *     
     */
    public Uhrzeit getUhrzeit() {
        return uhrzeit;
    }

    /**
     * Sets the value of the uhrzeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uhrzeit }
     *     
     */
    public void setUhrzeit(Uhrzeit value) {
        this.uhrzeit = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

}
