<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xpersonenstand="http://xpsw.domap.de/xpsw2505"
           xmlns:din91379="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"
           xmlns:xida="http://www.osci.de/xinneres/datum/2"
           targetNamespace="http://xpsw.domap.de/xpsw2505"
           version="25.05"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
   <xs:annotation>
      <xs:appinfo>
         <standard>
            <nameLang>XPersonenstand</nameLang>
            <nameKurz>XPersonenstand</nameKurz>
            <nameTechnisch>xinneres.xpersonenstand</nameTechnisch>
            <kennung>urn:xoev-de:kosit:standard:xinneres.xpersonenstand</kennung>
            <beschreibung>Projektziel ist die elektronische Kommunikation der Standesämter untereinander und mit anderen Behörden und Institutionen, welche Daten von den Standesämtern erhalten oder an Standesämter senden. Der Nutzen des Projektes besteht in der Kostenreduktion und einer Verbesserung der Qualität der Personenstandsdaten sowie einer Verbesserung der Interoperabilität in der Kommunikation der Standesämter untereinander und zu weiteren Kommunikationspartnern.
</beschreibung>
         </standard>
         <versionStandard>
            <version>25.05</version>
            <versionXOEVProfil>2.1.0_p3</versionXOEVProfil>
            <versionXOEVHandbuch>2.4</versionXOEVHandbuch>
            <versionXGenerator>3.0.1</versionXGenerator>
            <versionModellierungswerkzeug>19.0 SP4</versionModellierungswerkzeug>
            <nameModellierungswerkzeug>MagicDraw</nameModellierungswerkzeug>
         </versionStandard>
      </xs:appinfo>
   </xs:annotation>
   <xs:include schemaLocation="xpersonenstand-baukasten.xsd"/>
   <xs:import schemaLocation="http://www.osci.de/xinneres/datum/2/xinneres-datum.xsd"
              namespace="http://www.osci.de/xinneres/datum/2"/>
   <xs:import schemaLocation="https://xoev.de/schemata/din/91379/2022-08/din-norm-91379-datatypes.xsd"
              namespace="urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08"/>
   <xs:complexType name="StA2EGS.Abruf.Allgemeines">
      <xs:annotation>
         <xs:appinfo>
            <title>Allgemeine Angaben zum Datenabruf durch Elterngeldstellen</title>
         </xs:appinfo>
         <xs:documentation>In diesem Datentypen werden Angaben abgebildet, die sowohl in der Anfrage- sowie der Antwortnachricht übermittelt werden. Die Angaben in der Antwortnachrichten müssen dabei immer den entsprechenden Angaben in der Anfragenachricht entsprechen.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="zuordnung" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Zur besseren Zuordenbarkeit der Antwortnachricht zur Anfragenachricht kann hier eine Zeichenkette übermittelt werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="abfragendePerson" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier wird zum Zwecke der Protokollierung die abfragende Person übermittelt.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="StA2EGS.Abruf.Suchdaten">
      <xs:annotation>
         <xs:appinfo>
            <title>Suchdaten im Geburtenregister</title>
         </xs:appinfo>
         <xs:documentation>Dieser Datentyp wird verwendet, um den abgerufenen Geburtseintrag über Inhaltsdaten zu identifizieren.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="namen" type="xpersonenstand:PersonName">
            <xs:annotation>
               <xs:documentation>Die Namen des Kindes sind zur Suche unbedingt erforderlich, deswegen ist das Feld verpflichtend. Das Feld geburtsname darf bei Kindern nicht befüllt werden, da der Familienname erst nach der ersten Änderung des Familiennamens zum Geburtsnamen wird.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtstag" type="xida:Tagesdatum">
            <xs:annotation>
               <xs:documentation>Der Geburtstag ist für die Suche unbedingt erforderlich und ist deswegen ein Pflichtfeld. Um die Wahrscheinlichkeit von Mehrfachtreffern zu verringern muss der Tag exakt angegeben werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="geburtsort" minOccurs="0" type="din91379:datatypeC">
            <xs:annotation>
               <xs:documentation>Hier kann der Geburtsort übermittelt werden.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="stA2EGS.Geburt.131011">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt (psw)</autor>
            <leser>Elterngeldstelle</leser>
            <rechtsgrundlage>§ 57 (1) Nr. 8 PStV</rechtsgrundlage>
            <title>Mitteilung über die Beurkundung einer Geburt an die Elterngeldstelle</title>
         </xs:appinfo>
         <xs:documentation>Diese Mitteilung wird vom stamt an die zuständige Elterngeldstelle gesendet, um dieser eine im Geburtenregister beurkundete Geburt mitzuteilen.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="geburtseintragKind" type="xpersonenstand:Quelleintrag">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Angaben des Registereintrags übermittelt, in dem die Geburt beurkundet wurde.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtsort" type="xpersonenstand:Ereignisort">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben zum Geburtsort übermittelt. Es ist nur der Ort zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtstag" type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Hier ist der Tag der Geburt zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenKind" type="xpersonenstand:PersonName.Veraenderung">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Namen des Kindes mitgeteilt. Der Vorname des Kindes wird im Feld "vorname" gespeichert, der Geburtsname des Kindes im Feld "familienname". Das Feld "geburtsname" darf nicht befüllt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenElternteil1" type="xpersonenstand:PersonName">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Namen des ersten Elternteils (Mutter) mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenElternteil2"
                              minOccurs="0"
                              type="xpersonenstand:PersonName">
                     <xs:annotation>
                        <xs:documentation>Falls beurkundet, müssen hier die Namen des zweiten Elternteils (Vater) übermittelt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="auftragsnummer" minOccurs="0" type="din91379:datatypeC">
                     <xs:annotation>
                        <xs:documentation>Hier ist die Auftragsnummer zu übermitteln, sofern diese dem Standesamt bekannt ist, z. B. durch die nachricht.ref.081021. Das Portal muss die Zustimmung der Eltern zur Übermittlung der Auftragsnummer einholen.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="stA2EGS.Geburt.138010">
      <xs:annotation>
         <xs:appinfo>
            <autor>Elterngeldstelle (egs)</autor>
            <leser>Standesamt (psw)</leser>
            <rechtsgrundlage>§ 68 (3) PStG i.V.m. § 25 BEEG</rechtsgrundlage>
            <title>Anfragenachricht zum Datenabruf von einer Elterngeldstelle</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht ruft eine Elterngeldstelle beim Geburtenregister Daten zur Bearbeitung eines Elterngeldantrags ab.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="allgemeineAngaben"
                              type="xpersonenstand:StA2EGS.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben übermittelt, die sowohl in der Anfrage- sowie der Antwortnachricht übermittelt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="suchdaten" type="xpersonenstand:StA2EGS.Abruf.Suchdaten">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Suchdaten übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="stA2EGS.Geburt.138011">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt (psw)</autor>
            <leser>Elterngeldstelle (egs)</leser>
            <rechtsgrundlage>§ 68 (3) PStG i.V.m. § 25 BEEG</rechtsgrundlage>
            <title>Antwortnachricht mit Urkundsdaten zum Datenabruf von einer Elterngeldstelle</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht beantwortet ein Standesamt die Datenanfrage einer Elterngeldstelle mit Daten aus dem Geburtseintrag.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="allgemeineAngaben"
                              type="xpersonenstand:StA2EGS.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben übermittelt, die sowohl in der Anfrage- sowie der Antwortnachricht übermittelt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtsort" type="xpersonenstand:Ereignisort">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben zum Geburtsort übermittelt. Es ist nur der Ort zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="geburtstag" type="xida:Tagesdatum">
                     <xs:annotation>
                        <xs:documentation>Hier ist der Tag der Geburt zu übermitteln.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenElternteil1" type="xpersonenstand:PersonName">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Namen des ersten Elternteils (Mutter) mitgeteilt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenElternteil2"
                              minOccurs="0"
                              type="xpersonenstand:PersonName">
                     <xs:annotation>
                        <xs:documentation>Falls beurkundet, müssen hier die Namen des zweiten Elternteils (Vater) übermittelt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="namenKind" type="xpersonenstand:PersonName.Veraenderung">
                     <xs:annotation>
                        <xs:documentation>Hier werden die Namen des Kindes mitgeteilt. Der Vorname des Kindes wird im Feld "vorname" gespeichert, der Geburtsname des Kindes im Feld "familienname". Das Feld "geburtsname" darf nicht befüllt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="stA2EGS.Geburt.138050">
      <xs:annotation>
         <xs:appinfo>
            <autor>Standesamt (psw)</autor>
            <leser>Elterngeldstelle (egs)</leser>
            <rechtsgrundlage>§ 68 (3) PStG i.V.m. § 25 BEEG</rechtsgrundlage>
            <title>Fehlernachricht zum Datenabruf von einer Elterngeldstelle</title>
         </xs:appinfo>
         <xs:documentation>Mit dieser Nachricht beantwortet ein Standesamt die Datenanfrage einer Elterngeldstelle mit dem Grund, warum nicht mit Urkundsdaten geantwortet werden kann.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:complexContent>
            <xs:extension base="xpersonenstand:Nachricht.G2GXP">
               <xs:sequence>
                  <xs:element name="allgemeineAngaben"
                              type="xpersonenstand:StA2EGS.Abruf.Allgemeines">
                     <xs:annotation>
                        <xs:documentation>Hier werden Angaben übermittelt, die sowohl in der Anfrage- sowie der Antwortnachricht übermittelt werden.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
                  <xs:element name="fehlercode" type="xpersonenstand:Code.FehlerartEGS.Code">
                     <xs:annotation>
                        <xs:documentation>Hier wird der Art des Fehlers übermittelt.</xs:documentation>
                     </xs:annotation>
                  </xs:element>
               </xs:sequence>
            </xs:extension>
         </xs:complexContent>
      </xs:complexType>
   </xs:element>
</xs:schema>
