//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.xoev.schemata.basisnachricht.unqualified.g2g._1_1;

import de.osci.xinneres.basisnachricht._7.NachrichtG2GGrundstruktur;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Basistyp für alle Nachrichten zwischen Behörden und anderen öffentlichen Stellen (government-to-government).
 * 
 * <p>Java class for Nachricht.G2GType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Nachricht.G2GType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="nachrichtenkopf.g2g" type="{http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1}Nachrichtenkopf.G2GType"/>
 *       </sequence>
 *       <attribute name="produkt" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *       <attribute name="produkthersteller" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *       <attribute name="produktversion" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *       <attribute name="standard" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *       <attribute name="test" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *       <attribute name="version" use="required" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachricht.G2GType", propOrder = {
    "nachrichtenkopfG2G"
})
@XmlSeeAlso({
    NachrichtG2GGrundstruktur.class
})
public class NachrichtG2GType {

    @XmlElement(name = "nachrichtenkopf.g2g", required = true)
    protected NachrichtenkopfG2GType nachrichtenkopfG2G;
    @XmlAttribute(name = "produkt", required = true)
    protected String produkt;
    @XmlAttribute(name = "produkthersteller", required = true)
    protected String produkthersteller;
    @XmlAttribute(name = "produktversion")
    protected String produktversion;
    @XmlAttribute(name = "standard", required = true)
    protected String standard;
    @XmlAttribute(name = "test")
    protected String test;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the nachrichtenkopfG2G property.
     * 
     * @return
     *     possible object is
     *     {@link NachrichtenkopfG2GType }
     *     
     */
    public NachrichtenkopfG2GType getNachrichtenkopfG2G() {
        return nachrichtenkopfG2G;
    }

    /**
     * Sets the value of the nachrichtenkopfG2G property.
     * 
     * @param value
     *     allowed object is
     *     {@link NachrichtenkopfG2GType }
     *     
     */
    public void setNachrichtenkopfG2G(NachrichtenkopfG2GType value) {
        this.nachrichtenkopfG2G = value;
    }

    /**
     * Gets the value of the produkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdukt() {
        return produkt;
    }

    /**
     * Sets the value of the produkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdukt(String value) {
        this.produkt = value;
    }

    /**
     * Gets the value of the produkthersteller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdukthersteller() {
        return produkthersteller;
    }

    /**
     * Sets the value of the produkthersteller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdukthersteller(String value) {
        this.produkthersteller = value;
    }

    /**
     * Gets the value of the produktversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduktversion() {
        return produktversion;
    }

    /**
     * Sets the value of the produktversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduktversion(String value) {
        this.produktversion = value;
    }

    /**
     * Gets the value of the standard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandard() {
        return standard;
    }

    /**
     * Sets the value of the standard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandard(String value) {
        this.standard = value;
    }

    /**
     * Gets the value of the test property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTest() {
        return test;
    }

    /**
     * Sets the value of the test property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTest(String value) {
        this.test = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
