//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2411;

import de.osci.xinneres.allgemeinername._4.AllgemeinerName;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp dient der Darstellung von Vor- und Familiennamen in xpers. Er ist eine Erweiterung des Datentyps AllgemeinerName aus XInneres. Bei Namen nach ausländischem Recht kann in dem Kindelement namensart eine Namensart nach ausländischem Recht benannt und damit der name näher charakterisiert werden.
 * 
 * <p>Java class for AllgemeinerName.Personenstandswesen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="AllgemeinerName.Personenstandswesen">
 *   <complexContent>
 *     <extension base="{http://www.osci.de/xinneres/allgemeinername/4}AllgemeinerName">
 *       <sequence>
 *         <element name="namensart" type="{http://xpsw.domap.de/xpsw2411}Code.Namensart" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllgemeinerName.Personenstandswesen", propOrder = {
    "namensart"
})
public class AllgemeinerNamePersonenstandswesen
    extends AllgemeinerName
{

    protected CodeNamensart namensart;

    /**
     * Gets the value of the namensart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeNamensart }
     *     
     */
    public CodeNamensart getNamensart() {
        return namensart;
    }

    /**
     * Sets the value of the namensart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeNamensart }
     *     
     */
    public void setNamensart(CodeNamensart value) {
        this.namensart = value;
    }

}
