//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2411;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp fasst die Angaben zum Namen einer Behörde zusammen. Dieser Datentyp kann verwendet werden, sofern nicht sichergestellt ist, dass Funktion und Name der Behörde in jedem Fall vollständig vorliegen.
 * 
 * <p>Java class for Behoerdenbezeichnung.Flexibel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Behoerdenbezeichnung.Flexibel">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="behoerdeFunktion" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="behoerdeName" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Behoerdenbezeichnung.Flexibel", propOrder = {
    "behoerdeFunktion",
    "behoerdeName"
})
public class BehoerdenbezeichnungFlexibel {

    protected String behoerdeFunktion;
    protected String behoerdeName;

    /**
     * Gets the value of the behoerdeFunktion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehoerdeFunktion() {
        return behoerdeFunktion;
    }

    /**
     * Sets the value of the behoerdeFunktion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehoerdeFunktion(String value) {
        this.behoerdeFunktion = value;
    }

    /**
     * Gets the value of the behoerdeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehoerdeName() {
        return behoerdeName;
    }

    /**
     * Sets the value of the behoerdeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehoerdeName(String value) {
        this.behoerdeName = value;
    }

}
