//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2411;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Liste von Codes zur Übermittlung der Identifizierungsart.
 * 
 * <p>Java class for Code.Identifizierungsart complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Code.Identifizierungsart">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="code" type="{http://xpsw.domap.de/xpsw2411}Code.Identifizierungsart.Code"/>
 *         <element name="nichtGelisteterWert" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Code.Identifizierungsart", propOrder = {
    "code",
    "nichtGelisteterWert"
})
public class CodeIdentifizierungsart {

    protected CodeIdentifizierungsartCode code;
    protected String nichtGelisteterWert;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeIdentifizierungsartCode }
     *     
     */
    public CodeIdentifizierungsartCode getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeIdentifizierungsartCode }
     *     
     */
    public void setCode(CodeIdentifizierungsartCode value) {
        this.code = value;
    }

    /**
     * Gets the value of the nichtGelisteterWert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNichtGelisteterWert() {
        return nichtGelisteterWert;
    }

    /**
     * Sets the value of the nichtGelisteterWert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNichtGelisteterWert(String value) {
        this.nichtGelisteterWert = value;
    }

}
