//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Anz2StA.Geburt.Mehrling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Anz2StA.Geburt.Mehrling">
 *   <complexContent>
 *     <restriction base="{http://xpsw.domap.de/xpsw2611}Mehrlingsgeburt">
 *       <sequence>
 *         <element name="anzahlKnaben" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         <element name="anzahlMaedchen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         <element name="anzahlUnbestimmt" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anz2StA.Geburt.Mehrling")
public class Anz2StAGeburtMehrling
    extends Mehrlingsgeburt
{


}
