//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.util.ArrayList;
import java.util.List;
import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp dient zur Ableitung von Nachrichten, mit denen ein Datenabruf aus einem Geburtseintrag beantwortet werden. Der Datenumfang entspricht dem der Geburtsurkunde, wobei zusätzliche Angaben aus der Abrufnachricht zur Zuordnung der Abrufnachricht zur Antwortnachricht übermittelt werden.
 * 
 * <p>Java class for Datenabruf2StA.Template.AntwortGeburt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Datenabruf2StA.Template.AntwortGeburt">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="zuordnung" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Zuordnung"/>
 *         <element name="abrufzweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="identifikationGeburtseintrag" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Eintragsidentifikation.Geburt"/>
 *         <element name="registernummer" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Registernummer"/>
 *         <element name="geburt" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Geburt"/>
 *         <element name="kind">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="kindNamen" type="{http://xpsw.domap.de/xpsw2611}PersonName"/>
 *                   <element name="kindGeschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *                   <element name="namensfuehrungNichtNachgewiesen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="eltern" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Elternteil.Rechtlich" maxOccurs="2"/>
 *         <element name="elternLeiblich" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Elternteil" maxOccurs="2" minOccurs="0"/>
 *         <element name="eheDesKindes" type="{http://xpsw.domap.de/xpsw2611}Datenabruf2StA.Hinweis.Ehe" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datenabruf2StA.Template.AntwortGeburt", propOrder = {
    "zuordnung",
    "abrufzweck",
    "identifikationGeburtseintrag",
    "registernummer",
    "geburt",
    "kind",
    "eltern",
    "elternLeiblich",
    "eheDesKindes"
})
@XmlSeeAlso({
    Datenabruf2StAAntwortGeburtAsynchron018012 .class,
    Datenabruf2StAAntwortGeburtSynchron018011 .class
})
public abstract class Datenabruf2StATemplateAntwortGeburt
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected Datenabruf2StAZuordnung zuordnung;
    @XmlElement(required = true)
    protected String abrufzweck;
    @XmlElement(required = true)
    protected Datenabruf2StAEintragsidentifikationGeburt identifikationGeburtseintrag;
    @XmlElement(required = true)
    protected Datenabruf2StARegisternummer registernummer;
    @XmlElement(required = true)
    protected Datenabruf2StAGeburt geburt;
    @XmlElement(required = true)
    protected Datenabruf2StATemplateAntwortGeburt.Kind kind;
    @XmlElement(required = true)
    protected List<Datenabruf2StAElternteilRechtlich> eltern;
    protected List<Datenabruf2StAElternteil> elternLeiblich;
    protected Datenabruf2StAHinweisEhe eheDesKindes;

    /**
     * Gets the value of the zuordnung property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAZuordnung }
     *     
     */
    public Datenabruf2StAZuordnung getZuordnung() {
        return zuordnung;
    }

    /**
     * Sets the value of the zuordnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAZuordnung }
     *     
     */
    public void setZuordnung(Datenabruf2StAZuordnung value) {
        this.zuordnung = value;
    }

    /**
     * Gets the value of the abrufzweck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbrufzweck() {
        return abrufzweck;
    }

    /**
     * Sets the value of the abrufzweck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbrufzweck(String value) {
        this.abrufzweck = value;
    }

    /**
     * Gets the value of the identifikationGeburtseintrag property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAEintragsidentifikationGeburt }
     *     
     */
    public Datenabruf2StAEintragsidentifikationGeburt getIdentifikationGeburtseintrag() {
        return identifikationGeburtseintrag;
    }

    /**
     * Sets the value of the identifikationGeburtseintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAEintragsidentifikationGeburt }
     *     
     */
    public void setIdentifikationGeburtseintrag(Datenabruf2StAEintragsidentifikationGeburt value) {
        this.identifikationGeburtseintrag = value;
    }

    /**
     * Gets the value of the registernummer property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StARegisternummer }
     *     
     */
    public Datenabruf2StARegisternummer getRegisternummer() {
        return registernummer;
    }

    /**
     * Sets the value of the registernummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StARegisternummer }
     *     
     */
    public void setRegisternummer(Datenabruf2StARegisternummer value) {
        this.registernummer = value;
    }

    /**
     * Gets the value of the geburt property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAGeburt }
     *     
     */
    public Datenabruf2StAGeburt getGeburt() {
        return geburt;
    }

    /**
     * Sets the value of the geburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAGeburt }
     *     
     */
    public void setGeburt(Datenabruf2StAGeburt value) {
        this.geburt = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StATemplateAntwortGeburt.Kind }
     *     
     */
    public Datenabruf2StATemplateAntwortGeburt.Kind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StATemplateAntwortGeburt.Kind }
     *     
     */
    public void setKind(Datenabruf2StATemplateAntwortGeburt.Kind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the eltern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the eltern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEltern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datenabruf2StAElternteilRechtlich }
     * 
     * 
     * @return
     *     The value of the eltern property.
     */
    public List<Datenabruf2StAElternteilRechtlich> getEltern() {
        if (eltern == null) {
            eltern = new ArrayList<>();
        }
        return this.eltern;
    }

    /**
     * Gets the value of the elternLeiblich property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the elternLeiblich property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElternLeiblich().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datenabruf2StAElternteil }
     * 
     * 
     * @return
     *     The value of the elternLeiblich property.
     */
    public List<Datenabruf2StAElternteil> getElternLeiblich() {
        if (elternLeiblich == null) {
            elternLeiblich = new ArrayList<>();
        }
        return this.elternLeiblich;
    }

    /**
     * Gets the value of the eheDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAHinweisEhe }
     *     
     */
    public Datenabruf2StAHinweisEhe getEheDesKindes() {
        return eheDesKindes;
    }

    /**
     * Sets the value of the eheDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAHinweisEhe }
     *     
     */
    public void setEheDesKindes(Datenabruf2StAHinweisEhe value) {
        this.eheDesKindes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="kindNamen" type="{http://xpsw.domap.de/xpsw2611}PersonName"/>
     *         <element name="kindGeschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
     *         <element name="namensfuehrungNichtNachgewiesen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "kindNamen",
        "kindGeschlecht",
        "namensfuehrungNichtNachgewiesen"
    })
    public static class Kind {

        @XmlElement(required = true)
        protected PersonName kindNamen;
        @XmlElement(required = true)
        protected CodeGeschlecht kindGeschlecht;
        protected Boolean namensfuehrungNichtNachgewiesen;

        /**
         * Gets the value of the kindNamen property.
         * 
         * @return
         *     possible object is
         *     {@link PersonName }
         *     
         */
        public PersonName getKindNamen() {
            return kindNamen;
        }

        /**
         * Sets the value of the kindNamen property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonName }
         *     
         */
        public void setKindNamen(PersonName value) {
            this.kindNamen = value;
        }

        /**
         * Gets the value of the kindGeschlecht property.
         * 
         * @return
         *     possible object is
         *     {@link CodeGeschlecht }
         *     
         */
        public CodeGeschlecht getKindGeschlecht() {
            return kindGeschlecht;
        }

        /**
         * Sets the value of the kindGeschlecht property.
         * 
         * @param value
         *     allowed object is
         *     {@link CodeGeschlecht }
         *     
         */
        public void setKindGeschlecht(CodeGeschlecht value) {
            this.kindGeschlecht = value;
        }

        /**
         * Gets the value of the namensfuehrungNichtNachgewiesen property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNamensfuehrungNichtNachgewiesen() {
            return namensfuehrungNichtNachgewiesen;
        }

        /**
         * Sets the value of the namensfuehrungNichtNachgewiesen property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNamensfuehrungNichtNachgewiesen(Boolean value) {
            this.namensfuehrungNichtNachgewiesen = value;
        }

    }

}
