//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese abstrakte Nachricht dient als Vorlage für alle Nachrichten an Meldebehörden. Bei jeder Mitteilung von einem Standesamt an eine Meldebehörde werden übermittelt: Nachrichtenkopf mit Angaben zum Absender und Empfänger Angaben zum Erstellungszeitpunkt der Nachricht Angaben über den Grund der Nachricht Identifikationsdaten, um die betroffene Person bei der empfangenden Meldebehörde zu identifizieren.
 * 
 * <p>Java class for Nachricht.StA2MB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Nachricht.StA2MB">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="identifikationPerson" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Person.MitAnschrift"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachricht.StA2MB", propOrder = {
    "identifikationPerson"
})
@XmlSeeAlso({
    StA2MBSterbefall035010 .class,
    StA2MBSterbefall034100 .class,
    StA2MBLP033100 .class,
    StA2MBLP033030 .class,
    StA2MBLP033020 .class,
    StA2MBLP033010 .class,
    StA2MBEhe032100 .class,
    StA2MBEhe032030 .class,
    StA2MBEhe032020 .class,
    StA2MBEhe032010 .class,
    StA2MBGeburt031100 .class,
    StA2MBGeburt031050 .class,
    StA2MBGeburt031041 .class,
    StA2MBGeburt031040 .class,
    StA2MBGeburt031030 .class,
    StA2MBGeburt031020 .class,
    StA2MBGeburt031012 .class,
    StA2MBGeburt031011 .class,
    StA2MBTemplateGeburt.class
})
public abstract class NachrichtStA2MB
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected StA2MBPersonMitAnschrift identifikationPerson;

    /**
     * Gets the value of the identifikationPerson property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public StA2MBPersonMitAnschrift getIdentifikationPerson() {
        return identifikationPerson;
    }

    /**
     * Sets the value of the identifikationPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public void setIdentifikationPerson(StA2MBPersonMitAnschrift value) {
        this.identifikationPerson = value;
    }

}
