//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.G2G">
 *       <sequence>
 *         <element name="antragsteller" type="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.Antragsteller.NatuerlichePerson.Bescheinigung"/>
 *         <element name="modalitaeten" type="{http://xpsw.domap.de/xpsw2611}Bescheinigungsanforderung.Modalitaeten" minOccurs="0"/>
 *         <element name="verwendungszweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="kind">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.BeurkundetesEreignis">
 *                 <sequence>
 *                   <element name="geburtsort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="artDerBescheinigung" type="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.ArtDerBescheinigung.G"/>
 *         <element name="anhang" type="{http://xpsw.domap.de/xpsw2611}AnhangInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "antragsteller",
    "modalitaeten",
    "verwendungszweck",
    "kind",
    "artDerBescheinigung",
    "anhang"
})
@XmlRootElement(name = "portal2StA.Geburt.081031")
public class Portal2StAGeburt081031
    extends NachrichtG2G
{

    @XmlElement(required = true)
    protected UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung antragsteller;
    protected BescheinigungsanforderungModalitaeten modalitaeten;
    protected String verwendungszweck;
    @XmlElement(required = true)
    protected Portal2StAGeburt081031 .Kind kind;
    @XmlElement(required = true)
    protected UrkundenanforderungArtDerBescheinigungG artDerBescheinigung;
    protected List<AnhangInformation> anhang;

    /**
     * Gets the value of the antragsteller property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung }
     *     
     */
    public UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung getAntragsteller() {
        return antragsteller;
    }

    /**
     * Sets the value of the antragsteller property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung }
     *     
     */
    public void setAntragsteller(UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung value) {
        this.antragsteller = value;
    }

    /**
     * Gets the value of the modalitaeten property.
     * 
     * @return
     *     possible object is
     *     {@link BescheinigungsanforderungModalitaeten }
     *     
     */
    public BescheinigungsanforderungModalitaeten getModalitaeten() {
        return modalitaeten;
    }

    /**
     * Sets the value of the modalitaeten property.
     * 
     * @param value
     *     allowed object is
     *     {@link BescheinigungsanforderungModalitaeten }
     *     
     */
    public void setModalitaeten(BescheinigungsanforderungModalitaeten value) {
        this.modalitaeten = value;
    }

    /**
     * Gets the value of the verwendungszweck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerwendungszweck() {
        return verwendungszweck;
    }

    /**
     * Sets the value of the verwendungszweck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerwendungszweck(String value) {
        this.verwendungszweck = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StAGeburt081031 .Kind }
     *     
     */
    public Portal2StAGeburt081031 .Kind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StAGeburt081031 .Kind }
     *     
     */
    public void setKind(Portal2StAGeburt081031 .Kind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the artDerBescheinigung property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungArtDerBescheinigungG }
     *     
     */
    public UrkundenanforderungArtDerBescheinigungG getArtDerBescheinigung() {
        return artDerBescheinigung;
    }

    /**
     * Sets the value of the artDerBescheinigung property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungArtDerBescheinigungG }
     *     
     */
    public void setArtDerBescheinigung(UrkundenanforderungArtDerBescheinigungG value) {
        this.artDerBescheinigung = value;
    }

    /**
     * Gets the value of the anhang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anhang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnhang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnhangInformation }
     * 
     * 
     * @return
     *     The value of the anhang property.
     */
    public List<AnhangInformation> getAnhang() {
        if (anhang == null) {
            anhang = new ArrayList<>();
        }
        return this.anhang;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.BeurkundetesEreignis">
     *       <sequence>
     *         <element name="geburtsort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geburtsort"
    })
    public static class Kind
        extends UrkundenanforderungBeurkundetesEreignis
    {

        @XmlElement(required = true)
        protected String geburtsort;

        /**
         * Gets the value of the geburtsort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeburtsort() {
            return geburtsort;
        }

        /**
         * Sets the value of the geburtsort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeburtsort(String value) {
            this.geburtsort = value;
        }

    }

}
