//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.vertama.xpersonenstand._2611.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="eltern" type="{http://xpsw.domap.de/xpsw2611}Erk2StA.Beteiligter.Geburt" maxOccurs="2"/>
 *         <element name="neuerEhegatte" type="{http://xpsw.domap.de/xpsw2611}Erk2StA.NeuerEhegatte" minOccurs="0"/>
 *         <element name="kind" type="{http://xpsw.domap.de/xpsw2611}Erk2StA.Kind"/>
 *         <element name="gemeinsameSorgeDatum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum" minOccurs="0"/>
 *         <element name="ehenamen" type="{http://xpsw.domap.de/xpsw2611}Erk2StA.Ehename" minOccurs="0"/>
 *         <element name="erklaerung" type="{http://xpsw.domap.de/xpsw2611}Erk2StA.Erklaerung.Geburt"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eltern",
    "neuerEhegatte",
    "kind",
    "gemeinsameSorgeDatum",
    "ehenamen",
    "erklaerung"
})
@XmlRootElement(name = "portal2StA.Geburt.081060")
public class Portal2StAGeburt081060
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected List<Erk2StABeteiligterGeburt> eltern;
    protected Erk2StANeuerEhegatte neuerEhegatte;
    @XmlElement(required = true)
    protected Erk2StAKind kind;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate gemeinsameSorgeDatum;
    protected Erk2StAEhename ehenamen;
    @XmlElement(required = true)
    protected Erk2StAErklaerungGeburt erklaerung;

    /**
     * Gets the value of the eltern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the eltern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEltern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Erk2StABeteiligterGeburt }
     * 
     * 
     * @return
     *     The value of the eltern property.
     */
    public List<Erk2StABeteiligterGeburt> getEltern() {
        if (eltern == null) {
            eltern = new ArrayList<>();
        }
        return this.eltern;
    }

    /**
     * Gets the value of the neuerEhegatte property.
     * 
     * @return
     *     possible object is
     *     {@link Erk2StANeuerEhegatte }
     *     
     */
    public Erk2StANeuerEhegatte getNeuerEhegatte() {
        return neuerEhegatte;
    }

    /**
     * Sets the value of the neuerEhegatte property.
     * 
     * @param value
     *     allowed object is
     *     {@link Erk2StANeuerEhegatte }
     *     
     */
    public void setNeuerEhegatte(Erk2StANeuerEhegatte value) {
        this.neuerEhegatte = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link Erk2StAKind }
     *     
     */
    public Erk2StAKind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Erk2StAKind }
     *     
     */
    public void setKind(Erk2StAKind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the gemeinsameSorgeDatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getGemeinsameSorgeDatum() {
        return gemeinsameSorgeDatum;
    }

    /**
     * Sets the value of the gemeinsameSorgeDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGemeinsameSorgeDatum(LocalDate value) {
        this.gemeinsameSorgeDatum = value;
    }

    /**
     * Gets the value of the ehenamen property.
     * 
     * @return
     *     possible object is
     *     {@link Erk2StAEhename }
     *     
     */
    public Erk2StAEhename getEhenamen() {
        return ehenamen;
    }

    /**
     * Sets the value of the ehenamen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Erk2StAEhename }
     *     
     */
    public void setEhenamen(Erk2StAEhename value) {
        this.ehenamen = value;
    }

    /**
     * Gets the value of the erklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link Erk2StAErklaerungGeburt }
     *     
     */
    public Erk2StAErklaerungGeburt getErklaerung() {
        return erklaerung;
    }

    /**
     * Sets the value of the erklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Erk2StAErklaerungGeburt }
     *     
     */
    public void setErklaerung(Erk2StAErklaerungGeburt value) {
        this.erklaerung = value;
    }

}
