//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp dient dazu, Angaben zu Eheschließenden zu übermitteln. Diese Angaben werden gebraucht, um eine erste Einschätzung zur Ehefähigkeit sowie den notwendigen Nachweisen zu ermitteln.
 * 
 * <p>Java class for Portal2StA.AngabenEheschliessende.Nachbeurkundung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Portal2StA.AngabenEheschliessende.Nachbeurkundung">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Anm2StA.AngabenEheschliessende">
 *       <sequence>
 *         <element name="geburtsstandesamt" type="{http://xpsw.domap.de/xpsw2611}Anm2StA.Registereintrag" minOccurs="0"/>
 *         <element name="familienstand" type="{http://xpsw.domap.de/xpsw2611}Code.FamilienstandPersonenstandswesen" minOccurs="0"/>
 *         <element name="staatsangehoerigkeitBeiEheschliessung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="beiEheschliessungAnwesend" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="angabenRichtigVollstaendig" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Portal2StA.AngabenEheschliessende.Nachbeurkundung", propOrder = {
    "geburtsstandesamt",
    "familienstand",
    "staatsangehoerigkeitBeiEheschliessung",
    "beiEheschliessungAnwesend",
    "angabenRichtigVollstaendig"
})
public class Portal2StAAngabenEheschliessendeNachbeurkundung
    extends Anm2StAAngabenEheschliessende
{

    protected Anm2StARegistereintrag geburtsstandesamt;
    protected CodeFamilienstandPersonenstandswesen familienstand;
    protected List<String> staatsangehoerigkeitBeiEheschliessung;
    protected Boolean beiEheschliessungAnwesend;
    protected Boolean angabenRichtigVollstaendig;

    /**
     * Gets the value of the geburtsstandesamt property.
     * 
     * @return
     *     possible object is
     *     {@link Anm2StARegistereintrag }
     *     
     */
    public Anm2StARegistereintrag getGeburtsstandesamt() {
        return geburtsstandesamt;
    }

    /**
     * Sets the value of the geburtsstandesamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anm2StARegistereintrag }
     *     
     */
    public void setGeburtsstandesamt(Anm2StARegistereintrag value) {
        this.geburtsstandesamt = value;
    }

    /**
     * Gets the value of the familienstand property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFamilienstandPersonenstandswesen }
     *     
     */
    public CodeFamilienstandPersonenstandswesen getFamilienstand() {
        return familienstand;
    }

    /**
     * Sets the value of the familienstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFamilienstandPersonenstandswesen }
     *     
     */
    public void setFamilienstand(CodeFamilienstandPersonenstandswesen value) {
        this.familienstand = value;
    }

    /**
     * Gets the value of the staatsangehoerigkeitBeiEheschliessung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the staatsangehoerigkeitBeiEheschliessung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaatsangehoerigkeitBeiEheschliessung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the staatsangehoerigkeitBeiEheschliessung property.
     */
    public List<String> getStaatsangehoerigkeitBeiEheschliessung() {
        if (staatsangehoerigkeitBeiEheschliessung == null) {
            staatsangehoerigkeitBeiEheschliessung = new ArrayList<>();
        }
        return this.staatsangehoerigkeitBeiEheschliessung;
    }

    /**
     * Gets the value of the beiEheschliessungAnwesend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBeiEheschliessungAnwesend() {
        return beiEheschliessungAnwesend;
    }

    /**
     * Sets the value of the beiEheschliessungAnwesend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBeiEheschliessungAnwesend(Boolean value) {
        this.beiEheschliessungAnwesend = value;
    }

    /**
     * Gets the value of the angabenRichtigVollstaendig property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAngabenRichtigVollstaendig() {
        return angabenRichtigVollstaendig;
    }

    /**
     * Sets the value of the angabenRichtigVollstaendig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAngabenRichtigVollstaendig(Boolean value) {
        this.angabenRichtigVollstaendig = value;
    }

}
