//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp enthält alle Informationen zum Ehegatten oder Lebenspartner der verstorbenen Person, die bei einer Mitteilung über eine Sterbefallbeurkundung benötigt werden.
 * 
 * <p>Java class for StA2ZTR.EheOderLebenspartner.Beurkundung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2ZTR.EheOderLebenspartner.Beurkundung">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}StA2ZTR.EheOderLebenspartner.Basis">
 *       <sequence>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht" minOccurs="0"/>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2611}Anschrift.Inland" minOccurs="0"/>
 *         <element name="sterbefall" type="{http://xpsw.domap.de/xpsw2611}BeurkundeteDaten.Zeitraum.Registereintrag.Flexibel" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2ZTR.EheOderLebenspartner.Beurkundung", propOrder = {
    "geschlecht",
    "anschrift",
    "sterbefall"
})
public class StA2ZTREheOderLebenspartnerBeurkundung
    extends StA2ZTREheOderLebenspartnerBasis
{

    protected CodeGeschlecht geschlecht;
    protected AnschriftInland anschrift;
    protected BeurkundeteDatenZeitraumRegistereintragFlexibel sterbefall;

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlecht(CodeGeschlecht value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschrift(AnschriftInland value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the sterbefall property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
     *     
     */
    public BeurkundeteDatenZeitraumRegistereintragFlexibel getSterbefall() {
        return sterbefall;
    }

    /**
     * Sets the value of the sterbefall property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
     *     
     */
    public void setSterbefall(BeurkundeteDatenZeitraumRegistereintragFlexibel value) {
        this.sterbefall = value;
    }

}
