//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Der Auskunftsgeber wird dem Finanzamt (siehe Datensatzbeschreibung des BMF), dem Zentralen Testamentsregister und dem Geburtenbuchführer mitgeteilt. Die Daten des Auskunftsgebers werden grundsätzlich nur zur Aufgabenerfüllung weiterer Kommunikationspartner mitgeteilt. Der Auskunftsgeber ist entweder eine natürliche Person oder eine Behörde. Falls der Auskunftsgeber eine Behörde ist, wird nur der Behördenname mitgeteilt.
 * 
 * <p>Java class for StA2ZTR.Auskunftsgeber complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2ZTR.Auskunftsgeber">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="natuerlichePerson" type="{http://xpsw.domap.de/xpsw2611}StA2ZTR.Auskunftsgeber.NatuerlichePerson"/>
 *         <element name="behoerde" type="{http://xpsw.domap.de/xpsw2611}Behoerdenbezeichnung"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2ZTR.Auskunftsgeber", propOrder = {
    "natuerlichePerson",
    "behoerde"
})
public class StA2ZTRAuskunftsgeber {

    protected StA2ZTRAuskunftsgeberNatuerlichePerson natuerlichePerson;
    protected Behoerdenbezeichnung behoerde;

    /**
     * Gets the value of the natuerlichePerson property.
     * 
     * @return
     *     possible object is
     *     {@link StA2ZTRAuskunftsgeberNatuerlichePerson }
     *     
     */
    public StA2ZTRAuskunftsgeberNatuerlichePerson getNatuerlichePerson() {
        return natuerlichePerson;
    }

    /**
     * Sets the value of the natuerlichePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2ZTRAuskunftsgeberNatuerlichePerson }
     *     
     */
    public void setNatuerlichePerson(StA2ZTRAuskunftsgeberNatuerlichePerson value) {
        this.natuerlichePerson = value;
    }

    /**
     * Gets the value of the behoerde property.
     * 
     * @return
     *     possible object is
     *     {@link Behoerdenbezeichnung }
     *     
     */
    public Behoerdenbezeichnung getBehoerde() {
        return behoerde;
    }

    /**
     * Sets the value of the behoerde property.
     * 
     * @param value
     *     allowed object is
     *     {@link Behoerdenbezeichnung }
     *     
     */
    public void setBehoerde(Behoerdenbezeichnung value) {
        this.behoerde = value;
    }

}
