//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Container fasst die Daten zusammen, die für die Berichtigung bzw. Fortschreibung eines Ereignisorts nötig sind.
 * 
 * <p>Java class for StA2StA1B.Berichtigung.Ereignisort complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2StA1B.Berichtigung.Ereignisort">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="alt" type="{http://xpsw.domap.de/xpsw2611}Ereignisort"/>
 *         <element name="neu" type="{http://xpsw.domap.de/xpsw2611}Ereignisort"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2StA1B.Berichtigung.Ereignisort", propOrder = {
    "alt",
    "neu"
})
public class StA2StA1BBerichtigungEreignisort {

    @XmlElement(required = true)
    protected Ereignisort alt;
    @XmlElement(required = true)
    protected Ereignisort neu;

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setAlt(Ereignisort value) {
        this.alt = value;
    }

    /**
     * Gets the value of the neu property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getNeu() {
        return neu;
    }

    /**
     * Sets the value of the neu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setNeu(Ereignisort value) {
        this.neu = value;
    }

}
