//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.util.ArrayList;
import java.util.List;
import de.xoev.schemata.basisnachricht.unqualified.g2g._1_1.KommunikationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.StA2StA">
 *       <sequence>
 *         <element name="geburtsnameKindNeu" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="anschriftDesKindes" type="{http://xpsw.domap.de/xpsw2611}Anschrift.Inland" minOccurs="0"/>
 *         <element name="staatsangehoerigkeitDesKindes" type="{http://xpsw.domap.de/xpsw2611}Code.Staatsangehoerigkeit" minOccurs="0"/>
 *         <element name="erklaerung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="einwilligungElternteil" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="einwilligung" type="{http://xpsw.domap.de/xpsw2611}StA2StA.Erklaerung.Einwilligung.MitAnschrift"/>
 *                   <element name="sterbefall" type="{http://xpsw.domap.de/xpsw2611}BeurkundeteDaten.Zeitraum.Registereintrag.Flexibel"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="kommunikation" type="{http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1}KommunikationType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geburtsnameKindNeu",
    "anschriftDesKindes",
    "staatsangehoerigkeitDesKindes",
    "erklaerung",
    "einwilligungElternteil",
    "kommunikation"
})
@XmlRootElement(name = "stA2StA.Erklaerung.011211")
public class StA2StAErklaerung011211
    extends NachrichtStA2StA
{

    @XmlElement(required = true)
    protected String geburtsnameKindNeu;
    protected AnschriftInland anschriftDesKindes;
    protected CodeStaatsangehoerigkeit staatsangehoerigkeitDesKindes;
    @XmlElement(required = true)
    protected String erklaerung;
    protected StA2StAErklaerung011211 .EinwilligungElternteil einwilligungElternteil;
    protected List<KommunikationType> kommunikation;

    /**
     * Gets the value of the geburtsnameKindNeu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtsnameKindNeu() {
        return geburtsnameKindNeu;
    }

    /**
     * Sets the value of the geburtsnameKindNeu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsnameKindNeu(String value) {
        this.geburtsnameKindNeu = value;
    }

    /**
     * Gets the value of the anschriftDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftDesKindes() {
        return anschriftDesKindes;
    }

    /**
     * Sets the value of the anschriftDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftDesKindes(AnschriftInland value) {
        this.anschriftDesKindes = value;
    }

    /**
     * Gets the value of the staatsangehoerigkeitDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public CodeStaatsangehoerigkeit getStaatsangehoerigkeitDesKindes() {
        return staatsangehoerigkeitDesKindes;
    }

    /**
     * Sets the value of the staatsangehoerigkeitDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public void setStaatsangehoerigkeitDesKindes(CodeStaatsangehoerigkeit value) {
        this.staatsangehoerigkeitDesKindes = value;
    }

    /**
     * Gets the value of the erklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErklaerung() {
        return erklaerung;
    }

    /**
     * Sets the value of the erklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErklaerung(String value) {
        this.erklaerung = value;
    }

    /**
     * Gets the value of the einwilligungElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link StA2StAErklaerung011211 .EinwilligungElternteil }
     *     
     */
    public StA2StAErklaerung011211 .EinwilligungElternteil getEinwilligungElternteil() {
        return einwilligungElternteil;
    }

    /**
     * Sets the value of the einwilligungElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2StAErklaerung011211 .EinwilligungElternteil }
     *     
     */
    public void setEinwilligungElternteil(StA2StAErklaerung011211 .EinwilligungElternteil value) {
        this.einwilligungElternteil = value;
    }

    /**
     * Gets the value of the kommunikation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the kommunikation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKommunikation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KommunikationType }
     * 
     * 
     * @return
     *     The value of the kommunikation property.
     */
    public List<KommunikationType> getKommunikation() {
        if (kommunikation == null) {
            kommunikation = new ArrayList<>();
        }
        return this.kommunikation;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="einwilligung" type="{http://xpsw.domap.de/xpsw2611}StA2StA.Erklaerung.Einwilligung.MitAnschrift"/>
     *         <element name="sterbefall" type="{http://xpsw.domap.de/xpsw2611}BeurkundeteDaten.Zeitraum.Registereintrag.Flexibel"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "einwilligung",
        "sterbefall"
    })
    public static class EinwilligungElternteil {

        protected StA2StAErklaerungEinwilligungMitAnschrift einwilligung;
        protected BeurkundeteDatenZeitraumRegistereintragFlexibel sterbefall;

        /**
         * Gets the value of the einwilligung property.
         * 
         * @return
         *     possible object is
         *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
         *     
         */
        public StA2StAErklaerungEinwilligungMitAnschrift getEinwilligung() {
            return einwilligung;
        }

        /**
         * Sets the value of the einwilligung property.
         * 
         * @param value
         *     allowed object is
         *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
         *     
         */
        public void setEinwilligung(StA2StAErklaerungEinwilligungMitAnschrift value) {
            this.einwilligung = value;
        }

        /**
         * Gets the value of the sterbefall property.
         * 
         * @return
         *     possible object is
         *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
         *     
         */
        public BeurkundeteDatenZeitraumRegistereintragFlexibel getSterbefall() {
            return sterbefall;
        }

        /**
         * Sets the value of the sterbefall property.
         * 
         * @param value
         *     allowed object is
         *     {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
         *     
         */
        public void setSterbefall(BeurkundeteDatenZeitraumRegistereintragFlexibel value) {
            this.sterbefall = value;
        }

    }

}
