//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.StA2MB">
 *       <sequence>
 *         <element name="sterbeeintrag" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Nachweisdaten.Ort"/>
 *         <element name="identitaetNichtNachgewiesen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sterbeeintrag",
    "identitaetNichtNachgewiesen"
})
@XmlRootElement(name = "stA2MB.Sterbefall.035010")
public class StA2MBSterbefall035010
    extends NachrichtStA2MB
{

    @XmlElement(required = true)
    protected StA2MBNachweisdatenOrt sterbeeintrag;
    protected Boolean identitaetNichtNachgewiesen;

    /**
     * Gets the value of the sterbeeintrag property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBNachweisdatenOrt }
     *     
     */
    public StA2MBNachweisdatenOrt getSterbeeintrag() {
        return sterbeeintrag;
    }

    /**
     * Sets the value of the sterbeeintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBNachweisdatenOrt }
     *     
     */
    public void setSterbeeintrag(StA2MBNachweisdatenOrt value) {
        this.sterbeeintrag = value;
    }

    /**
     * Gets the value of the identitaetNichtNachgewiesen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIdentitaetNichtNachgewiesen() {
        return identitaetNichtNachgewiesen;
    }

    /**
     * Sets the value of the identitaetNichtNachgewiesen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIdentitaetNichtNachgewiesen(Boolean value) {
        this.identitaetNichtNachgewiesen = value;
    }

}
