//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Nachricht.StA2MB">
 *       <sequence>
 *         <element name="person1" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Person.MitAnschrift"/>
 *         <element name="person2" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Person.MitAnschrift"/>
 *         <element name="aufgeloesteLP" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Nachweisdaten"/>
 *         <element name="aufloesungLP" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Nachweisdaten"/>
 *         <element name="neuerFamilienstandPerson1" type="{http://xpsw.domap.de/xpsw2611}Code.FamilienstandMeldewesen"/>
 *         <element name="neuerFamilienstandPerson2" type="{http://xpsw.domap.de/xpsw2611}Code.FamilienstandMeldewesen"/>
 *         <element name="beendigungsgrund" type="{http://xpsw.domap.de/xpsw2611}Code.BeendigungsgrundFamilienstand"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "person1",
    "person2",
    "aufgeloesteLP",
    "aufloesungLP",
    "neuerFamilienstandPerson1",
    "neuerFamilienstandPerson2",
    "beendigungsgrund"
})
@XmlRootElement(name = "stA2MB.LP.033030")
public class StA2MBLP033030
    extends NachrichtStA2MB
{

    @XmlElement(required = true)
    protected StA2MBPersonMitAnschrift person1;
    @XmlElement(required = true)
    protected StA2MBPersonMitAnschrift person2;
    @XmlElement(required = true)
    protected StA2MBNachweisdaten aufgeloesteLP;
    @XmlElement(required = true)
    protected StA2MBNachweisdaten aufloesungLP;
    @XmlElement(required = true)
    protected CodeFamilienstandMeldewesen neuerFamilienstandPerson1;
    @XmlElement(required = true)
    protected CodeFamilienstandMeldewesen neuerFamilienstandPerson2;
    @XmlElement(required = true)
    protected CodeBeendigungsgrundFamilienstand beendigungsgrund;

    /**
     * Gets the value of the person1 property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public StA2MBPersonMitAnschrift getPerson1() {
        return person1;
    }

    /**
     * Sets the value of the person1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public void setPerson1(StA2MBPersonMitAnschrift value) {
        this.person1 = value;
    }

    /**
     * Gets the value of the person2 property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public StA2MBPersonMitAnschrift getPerson2() {
        return person2;
    }

    /**
     * Sets the value of the person2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBPersonMitAnschrift }
     *     
     */
    public void setPerson2(StA2MBPersonMitAnschrift value) {
        this.person2 = value;
    }

    /**
     * Gets the value of the aufgeloesteLP property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public StA2MBNachweisdaten getAufgeloesteLP() {
        return aufgeloesteLP;
    }

    /**
     * Sets the value of the aufgeloesteLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public void setAufgeloesteLP(StA2MBNachweisdaten value) {
        this.aufgeloesteLP = value;
    }

    /**
     * Gets the value of the aufloesungLP property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public StA2MBNachweisdaten getAufloesungLP() {
        return aufloesungLP;
    }

    /**
     * Sets the value of the aufloesungLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBNachweisdaten }
     *     
     */
    public void setAufloesungLP(StA2MBNachweisdaten value) {
        this.aufloesungLP = value;
    }

    /**
     * Gets the value of the neuerFamilienstandPerson1 property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFamilienstandMeldewesen }
     *     
     */
    public CodeFamilienstandMeldewesen getNeuerFamilienstandPerson1() {
        return neuerFamilienstandPerson1;
    }

    /**
     * Sets the value of the neuerFamilienstandPerson1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFamilienstandMeldewesen }
     *     
     */
    public void setNeuerFamilienstandPerson1(CodeFamilienstandMeldewesen value) {
        this.neuerFamilienstandPerson1 = value;
    }

    /**
     * Gets the value of the neuerFamilienstandPerson2 property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFamilienstandMeldewesen }
     *     
     */
    public CodeFamilienstandMeldewesen getNeuerFamilienstandPerson2() {
        return neuerFamilienstandPerson2;
    }

    /**
     * Sets the value of the neuerFamilienstandPerson2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFamilienstandMeldewesen }
     *     
     */
    public void setNeuerFamilienstandPerson2(CodeFamilienstandMeldewesen value) {
        this.neuerFamilienstandPerson2 = value;
    }

    /**
     * Gets the value of the beendigungsgrund property.
     * 
     * @return
     *     possible object is
     *     {@link CodeBeendigungsgrundFamilienstand }
     *     
     */
    public CodeBeendigungsgrundFamilienstand getBeendigungsgrund() {
        return beendigungsgrund;
    }

    /**
     * Sets the value of the beendigungsgrund property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeBeendigungsgrundFamilienstand }
     *     
     */
    public void setBeendigungsgrund(CodeBeendigungsgrundFamilienstand value) {
        this.beendigungsgrund = value;
    }

}
