//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import de.osci.xinneres.datum._2.TeilbekanntesDatum;
import de.osci.xinneres.idnr._2.PlausibilisierteIdentifikationsnummer;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp fasst die Angaben zu einem gesetzlichen Vertreter in Mitteilungen zu Erklärungsinhalten zusammen.
 * 
 * <p>Java class for StA2StA.Erklaerung.GesetzlicherVertreter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2StA.Erklaerung.GesetzlicherVertreter">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namen" type="{http://xpsw.domap.de/xpsw2611}StA2StA.PersonName.Aenderung"/>
 *         <element name="geburtsort" type="{http://xpsw.domap.de/xpsw2611}Ereignisort"/>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatum"/>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2611}Anschrift.InlandAusland"/>
 *         <element name="identifikationsnummer" type="{http://www.osci.de/xinneres/idnr/2}PlausibilisierteIdentifikationsnummer" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2StA.Erklaerung.GesetzlicherVertreter", propOrder = {
    "namen",
    "geburtsort",
    "geburtsdatum",
    "anschrift",
    "identifikationsnummer"
})
public class StA2StAErklaerungGesetzlicherVertreter {

    @XmlElement(required = true)
    protected StA2StAPersonNameAenderung namen;
    @XmlElement(required = true)
    protected Ereignisort geburtsort;
    @XmlElement(required = true)
    protected TeilbekanntesDatum geburtsdatum;
    @XmlElement(required = true)
    protected AnschriftInlandAusland anschrift;
    protected PlausibilisierteIdentifikationsnummer identifikationsnummer;

    /**
     * Gets the value of the namen property.
     * 
     * @return
     *     possible object is
     *     {@link StA2StAPersonNameAenderung }
     *     
     */
    public StA2StAPersonNameAenderung getNamen() {
        return namen;
    }

    /**
     * Sets the value of the namen property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2StAPersonNameAenderung }
     *     
     */
    public void setNamen(StA2StAPersonNameAenderung value) {
        this.namen = value;
    }

    /**
     * Gets the value of the geburtsort property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getGeburtsort() {
        return geburtsort;
    }

    /**
     * Sets the value of the geburtsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setGeburtsort(Ereignisort value) {
        this.geburtsort = value;
    }

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatum }
     *     
     */
    public TeilbekanntesDatum getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatum }
     *     
     */
    public void setGeburtsdatum(TeilbekanntesDatum value) {
        this.geburtsdatum = value;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public AnschriftInlandAusland getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public void setAnschrift(AnschriftInlandAusland value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the identifikationsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public PlausibilisierteIdentifikationsnummer getIdentifikationsnummer() {
        return identifikationsnummer;
    }

    /**
     * Sets the value of the identifikationsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public void setIdentifikationsnummer(PlausibilisierteIdentifikationsnummer value) {
        this.identifikationsnummer = value;
    }

}
