//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese Klasse beinhaltet die Daten zur Anschrift, die der mb übermittelt werden.
 * 
 * <p>Java class for StA2MB.Anschrift complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2MB.Anschrift">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2611}StA2MB.Anschrift.Meldebehoerde"/>
 *         <element name="staat" type="{http://xpsw.domap.de/xpsw2611}Code.Staat"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2MB.Anschrift", propOrder = {
    "anschrift",
    "staat"
})
public class StA2MBAnschrift {

    protected StA2MBAnschriftMeldebehoerde anschrift;
    protected CodeStaat staat;

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBAnschriftMeldebehoerde }
     *     
     */
    public StA2MBAnschriftMeldebehoerde getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBAnschriftMeldebehoerde }
     *     
     */
    public void setAnschrift(StA2MBAnschriftMeldebehoerde value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the staat property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStaat }
     *     
     */
    public CodeStaat getStaat() {
        return staat;
    }

    /**
     * Sets the value of the staat property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStaat }
     *     
     */
    public void setStaat(CodeStaat value) {
        this.staat = value;
    }

}
