//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.time.LocalDate;
import com.vertama.xpersonenstand._2611.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Dieser Container enthält die Datenfelder zur Beschreibung der natürlichen Person als Auskunftsgeber.
 * 
 * <p>Java class for StA2ZTR.Auskunftsgeber.NatuerlichePerson.Geburtsdatum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2ZTR.Auskunftsgeber.NatuerlichePerson.Geburtsdatum">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}StA2ZTR.Auskunftsgeber.NatuerlichePerson">
 *       <sequence>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2ZTR.Auskunftsgeber.NatuerlichePerson.Geburtsdatum", propOrder = {
    "geburtsdatum"
})
public class StA2ZTRAuskunftsgeberNatuerlichePersonGeburtsdatum
    extends StA2ZTRAuskunftsgeberNatuerlichePerson
{

    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate geburtsdatum;

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsdatum(LocalDate value) {
        this.geburtsdatum = value;
    }

}
