//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import de.osci.xinneres.meldeanschrift._5.Meldeanschrift;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese Klasse beinhaltet die Daten zur Anschrift, die der mb übermittelt werden. Von den aus der Meldeanschrift übernommenen Elementen wurden die Elemente stockwerkswohnungsnummer, zusatzangaben und wohnungsgeber entfernt.
 * 
 * <p>Java class for StA2MB.Anschrift.Meldebehoerde complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2MB.Anschrift.Meldebehoerde">
 *   <complexContent>
 *     <restriction base="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift">
 *       <sequence>
 *         <element name="gemeindeschluessel" type="{http://www.osci.de/xinneres/codes/gemeindeverzeichnis/3}Code.GemeindeVZ.AmtlicherGemeindeschluessel" form="unqualified"/>
 *         <element name="hausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.Hausnummer" minOccurs="0" form="unqualified"/>
 *         <element name="hausnummerBuchstabeZusatzziffer" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.HausnummerBuchstabeZusatzziffer" minOccurs="0" form="unqualified"/>
 *         <element name="postleitzahl" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.Postleitzahl" form="unqualified"/>
 *         <element name="strasse" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.Strasse" minOccurs="0" form="unqualified"/>
 *         <element name="teilnummerDerHausnummer" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.TeilnummerDerHausnummer" minOccurs="0" form="unqualified"/>
 *         <element name="wohnort" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.Wohnort" form="unqualified"/>
 *         <element name="wohnortFruehererGemeindename" type="{http://www.osci.de/xinneres/meldeanschrift/5}Meldeanschrift.WohnortFruehererGemeindename" minOccurs="0" form="unqualified"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2MB.Anschrift.Meldebehoerde")
public class StA2MBAnschriftMeldebehoerde
    extends Meldeanschrift
{


}
