//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}StA2StA.Familienrecht.Template.LPnamensaenderung.Eltern2Kind">
 *       <sequence>
 *         <element name="lebenspartnerschaftseintrag" type="{http://xpsw.domap.de/xpsw2611}Quelleintrag"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lebenspartnerschaftseintrag"
})
@XmlRootElement(name = "stA2StA.LP.013050")
public class StA2StALP013050
    extends StA2StAFamilienrechtTemplateLPnamensaenderungEltern2Kind
{

    @XmlElement(required = true)
    protected Quelleintrag lebenspartnerschaftseintrag;

    /**
     * Gets the value of the lebenspartnerschaftseintrag property.
     * 
     * @return
     *     possible object is
     *     {@link Quelleintrag }
     *     
     */
    public Quelleintrag getLebenspartnerschaftseintrag() {
        return lebenspartnerschaftseintrag;
    }

    /**
     * Sets the value of the lebenspartnerschaftseintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quelleintrag }
     *     
     */
    public void setLebenspartnerschaftseintrag(Quelleintrag value) {
        this.lebenspartnerschaftseintrag = value;
    }

}
