//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp enthält Angaben zum Antragsteller der Urkundenanforderung. Dabei kann zwischen Angaben zu einer juristischen oder einer natürlichen Person gewählt werden.
 * 
 * <p>Java class for Urkundenanforderung.Antragsteller.Elektronisch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Urkundenanforderung.Antragsteller.Elektronisch">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="juristischePerson" type="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.Antragsteller.JuristischePerson"/>
 *         <element name="natuerlichePerson" type="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.Antragsteller.NatuerlichePerson.Elektronisch"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Urkundenanforderung.Antragsteller.Elektronisch", propOrder = {
    "juristischePerson",
    "natuerlichePerson"
})
public class UrkundenanforderungAntragstellerElektronisch {

    protected UrkundenanforderungAntragstellerJuristischePerson juristischePerson;
    protected UrkundenanforderungAntragstellerNatuerlichePersonElektronisch natuerlichePerson;

    /**
     * Gets the value of the juristischePerson property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungAntragstellerJuristischePerson }
     *     
     */
    public UrkundenanforderungAntragstellerJuristischePerson getJuristischePerson() {
        return juristischePerson;
    }

    /**
     * Sets the value of the juristischePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungAntragstellerJuristischePerson }
     *     
     */
    public void setJuristischePerson(UrkundenanforderungAntragstellerJuristischePerson value) {
        this.juristischePerson = value;
    }

    /**
     * Gets the value of the natuerlichePerson property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungAntragstellerNatuerlichePersonElektronisch }
     *     
     */
    public UrkundenanforderungAntragstellerNatuerlichePersonElektronisch getNatuerlichePerson() {
        return natuerlichePerson;
    }

    /**
     * Sets the value of the natuerlichePerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungAntragstellerNatuerlichePersonElektronisch }
     *     
     */
    public void setNatuerlichePerson(UrkundenanforderungAntragstellerNatuerlichePersonElektronisch value) {
        this.natuerlichePerson = value;
    }

}
