//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp enthält Angaben zu Anzahl und Art der angeforderten Bescheinigungen aus dem Eheregister.
 * 
 * <p>Java class for Urkundenanforderung.ArtDerBescheinigung.L complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Urkundenanforderung.ArtDerBescheinigung.L">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="anzahlBescheinigungNamenLP" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="anzahlBescheinigungNamenLPn" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Urkundenanforderung.ArtDerBescheinigung.L", propOrder = {
    "anzahlBescheinigungNamenLP",
    "anzahlBescheinigungNamenLPn"
})
public class UrkundenanforderungArtDerBescheinigungL {

    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlBescheinigungNamenLP;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlBescheinigungNamenLPn;

    /**
     * Gets the value of the anzahlBescheinigungNamenLP property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlBescheinigungNamenLP() {
        return anzahlBescheinigungNamenLP;
    }

    /**
     * Sets the value of the anzahlBescheinigungNamenLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlBescheinigungNamenLP(BigInteger value) {
        this.anzahlBescheinigungNamenLP = value;
    }

    /**
     * Gets the value of the anzahlBescheinigungNamenLPn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlBescheinigungNamenLPn() {
        return anzahlBescheinigungNamenLPn;
    }

    /**
     * Sets the value of the anzahlBescheinigungNamenLPn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlBescheinigungNamenLPn(BigInteger value) {
        this.anzahlBescheinigungNamenLPn = value;
    }

}
