//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp enthält Angaben zu Anzahl und Art der angeforderten Urkunden.
 * 
 * <p>Java class for Urkundenanforderung.ArtDerUrkunde.Erweitert complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Urkundenanforderung.ArtDerUrkunde.Erweitert">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.ArtDerUrkunde.Basis">
 *       <sequence>
 *         <element name="anzahlRegisterausdruck" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="anzahlRegisterausdruckMitHinweisen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="anzahlSozialversicherung" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="anzahlUebersetzungshilfe" type="{http://xpsw.domap.de/xpsw2611}Urkundenanforderung.Uebersetzungshilfe" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Urkundenanforderung.ArtDerUrkunde.Erweitert", propOrder = {
    "anzahlRegisterausdruck",
    "anzahlRegisterausdruckMitHinweisen",
    "anzahlSozialversicherung",
    "anzahlUebersetzungshilfe"
})
public class UrkundenanforderungArtDerUrkundeErweitert
    extends UrkundenanforderungArtDerUrkundeBasis
{

    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlRegisterausdruck;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlRegisterausdruckMitHinweisen;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlSozialversicherung;
    protected List<UrkundenanforderungUebersetzungshilfe> anzahlUebersetzungshilfe;

    /**
     * Gets the value of the anzahlRegisterausdruck property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlRegisterausdruck() {
        return anzahlRegisterausdruck;
    }

    /**
     * Sets the value of the anzahlRegisterausdruck property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlRegisterausdruck(BigInteger value) {
        this.anzahlRegisterausdruck = value;
    }

    /**
     * Gets the value of the anzahlRegisterausdruckMitHinweisen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlRegisterausdruckMitHinweisen() {
        return anzahlRegisterausdruckMitHinweisen;
    }

    /**
     * Sets the value of the anzahlRegisterausdruckMitHinweisen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlRegisterausdruckMitHinweisen(BigInteger value) {
        this.anzahlRegisterausdruckMitHinweisen = value;
    }

    /**
     * Gets the value of the anzahlSozialversicherung property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlSozialversicherung() {
        return anzahlSozialversicherung;
    }

    /**
     * Sets the value of the anzahlSozialversicherung property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlSozialversicherung(BigInteger value) {
        this.anzahlSozialversicherung = value;
    }

    /**
     * Gets the value of the anzahlUebersetzungshilfe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anzahlUebersetzungshilfe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnzahlUebersetzungshilfe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UrkundenanforderungUebersetzungshilfe }
     * 
     * 
     * @return
     *     The value of the anzahlUebersetzungshilfe property.
     */
    public List<UrkundenanforderungUebersetzungshilfe> getAnzahlUebersetzungshilfe() {
        if (anzahlUebersetzungshilfe == null) {
            anzahlUebersetzungshilfe = new ArrayList<>();
        }
        return this.anzahlUebersetzungshilfe;
    }

}
