//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Container enthält Informationen über die Zahlung. Es sind hier nur Kosten für beantragte Urkunden anzugeben, keine Preise mitzuteilen.
 * 
 * <p>Java class for Urkundenanforderung.Zahlungsinformationen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Urkundenanforderung.Zahlungsinformationen">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="zahlungsart" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="lastschrift">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                             <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *                             <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                             <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="vorkasse">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                             <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *                             <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                             <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="nachnahme" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   <element name="rechnung" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="buchungsreferenz" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="sonstigeZahlungsinformationen" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="gesamtkosten" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Urkundenanforderung.Zahlungsinformationen", propOrder = {
    "zahlungsart",
    "buchungsreferenz",
    "sonstigeZahlungsinformationen",
    "gesamtkosten"
})
public class UrkundenanforderungZahlungsinformationen {

    protected UrkundenanforderungZahlungsinformationen.Zahlungsart zahlungsart;
    protected String buchungsreferenz;
    protected String sonstigeZahlungsinformationen;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger gesamtkosten;

    /**
     * Gets the value of the zahlungsart property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart }
     *     
     */
    public UrkundenanforderungZahlungsinformationen.Zahlungsart getZahlungsart() {
        return zahlungsart;
    }

    /**
     * Sets the value of the zahlungsart property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart }
     *     
     */
    public void setZahlungsart(UrkundenanforderungZahlungsinformationen.Zahlungsart value) {
        this.zahlungsart = value;
    }

    /**
     * Gets the value of the buchungsreferenz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuchungsreferenz() {
        return buchungsreferenz;
    }

    /**
     * Sets the value of the buchungsreferenz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuchungsreferenz(String value) {
        this.buchungsreferenz = value;
    }

    /**
     * Gets the value of the sonstigeZahlungsinformationen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonstigeZahlungsinformationen() {
        return sonstigeZahlungsinformationen;
    }

    /**
     * Sets the value of the sonstigeZahlungsinformationen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonstigeZahlungsinformationen(String value) {
        this.sonstigeZahlungsinformationen = value;
    }

    /**
     * Gets the value of the gesamtkosten property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGesamtkosten() {
        return gesamtkosten;
    }

    /**
     * Sets the value of the gesamtkosten property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGesamtkosten(BigInteger value) {
        this.gesamtkosten = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="lastschrift">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                   <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
     *                   <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                   <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="vorkasse">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                   <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
     *                   <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                   <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="nachnahme" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         <element name="rechnung" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lastschrift",
        "vorkasse",
        "nachnahme",
        "rechnung"
    })
    public static class Zahlungsart {

        protected UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift lastschrift;
        protected UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse vorkasse;
        protected Boolean nachnahme;
        protected Boolean rechnung;

        /**
         * Gets the value of the lastschrift property.
         * 
         * @return
         *     possible object is
         *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
         *     
         */
        public UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift getLastschrift() {
            return lastschrift;
        }

        /**
         * Sets the value of the lastschrift property.
         * 
         * @param value
         *     allowed object is
         *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
         *     
         */
        public void setLastschrift(UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift value) {
            this.lastschrift = value;
        }

        /**
         * Gets the value of the vorkasse property.
         * 
         * @return
         *     possible object is
         *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
         *     
         */
        public UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse getVorkasse() {
            return vorkasse;
        }

        /**
         * Sets the value of the vorkasse property.
         * 
         * @param value
         *     allowed object is
         *     {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
         *     
         */
        public void setVorkasse(UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse value) {
            this.vorkasse = value;
        }

        /**
         * Gets the value of the nachnahme property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNachnahme() {
            return nachnahme;
        }

        /**
         * Sets the value of the nachnahme property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNachnahme(Boolean value) {
            this.nachnahme = value;
        }

        /**
         * Gets the value of the rechnung property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isRechnung() {
            return rechnung;
        }

        /**
         * Sets the value of the rechnung property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setRechnung(Boolean value) {
            this.rechnung = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *         <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
         *         <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *         <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kontoinhaber",
            "bank",
            "iban",
            "swift"
        })
        public static class Lastschrift {

            @XmlElement(required = true)
            protected String kontoinhaber;
            protected String bank;
            @XmlElement(name = "iBAN", required = true)
            protected String iban;
            @XmlElement(name = "sWIFT")
            protected String swift;

            /**
             * Gets the value of the kontoinhaber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKontoinhaber() {
                return kontoinhaber;
            }

            /**
             * Sets the value of the kontoinhaber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKontoinhaber(String value) {
                this.kontoinhaber = value;
            }

            /**
             * Gets the value of the bank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBank() {
                return bank;
            }

            /**
             * Sets the value of the bank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBank(String value) {
                this.bank = value;
            }

            /**
             * Gets the value of the iban property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIBAN() {
                return iban;
            }

            /**
             * Sets the value of the iban property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIBAN(String value) {
                this.iban = value;
            }

            /**
             * Gets the value of the swift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSWIFT() {
                return swift;
            }

            /**
             * Sets the value of the swift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSWIFT(String value) {
                this.swift = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="kontoinhaber" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *         <element name="bank" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
         *         <element name="iBAN" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *         <element name="sWIFT" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kontoinhaber",
            "bank",
            "iban",
            "swift"
        })
        public static class Vorkasse {

            @XmlElement(required = true)
            protected String kontoinhaber;
            protected String bank;
            @XmlElement(name = "iBAN", required = true)
            protected String iban;
            @XmlElement(name = "sWIFT")
            protected String swift;

            /**
             * Gets the value of the kontoinhaber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKontoinhaber() {
                return kontoinhaber;
            }

            /**
             * Sets the value of the kontoinhaber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKontoinhaber(String value) {
                this.kontoinhaber = value;
            }

            /**
             * Gets the value of the bank property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBank() {
                return bank;
            }

            /**
             * Sets the value of the bank property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBank(String value) {
                this.bank = value;
            }

            /**
             * Gets the value of the iban property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIBAN() {
                return iban;
            }

            /**
             * Sets the value of the iban property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIBAN(String value) {
                this.iban = value;
            }

            /**
             * Gets the value of the swift property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSWIFT() {
                return swift;
            }

            /**
             * Sets the value of the swift property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSWIFT(String value) {
                this.swift = value;
            }

        }

    }

}
