//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2611;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Container enthält die Identifikationsdaten für einen Eintrag in dem Register des Lesers der Mitteilung.
 * 
 * <p>Java class for Zieleintrag complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Zieleintrag">
 *   <complexContent>
 *     <restriction base="{http://xpsw.domap.de/xpsw2611}Registereintrag">
 *       <sequence>
 *         <element name="behoerdenname" type="{http://xpsw.domap.de/xpsw2611}Behoerdenbezeichnung"/>
 *         <element name="standesamtsnummer" type="{http://xpsw.domap.de/xpsw2611}Code.Standesamtsnummer"/>
 *         <element name="registerart" type="{http://xpsw.domap.de/xpsw2611}Code.Registerart" minOccurs="0"/>
 *         <element name="erstbeurkundungsjahr" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *         <element name="eintragsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zieleintrag")
public class Zieleintrag
    extends Registereintrag
{


}
