//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.xoev.schemata.code._1_0;

import de.domap.xpsw.xpsw2505.CodeAGSCode;
import de.domap.xpsw.xpsw2505.CodeArtErklaerungEheCode;
import de.domap.xpsw.xpsw2505.CodeArtNameWiederannahmeCode;
import de.domap.xpsw.xpsw2505.CodeAufenthaltsrechtCode;
import de.domap.xpsw.xpsw2505.CodeAufenthaltsstatusCode;
import de.domap.xpsw.xpsw2505.CodeAusweisartCode;
import de.domap.xpsw.xpsw2505.CodeBeendigungsgrundFamilienstandCode;
import de.domap.xpsw.xpsw2505.CodeBeschlussartCode;
import de.domap.xpsw.xpsw2505.CodeBestattungsartCode;
import de.domap.xpsw.xpsw2505.CodeFamilienrechtlicheBezeichnungEheregisterCode;
import de.domap.xpsw.xpsw2505.CodeFamilienrechtlicheBezeichnungGeburtenregisterCode;
import de.domap.xpsw.xpsw2505.CodeFamilienrechtlicheBezeichnungLPregisterCode;
import de.domap.xpsw.xpsw2505.CodeFamilienstandMeldewesenCode;
import de.domap.xpsw.xpsw2505.CodeFamilienstandPersonenstandswesenCode;
import de.domap.xpsw.xpsw2505.CodeFehlerartCode;
import de.domap.xpsw.xpsw2505.CodeFehlerartEGSCode;
import de.domap.xpsw.xpsw2505.CodeIdentifizierungsartCode;
import de.domap.xpsw.xpsw2505.CodeNachrichtentyp;
import de.domap.xpsw.xpsw2505.CodeNamensartCode;
import de.domap.xpsw.xpsw2505.CodeNamensfuehrungCode;
import de.domap.xpsw.xpsw2505.CodePersonenstandsrechtlicherTatbestandCode;
import de.domap.xpsw.xpsw2505.CodeRechtsgrundlageCode;
import de.domap.xpsw.xpsw2505.CodeRegisterart;
import de.domap.xpsw.xpsw2505.CodeSpracheUebersetzungshilfeCode;
import de.domap.xpsw.xpsw2505.CodeStaatCode;
import de.domap.xpsw.xpsw2505.CodeStaatsangehoerigkeitCode;
import de.domap.xpsw.xpsw2505.CodeStandesamtsnummerCode;
import de.domap.xpsw.xpsw2505.CodeVerwendungszweckEheurkundeCode;
import de.domap.xpsw.xpsw2505.CodeVerwendungszweckGeburtsurkundeCode;
import de.domap.xpsw.xpsw2505.CodeVerwendungszweckLPurkundeCode;
import de.domap.xpsw.xpsw2505.CodeVerwendungszweckSterbeurkundeCode;
import de.domap.xpsw.xpsw2505.CodeWahlEhenameCode;
import de.domap.xpsw.xpsw2505.CodeWahlLPNameCode;
import de.osci.xinneres.auslandsanschrift._5.CodeZielstaat;
import de.osci.xinneres.basisnachricht._6.CodeNachrichtentypTyp4;
import de.osci.xinneres.behoerde._6.CodeBehoerdenkennung;
import de.osci.xinneres.behoerde._6.CodeDVDVBehoerdenschluessel;
import de.osci.xinneres.behoerde._6.CodePraefix;
import de.osci.xinneres.codes.gemeindeverzeichnis._3.CodeGemeindeVZAmtlicherGemeindeschluessel;
import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import de.osci.xinneres.kommunikation._5.CodeErreichbarkeit;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Der XÖV-Datentyp Code ermöglicht die Übermittlung von Werten, so genannter Codes, aus vordefinierten Codelisten. Eine Codeliste ist eine Liste von Codes und der Beschreibung ihrer jeweiligen Bedeutung.clRef 
 * 
 * Eine entscheidende Eigenschaft des Datentyps ist die Möglichkeit auf differenzierte Weise Bezug zu Codelisten zu nehmen (Code-Typ 1 bis 4).clTypenRef In jedem Fall erlauben die übermittelten Daten eine eindeutige Identifizierung der zugrundeliegenden Codeliste.
 * 
 * <p>Java class for Code complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Code">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="code" type="{http://www.w3.org/2001/XMLSchema}token" form="unqualified"/>
 *         <element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0" form="unqualified"/>
 *       </sequence>
 *       <attribute name="listURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       <attribute name="listVersionID" type="{http://www.w3.org/2001/XMLSchema}normalizedString" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Code", propOrder = {
    "code",
    "name"
})
@XmlSeeAlso({
    CodeGeschlecht.class,
    CodeAGSCode.class,
    CodeArtErklaerungEheCode.class,
    CodeArtNameWiederannahmeCode.class,
    CodeAufenthaltsrechtCode.class,
    CodeAufenthaltsstatusCode.class,
    CodeAusweisartCode.class,
    CodeBeendigungsgrundFamilienstandCode.class,
    CodeBeschlussartCode.class,
    CodeBestattungsartCode.class,
    CodeFamilienrechtlicheBezeichnungEheregisterCode.class,
    CodeFamilienrechtlicheBezeichnungGeburtenregisterCode.class,
    CodeFamilienrechtlicheBezeichnungLPregisterCode.class,
    CodeFamilienstandMeldewesenCode.class,
    CodeFamilienstandPersonenstandswesenCode.class,
    CodeFehlerartCode.class,
    CodeFehlerartEGSCode.class,
    CodeIdentifizierungsartCode.class,
    CodeNachrichtentyp.class,
    CodeNamensartCode.class,
    CodeNamensfuehrungCode.class,
    CodePersonenstandsrechtlicherTatbestandCode.class,
    CodeRechtsgrundlageCode.class,
    CodeRegisterart.class,
    CodeSpracheUebersetzungshilfeCode.class,
    CodeStaatCode.class,
    CodeStaatsangehoerigkeitCode.class,
    CodeStandesamtsnummerCode.class,
    CodeVerwendungszweckEheurkundeCode.class,
    CodeVerwendungszweckGeburtsurkundeCode.class,
    CodeVerwendungszweckLPurkundeCode.class,
    CodeVerwendungszweckSterbeurkundeCode.class,
    CodeWahlEhenameCode.class,
    CodeWahlLPNameCode.class,
    CodeZielstaat.class,
    CodeNachrichtentypTyp4 .class,
    CodeBehoerdenkennung.class,
    CodeDVDVBehoerdenschluessel.class,
    CodePraefix.class,
    CodeErreichbarkeit.class,
    CodeGemeindeVZAmtlicherGemeindeschluessel.class
})
public class Code {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String code;
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String name;
    @XmlAttribute(name = "listURI")
    @XmlSchemaType(name = "anyURI")
    protected String listURI;
    @XmlAttribute(name = "listVersionID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String listVersionID;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the listURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListURI() {
        return listURI;
    }

    /**
     * Sets the value of the listURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListURI(String value) {
        this.listURI = value;
    }

    /**
     * Gets the value of the listVersionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListVersionID() {
        return listVersionID;
    }

    /**
     * Sets the value of the listVersionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListVersionID(String value) {
        this.listVersionID = value;
    }

}
