//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.vertama.xpersonenstand._2511.model.de.osci.xinneres.auslandsanschrift._5;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp repräsentiert eine Zeile einer Aufschrift gemäß DIN 5008 und besteht aus dem Inhalt der Zeile sowie der Angabe der Zeilennummer in der Aufschrift. Sofern dieser Datentyp für die Übermittlung einer Zeile der Anschriftzone verwendet wird, sind ausschließlich die Zeilennummern 4 bis 8 zu verwenden. Zeilen der Vermerkzone werden in dem Datentyp Auslandsanschrift.Druckbild nicht übermittelt. Sofern in einem xinneres-fachmodul der Bedarf besteht, kann der Datentyp aber im Rahmen der Einbindung in das xinneres-fachmodul um weitere ZeileAufschrift-Kindelemente für die Vermerkzone ergänzt werden. Für diese Zeilen sind ausschließlich die Zeilennummern 1 bis 3 zu verwenden.
 * 
 * <p>Java class for ZeileAufschrift complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="ZeileAufschrift">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="zeilennummer" type="{http://www.osci.de/xinneres/auslandsanschrift/5}ZeileAufschrift.Zeilennummer"/>
 *         <element name="inhalt" type="{http://www.osci.de/xinneres/auslandsanschrift/5}ZeileAufschrift.Inhalt"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZeileAufschrift", propOrder = {
    "zeilennummer",
    "inhalt"
})
public class ZeileAufschrift {

    @XmlSchemaType(name = "nonNegativeInteger")
    protected int zeilennummer;
    @XmlElement(required = true)
    protected String inhalt;

    /**
     * Gets the value of the zeilennummer property.
     * 
     */
    public int getZeilennummer() {
        return zeilennummer;
    }

    /**
     * Sets the value of the zeilennummer property.
     * 
     */
    public void setZeilennummer(int value) {
        this.zeilennummer = value;
    }

    /**
     * Gets the value of the inhalt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInhalt() {
        return inhalt;
    }

    /**
     * Sets the value of the inhalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInhalt(String value) {
        this.inhalt = value;
    }

}
