//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import de.osci.xinneres.kommunikation._5.Kommunikation;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser abstrakte Datentyp dient als Vorlage für die Nachricht zur Anzeige der Geburt von einer Einrichtung sowie der Berichtigung dieser Anzeige. Da beide Nachrichten strukturidentisch sind, wurde diese Vorlage geschaffen, um redundante Datenhaltung zu vermeiden.
 * 
 * <p>Java class for Anz2StA.Template.Geburtsanzeige complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Anz2StA.Template.Geburtsanzeige">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2505}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="nameEinrichtung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="geburtsangaben">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.AngabenEreignis">
 *                 <sequence>
 *                   <element name="uhrzeit" type="{http://xpsw.domap.de/xpsw2505}UhrzeitPersonenstandswesen"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="totgeburt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="totgeburtAngaben" type="{http://xpsw.domap.de/xpsw2505}Anz2StA.Totgeburt" minOccurs="0"/>
 *         <element name="kind" type="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.Kind"/>
 *         <element name="mutter">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element name="standard">
 *                     <complexType>
 *                       <complexContent>
 *                         <extension base="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.Elternteil.Basis">
 *                           <sequence>
 *                             <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *                             <element name="anschrift" type="{http://xpsw.domap.de/xpsw2505}Anschrift.Inland"/>
 *                             <element name="kontakt" type="{http://www.osci.de/xinneres/kommunikation/5}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
 *                           </sequence>
 *                         </extension>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                   <element name="vertraulich">
 *                     <complexType>
 *                       <complexContent>
 *                         <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           <sequence>
 *                             <element name="vornamen" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                             <element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *                           </sequence>
 *                         </restriction>
 *                       </complexContent>
 *                     </complexType>
 *                   </element>
 *                 </choice>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="elternteil2" type="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.Elternteil.Basis" minOccurs="0"/>
 *         <element name="vertraulicheGeburt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="mehrlingsgeburt" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://xpsw.domap.de/xpsw2505}Statistik.Mehrlingsgeburt">
 *                 <sequence>
 *                   <element name="anzahlKnaben" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   <element name="anzahlMaedchen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                   <element name="anzahlUnbestimmt" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="zuordnungGeburtsanzeige" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anz2StA.Template.Geburtsanzeige", propOrder = {
    "nameEinrichtung",
    "geburtsangaben",
    "totgeburt",
    "totgeburtAngaben",
    "kind",
    "mutter",
    "elternteil2",
    "vertraulicheGeburt",
    "mehrlingsgeburt",
    "zuordnungGeburtsanzeige"
})
@XmlSeeAlso({
    Portal2StAGeburt081120 .class,
    Portal2StAGeburt081020 .class
})
public abstract class Anz2StATemplateGeburtsanzeige
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected String nameEinrichtung;
    @XmlElement(required = true)
    protected Anz2StATemplateGeburtsanzeige.Geburtsangaben geburtsangaben;
    protected Boolean totgeburt;
    protected Anz2StATotgeburt totgeburtAngaben;
    @XmlElement(required = true)
    protected Anz2StAGeburtKind kind;
    @XmlElement(required = true)
    protected Anz2StATemplateGeburtsanzeige.Mutter mutter;
    protected Anz2StAGeburtElternteilBasis elternteil2;
    protected Boolean vertraulicheGeburt;
    protected Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt mehrlingsgeburt;
    protected String zuordnungGeburtsanzeige;

    /**
     * Gets the value of the nameEinrichtung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameEinrichtung() {
        return nameEinrichtung;
    }

    /**
     * Sets the value of the nameEinrichtung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameEinrichtung(String value) {
        this.nameEinrichtung = value;
    }

    /**
     * Gets the value of the geburtsangaben property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StATemplateGeburtsanzeige.Geburtsangaben }
     *     
     */
    public Anz2StATemplateGeburtsanzeige.Geburtsangaben getGeburtsangaben() {
        return geburtsangaben;
    }

    /**
     * Sets the value of the geburtsangaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StATemplateGeburtsanzeige.Geburtsangaben }
     *     
     */
    public void setGeburtsangaben(Anz2StATemplateGeburtsanzeige.Geburtsangaben value) {
        this.geburtsangaben = value;
    }

    /**
     * Gets the value of the totgeburt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTotgeburt() {
        return totgeburt;
    }

    /**
     * Sets the value of the totgeburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTotgeburt(Boolean value) {
        this.totgeburt = value;
    }

    /**
     * Gets the value of the totgeburtAngaben property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StATotgeburt }
     *     
     */
    public Anz2StATotgeburt getTotgeburtAngaben() {
        return totgeburtAngaben;
    }

    /**
     * Sets the value of the totgeburtAngaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StATotgeburt }
     *     
     */
    public void setTotgeburtAngaben(Anz2StATotgeburt value) {
        this.totgeburtAngaben = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StAGeburtKind }
     *     
     */
    public Anz2StAGeburtKind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StAGeburtKind }
     *     
     */
    public void setKind(Anz2StAGeburtKind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the mutter property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StATemplateGeburtsanzeige.Mutter }
     *     
     */
    public Anz2StATemplateGeburtsanzeige.Mutter getMutter() {
        return mutter;
    }

    /**
     * Sets the value of the mutter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StATemplateGeburtsanzeige.Mutter }
     *     
     */
    public void setMutter(Anz2StATemplateGeburtsanzeige.Mutter value) {
        this.mutter = value;
    }

    /**
     * Gets the value of the elternteil2 property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StAGeburtElternteilBasis }
     *     
     */
    public Anz2StAGeburtElternteilBasis getElternteil2() {
        return elternteil2;
    }

    /**
     * Sets the value of the elternteil2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StAGeburtElternteilBasis }
     *     
     */
    public void setElternteil2(Anz2StAGeburtElternteilBasis value) {
        this.elternteil2 = value;
    }

    /**
     * Gets the value of the vertraulicheGeburt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVertraulicheGeburt() {
        return vertraulicheGeburt;
    }

    /**
     * Sets the value of the vertraulicheGeburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVertraulicheGeburt(Boolean value) {
        this.vertraulicheGeburt = value;
    }

    /**
     * Gets the value of the mehrlingsgeburt property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt }
     *     
     */
    public Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt getMehrlingsgeburt() {
        return mehrlingsgeburt;
    }

    /**
     * Sets the value of the mehrlingsgeburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt }
     *     
     */
    public void setMehrlingsgeburt(Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt value) {
        this.mehrlingsgeburt = value;
    }

    /**
     * Gets the value of the zuordnungGeburtsanzeige property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZuordnungGeburtsanzeige() {
        return zuordnungGeburtsanzeige;
    }

    /**
     * Sets the value of the zuordnungGeburtsanzeige property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZuordnungGeburtsanzeige(String value) {
        this.zuordnungGeburtsanzeige = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.AngabenEreignis">
     *       <sequence>
     *         <element name="uhrzeit" type="{http://xpsw.domap.de/xpsw2505}UhrzeitPersonenstandswesen"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uhrzeit"
    })
    public static class Geburtsangaben
        extends Anz2StAGeburtAngabenEreignis
    {

        @XmlElement(required = true)
        protected String uhrzeit;

        /**
         * Gets the value of the uhrzeit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUhrzeit() {
            return uhrzeit;
        }

        /**
         * Sets the value of the uhrzeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUhrzeit(String value) {
            this.uhrzeit = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://xpsw.domap.de/xpsw2505}Statistik.Mehrlingsgeburt">
     *       <sequence>
     *         <element name="anzahlKnaben" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         <element name="anzahlMaedchen" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *         <element name="anzahlUnbestimmt" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Mehrlingsgeburt
        extends StatistikMehrlingsgeburt
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element name="standard">
     *           <complexType>
     *             <complexContent>
     *               <extension base="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.Elternteil.Basis">
     *                 <sequence>
     *                   <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
     *                   <element name="anschrift" type="{http://xpsw.domap.de/xpsw2505}Anschrift.Inland"/>
     *                   <element name="kontakt" type="{http://www.osci.de/xinneres/kommunikation/5}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
     *                 </sequence>
     *               </extension>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *         <element name="vertraulich">
     *           <complexType>
     *             <complexContent>
     *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 <sequence>
     *                   <element name="vornamen" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                   <element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
     *                 </sequence>
     *               </restriction>
     *             </complexContent>
     *           </complexType>
     *         </element>
     *       </choice>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "standard",
        "vertraulich"
    })
    public static class Mutter {

        protected Anz2StATemplateGeburtsanzeige.Mutter.Standard standard;
        protected Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich vertraulich;

        /**
         * Gets the value of the standard property.
         * 
         * @return
         *     possible object is
         *     {@link Anz2StATemplateGeburtsanzeige.Mutter.Standard }
         *     
         */
        public Anz2StATemplateGeburtsanzeige.Mutter.Standard getStandard() {
            return standard;
        }

        /**
         * Sets the value of the standard property.
         * 
         * @param value
         *     allowed object is
         *     {@link Anz2StATemplateGeburtsanzeige.Mutter.Standard }
         *     
         */
        public void setStandard(Anz2StATemplateGeburtsanzeige.Mutter.Standard value) {
            this.standard = value;
        }

        /**
         * Gets the value of the vertraulich property.
         * 
         * @return
         *     possible object is
         *     {@link Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich }
         *     
         */
        public Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich getVertraulich() {
            return vertraulich;
        }

        /**
         * Sets the value of the vertraulich property.
         * 
         * @param value
         *     allowed object is
         *     {@link Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich }
         *     
         */
        public void setVertraulich(Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich value) {
            this.vertraulich = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <extension base="{http://xpsw.domap.de/xpsw2505}Anz2StA.Geburt.Elternteil.Basis">
         *       <sequence>
         *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
         *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2505}Anschrift.Inland"/>
         *         <element name="kontakt" type="{http://www.osci.de/xinneres/kommunikation/5}Kommunikation" maxOccurs="unbounded" minOccurs="0"/>
         *       </sequence>
         *     </extension>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "geburtsdatum",
            "anschrift",
            "kontakt"
        })
        public static class Standard
            extends Anz2StAGeburtElternteilBasis
        {

            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar geburtsdatum;
            @XmlElement(required = true)
            protected AnschriftInland anschrift;
            protected List<Kommunikation> kontakt;

            /**
             * Gets the value of the geburtsdatum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGeburtsdatum() {
                return geburtsdatum;
            }

            /**
             * Sets the value of the geburtsdatum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGeburtsdatum(XMLGregorianCalendar value) {
                this.geburtsdatum = value;
            }

            /**
             * Gets the value of the anschrift property.
             * 
             * @return
             *     possible object is
             *     {@link AnschriftInland }
             *     
             */
            public AnschriftInland getAnschrift() {
                return anschrift;
            }

            /**
             * Sets the value of the anschrift property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnschriftInland }
             *     
             */
            public void setAnschrift(AnschriftInland value) {
                this.anschrift = value;
            }

            /**
             * Gets the value of the kontakt property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a {@code set} method for the kontakt property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKontakt().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Kommunikation }
             * 
             * 
             * @return
             *     The value of the kontakt property.
             */
            public List<Kommunikation> getKontakt() {
                if (kontakt == null) {
                    kontakt = new ArrayList<>();
                }
                return this.kontakt;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>{@code
         * <complexType>
         *   <complexContent>
         *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       <sequence>
         *         <element name="vornamen" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *         <element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
         *       </sequence>
         *     </restriction>
         *   </complexContent>
         * </complexType>
         * }</pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vornamen",
            "familienname"
        })
        public static class Vertraulich {

            @XmlElement(required = true)
            protected String vornamen;
            @XmlElement(required = true)
            protected String familienname;

            /**
             * Gets the value of the vornamen property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVornamen() {
                return vornamen;
            }

            /**
             * Sets the value of the vornamen property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVornamen(String value) {
                this.vornamen = value;
            }

            /**
             * Gets the value of the familienname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFamilienname() {
                return familienname;
            }

            /**
             * Sets the value of the familienname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFamilienname(String value) {
                this.familienname = value;
            }

        }

    }

}
