//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Mit diesem Datentyp werden Angaben zu einem Kind im Rahmen einer Namenserklärung im Geburtenregister übermittelt.
 * 
 * <p>Java class for Erk2StA.Kind complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Erk2StA.Kind">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namen" type="{http://xpsw.domap.de/xpsw2505}PersonName"/>
 *         <element name="geburt" type="{http://xpsw.domap.de/xpsw2505}Geburt"/>
 *         <element name="staatsangehoerigkeit" type="{http://xpsw.domap.de/xpsw2505}Code.Staatsangehoerigkeit" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2505}Anschrift.InlandAusland"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Erk2StA.Kind", propOrder = {
    "namen",
    "geburt",
    "staatsangehoerigkeit",
    "anschrift"
})
public class Erk2StAKind {

    @XmlElement(required = true)
    protected PersonName namen;
    @XmlElement(required = true)
    protected Geburt geburt;
    protected List<CodeStaatsangehoerigkeit> staatsangehoerigkeit;
    @XmlElement(required = true)
    protected AnschriftInlandAusland anschrift;

    /**
     * Gets the value of the namen property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNamen() {
        return namen;
    }

    /**
     * Sets the value of the namen property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNamen(PersonName value) {
        this.namen = value;
    }

    /**
     * Gets the value of the geburt property.
     * 
     * @return
     *     possible object is
     *     {@link Geburt }
     *     
     */
    public Geburt getGeburt() {
        return geburt;
    }

    /**
     * Sets the value of the geburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Geburt }
     *     
     */
    public void setGeburt(Geburt value) {
        this.geburt = value;
    }

    /**
     * Gets the value of the staatsangehoerigkeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the staatsangehoerigkeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStaatsangehoerigkeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeStaatsangehoerigkeit }
     * 
     * 
     * @return
     *     The value of the staatsangehoerigkeit property.
     */
    public List<CodeStaatsangehoerigkeit> getStaatsangehoerigkeit() {
        if (staatsangehoerigkeit == null) {
            staatsangehoerigkeit = new ArrayList<>();
        }
        return this.staatsangehoerigkeit;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public AnschriftInlandAusland getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public void setAnschrift(AnschriftInlandAusland value) {
        this.anschrift = value;
    }

}
