//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import de.osci.xinneres.basisnachricht._6.IdentifikationEreignis;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Diese abstrakte Klasse bildet die XPersonenstand-weite Basis für alle Nachrichten. Gegenüber dem Datentyp Nachricht.G2G enthält sie zusätzliche Informationen, um Rückfragen des Empfängers schneller bearbeiten zu können.
 * 
 * <p>Java class for Nachricht.G2GXP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Nachricht.G2GXP">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2505}Nachricht.G2G">
 *       <sequence>
 *         <element name="ansprechpartner" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="vorgangsidentifikation" type="{http://www.osci.de/xinneres/basisnachricht/6}Identifikation.Ereignis" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nachricht.G2GXP", propOrder = {
    "ansprechpartner",
    "vorgangsidentifikation"
})
@XmlSeeAlso({
    NachrichtStA2StA.class,
    Portal2StASterbefall084040 .class,
    Portal2StASterbefall084025 .class,
    Portal2StASterbefall084021 .class,
    Portal2StASterbefall084020 .class,
    Portal2StAEhe082060 .class,
    Portal2StAGeburt081070 .class,
    Portal2StAGeburt081060 .class,
    Portal2StAGeburt081025 .class,
    Portal2StAGeburt081022 .class,
    Portal2StAGeburt081021 .class,
    Anz2StATemplateGeburtsanzeige.class
})
public abstract class NachrichtG2GXP
    extends NachrichtG2G
{

    protected String ansprechpartner;
    protected IdentifikationEreignis vorgangsidentifikation;

    /**
     * Gets the value of the ansprechpartner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnsprechpartner() {
        return ansprechpartner;
    }

    /**
     * Sets the value of the ansprechpartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnsprechpartner(String value) {
        this.ansprechpartner = value;
    }

    /**
     * Gets the value of the vorgangsidentifikation property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationEreignis }
     *     
     */
    public IdentifikationEreignis getVorgangsidentifikation() {
        return vorgangsidentifikation;
    }

    /**
     * Sets the value of the vorgangsidentifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationEreignis }
     *     
     */
    public void setVorgangsidentifikation(IdentifikationEreignis value) {
        this.vorgangsidentifikation = value;
    }

}
