//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.domap.xpsw.xpsw2505 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.domap.xpsw.xpsw2505
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081010 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081010 }
     */
    public Portal2StAGeburt081010 createPortal2StAGeburt081010() {
        return new Portal2StAGeburt081010();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081021 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081021 }
     */
    public Portal2StAGeburt081021 createPortal2StAGeburt081021() {
        return new Portal2StAGeburt081021();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 }
     */
    public Portal2StAGeburt081025 createPortal2StAGeburt081025() {
        return new Portal2StAGeburt081025();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081030 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081030 }
     */
    public Portal2StAGeburt081030 createPortal2StAGeburt081030() {
        return new Portal2StAGeburt081030();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081031 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081031 }
     */
    public Portal2StAGeburt081031 createPortal2StAGeburt081031() {
        return new Portal2StAGeburt081031();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081032 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081032 }
     */
    public Portal2StAGeburt081032 createPortal2StAGeburt081032() {
        return new Portal2StAGeburt081032();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081070 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081070 }
     */
    public Portal2StAGeburt081070 createPortal2StAGeburt081070() {
        return new Portal2StAGeburt081070();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082025 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082025 }
     */
    public Portal2StAEhe082025 createPortal2StAEhe082025() {
        return new Portal2StAEhe082025();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082030 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082030 }
     */
    public Portal2StAEhe082030 createPortal2StAEhe082030() {
        return new Portal2StAEhe082030();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082031 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082031 }
     */
    public Portal2StAEhe082031 createPortal2StAEhe082031() {
        return new Portal2StAEhe082031();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082032 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082032 }
     */
    public Portal2StAEhe082032 createPortal2StAEhe082032() {
        return new Portal2StAEhe082032();
    }

    /**
     * Create an instance of {@link Portal2StALP083030 }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083030 }
     */
    public Portal2StALP083030 createPortal2StALP083030() {
        return new Portal2StALP083030();
    }

    /**
     * Create an instance of {@link Portal2StALP083031 }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083031 }
     */
    public Portal2StALP083031 createPortal2StALP083031() {
        return new Portal2StALP083031();
    }

    /**
     * Create an instance of {@link Portal2StALP083032 }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083032 }
     */
    public Portal2StALP083032 createPortal2StALP083032() {
        return new Portal2StALP083032();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 }
     */
    public Portal2StASterbefall084010 createPortal2StASterbefall084010() {
        return new Portal2StASterbefall084010();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084020 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084020 }
     */
    public Portal2StASterbefall084020 createPortal2StASterbefall084020() {
        return new Portal2StASterbefall084020();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 }
     */
    public Portal2StASterbefall084021 createPortal2StASterbefall084021() {
        return new Portal2StASterbefall084021();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084025 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084025 }
     */
    public Portal2StASterbefall084025 createPortal2StASterbefall084025() {
        return new Portal2StASterbefall084025();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084030 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084030 }
     */
    public Portal2StASterbefall084030 createPortal2StASterbefall084030() {
        return new Portal2StASterbefall084030();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084032 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084032 }
     */
    public Portal2StASterbefall084032 createPortal2StASterbefall084032() {
        return new Portal2StASterbefall084032();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen }
     */
    public UrkundenanforderungZahlungsinformationen createUrkundenanforderungZahlungsinformationen() {
        return new UrkundenanforderungZahlungsinformationen();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart }
     */
    public UrkundenanforderungZahlungsinformationen.Zahlungsart createUrkundenanforderungZahlungsinformationenZahlungsart() {
        return new UrkundenanforderungZahlungsinformationen.Zahlungsart();
    }

    /**
     * Create an instance of {@link BescheinigungsanforderungZahlungsinformationen }
     * 
     * @return
     *     the new instance of {@link BescheinigungsanforderungZahlungsinformationen }
     */
    public BescheinigungsanforderungZahlungsinformationen createBescheinigungsanforderungZahlungsinformationen() {
        return new BescheinigungsanforderungZahlungsinformationen();
    }

    /**
     * Create an instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart }
     * 
     * @return
     *     the new instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart }
     */
    public BescheinigungsanforderungZahlungsinformationen.Zahlungsart createBescheinigungsanforderungZahlungsinformationenZahlungsart() {
        return new BescheinigungsanforderungZahlungsinformationen.Zahlungsart();
    }

    /**
     * Create an instance of {@link TodesbescheinigungSterbefall }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungSterbefall }
     */
    public TodesbescheinigungSterbefall createTodesbescheinigungSterbefall() {
        return new TodesbescheinigungSterbefall();
    }

    /**
     * Create an instance of {@link TodesbescheinigungSterbefall.Todestag }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungSterbefall.Todestag }
     */
    public TodesbescheinigungSterbefall.Todestag createTodesbescheinigungSterbefallTodestag() {
        return new TodesbescheinigungSterbefall.Todestag();
    }

    /**
     * Create an instance of {@link Anz2StAEheVerstorbenerErweitert }
     * 
     * @return
     *     the new instance of {@link Anz2StAEheVerstorbenerErweitert }
     */
    public Anz2StAEheVerstorbenerErweitert createAnz2StAEheVerstorbenerErweitert() {
        return new Anz2StAEheVerstorbenerErweitert();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 .Anzeigender }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 .Anzeigender }
     */
    public Portal2StASterbefall084021 .Anzeigender createPortal2StASterbefall084021Anzeigender() {
        return new Portal2StASterbefall084021 .Anzeigender();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084020 .Anzeigender }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084020 .Anzeigender }
     */
    public Portal2StASterbefall084020 .Anzeigender createPortal2StASterbefall084020Anzeigender() {
        return new Portal2StASterbefall084020 .Anzeigender();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall }
     */
    public Portal2StASterbefall createPortal2StASterbefall() {
        return new Portal2StASterbefall();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall.Todestag }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall.Todestag }
     */
    public Portal2StASterbefall.Todestag createPortal2StASterbefallTodestag() {
        return new Portal2StASterbefall.Todestag();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .InnerTodestag }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .InnerTodestag }
     */
    public Portal2StASterbefall084010 .InnerTodestag createPortal2StASterbefall084010InnerTodestag() {
        return new Portal2StASterbefall084010 .InnerTodestag();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081070 .Kind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081070 .Kind }
     */
    public Portal2StAGeburt081070 .Kind createPortal2StAGeburt081070Kind() {
        return new Portal2StAGeburt081070 .Kind();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081070 .Kind.Geburt }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081070 .Kind.Geburt }
     */
    public Portal2StAGeburt081070 .Kind.Geburt createPortal2StAGeburt081070KindGeburt() {
        return new Portal2StAGeburt081070 .Kind.Geburt();
    }

    /**
     * Create an instance of {@link Portal2StAGeburtNachbeurkundungKind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburtNachbeurkundungKind }
     */
    public Portal2StAGeburtNachbeurkundungKind createPortal2StAGeburtNachbeurkundungKind() {
        return new Portal2StAGeburtNachbeurkundungKind();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter }
     */
    public de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter createAnz2StATemplateGeburtsanzeigeMutter() {
        return new de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter();
    }

    /**
     * Create an instance of {@link Anz2StAEreignisortDetail }
     * 
     * @return
     *     the new instance of {@link Anz2StAEreignisortDetail }
     */
    public Anz2StAEreignisortDetail createAnz2StAEreignisortDetail() {
        return new Anz2StAEreignisortDetail();
    }

    /**
     * Create an instance of {@link Anz2StAMutter }
     * 
     * @return
     *     the new instance of {@link Anz2StAMutter }
     */
    public Anz2StAMutter createAnz2StAMutter() {
        return new Anz2StAMutter();
    }

    /**
     * Create an instance of {@link Anz2StAElternteil }
     * 
     * @return
     *     the new instance of {@link Anz2StAElternteil }
     */
    public Anz2StAElternteil createAnz2StAElternteil() {
        return new Anz2StAElternteil();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081010 .EheDerEltern }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081010 .EheDerEltern }
     */
    public Portal2StAGeburt081010 .EheDerEltern createPortal2StAGeburt081010EheDerEltern() {
        return new Portal2StAGeburt081010 .EheDerEltern();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081010 .Mehrlingsgeburt }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081010 .Mehrlingsgeburt }
     */
    public Portal2StAGeburt081010 .Mehrlingsgeburt createPortal2StAGeburt081010Mehrlingsgeburt() {
        return new Portal2StAGeburt081010 .Mehrlingsgeburt();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081010 .ZahlDerUrkunden }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081010 .ZahlDerUrkunden }
     */
    public Portal2StAGeburt081010 .ZahlDerUrkunden createPortal2StAGeburt081010ZahlDerUrkunden() {
        return new Portal2StAGeburt081010 .ZahlDerUrkunden();
    }

    /**
     * Create an instance of {@link AnhangInhalt }
     * 
     * @return
     *     the new instance of {@link AnhangInhalt }
     */
    public AnhangInhalt createAnhangInhalt() {
        return new AnhangInhalt();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081020 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081020 }
     */
    public Portal2StAGeburt081020 createPortal2StAGeburt081020() {
        return new Portal2StAGeburt081020();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Geburtsangaben }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Geburtsangaben }
     */
    public de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Geburtsangaben createAnz2StATemplateGeburtsanzeigeGeburtsangaben() {
        return new de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Geburtsangaben();
    }

    /**
     * Create an instance of {@link Anz2StATotgeburt }
     * 
     * @return
     *     the new instance of {@link Anz2StATotgeburt }
     */
    public Anz2StATotgeburt createAnz2StATotgeburt() {
        return new Anz2StATotgeburt();
    }

    /**
     * Create an instance of {@link Anz2StAGeburtKind }
     * 
     * @return
     *     the new instance of {@link Anz2StAGeburtKind }
     */
    public Anz2StAGeburtKind createAnz2StAGeburtKind() {
        return new Anz2StAGeburtKind();
    }

    /**
     * Create an instance of {@link Anz2StAGeburtElternteilBasis }
     * 
     * @return
     *     the new instance of {@link Anz2StAGeburtElternteilBasis }
     */
    public Anz2StAGeburtElternteilBasis createAnz2StAGeburtElternteilBasis() {
        return new Anz2StAGeburtElternteilBasis();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt }
     */
    public de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt createAnz2StATemplateGeburtsanzeigeMehrlingsgeburt() {
        return new de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mehrlingsgeburt();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081021 .Geburtsangaben }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081021 .Geburtsangaben }
     */
    public Portal2StAGeburt081021 .Geburtsangaben createPortal2StAGeburt081021Geburtsangaben() {
        return new Portal2StAGeburt081021 .Geburtsangaben();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081021 .Mutter }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081021 .Mutter }
     */
    public Portal2StAGeburt081021 .Mutter createPortal2StAGeburt081021Mutter() {
        return new Portal2StAGeburt081021 .Mutter();
    }

    /**
     * Create an instance of {@link Anz2StAGeburtElternteilErweitert }
     * 
     * @return
     *     the new instance of {@link Anz2StAGeburtElternteilErweitert }
     */
    public Anz2StAGeburtElternteilErweitert createAnz2StAGeburtElternteilErweitert() {
        return new Anz2StAGeburtElternteilErweitert();
    }

    /**
     * Create an instance of {@link Anz2StAGeburtAngabenEhe }
     * 
     * @return
     *     the new instance of {@link Anz2StAGeburtAngabenEhe }
     */
    public Anz2StAGeburtAngabenEhe createAnz2StAGeburtAngabenEhe() {
        return new Anz2StAGeburtAngabenEhe();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081021 .VorangegangenesKind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081021 .VorangegangenesKind }
     */
    public Portal2StAGeburt081021 .VorangegangenesKind createPortal2StAGeburt081021VorangegangenesKind() {
        return new Portal2StAGeburt081021 .VorangegangenesKind();
    }

    /**
     * Create an instance of {@link UrkundenanforderungArtDerUrkundeBasis }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungArtDerUrkundeBasis }
     */
    public UrkundenanforderungArtDerUrkundeBasis createUrkundenanforderungArtDerUrkundeBasis() {
        return new UrkundenanforderungArtDerUrkundeBasis();
    }

    /**
     * Create an instance of {@link Portal2StAZahlungsinformation }
     * 
     * @return
     *     the new instance of {@link Portal2StAZahlungsinformation }
     */
    public Portal2StAZahlungsinformation createPortal2StAZahlungsinformation() {
        return new Portal2StAZahlungsinformation();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081022 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081022 }
     */
    public Portal2StAGeburt081022 createPortal2StAGeburt081022() {
        return new Portal2StAGeburt081022();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     * @return
     *     the new instance of {@link PersonName }
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 .Antragsteller }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 .Antragsteller }
     */
    public Portal2StAGeburt081025 .Antragsteller createPortal2StAGeburt081025Antragsteller() {
        return new Portal2StAGeburt081025 .Antragsteller();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 .Geburtsangaben }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 .Geburtsangaben }
     */
    public Portal2StAGeburt081025 .Geburtsangaben createPortal2StAGeburt081025Geburtsangaben() {
        return new Portal2StAGeburt081025 .Geburtsangaben();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 .Mutter }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 .Mutter }
     */
    public Portal2StAGeburt081025 .Mutter createPortal2StAGeburt081025Mutter() {
        return new Portal2StAGeburt081025 .Mutter();
    }

    /**
     * Create an instance of {@link Portal2StAGeburtNachbeurkundungElternteil }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburtNachbeurkundungElternteil }
     */
    public Portal2StAGeburtNachbeurkundungElternteil createPortal2StAGeburtNachbeurkundungElternteil() {
        return new Portal2StAGeburtNachbeurkundungElternteil();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 .EheDerEltern }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 .EheDerEltern }
     */
    public Portal2StAGeburt081025 .EheDerEltern createPortal2StAGeburt081025EheDerEltern() {
        return new Portal2StAGeburt081025 .EheDerEltern();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081025 .Geschwisterkinder }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081025 .Geschwisterkinder }
     */
    public Portal2StAGeburt081025 .Geschwisterkinder createPortal2StAGeburt081025Geschwisterkinder() {
        return new Portal2StAGeburt081025 .Geschwisterkinder();
    }

    /**
     * Create an instance of {@link UrkundenanforderungArtDerUrkundeErweitert }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungArtDerUrkundeErweitert }
     */
    public UrkundenanforderungArtDerUrkundeErweitert createUrkundenanforderungArtDerUrkundeErweitert() {
        return new UrkundenanforderungArtDerUrkundeErweitert();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAntragssteller }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAntragssteller }
     */
    public UrkundenanforderungAntragssteller createUrkundenanforderungAntragssteller() {
        return new UrkundenanforderungAntragssteller();
    }

    /**
     * Create an instance of {@link UrkundenanforderungModalitaeten }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungModalitaeten }
     */
    public UrkundenanforderungModalitaeten createUrkundenanforderungModalitaeten() {
        return new UrkundenanforderungModalitaeten();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckGeburtsurkunde }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckGeburtsurkunde }
     */
    public CodeVerwendungszweckGeburtsurkunde createCodeVerwendungszweckGeburtsurkunde() {
        return new CodeVerwendungszweckGeburtsurkunde();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081030 .Kind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081030 .Kind }
     */
    public Portal2StAGeburt081030 .Kind createPortal2StAGeburt081030Kind() {
        return new Portal2StAGeburt081030 .Kind();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung }
     */
    public UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung createUrkundenanforderungAntragstellerNatuerlichePersonBescheinigung() {
        return new UrkundenanforderungAntragstellerNatuerlichePersonBescheinigung();
    }

    /**
     * Create an instance of {@link BescheinigungsanforderungModalitaeten }
     * 
     * @return
     *     the new instance of {@link BescheinigungsanforderungModalitaeten }
     */
    public BescheinigungsanforderungModalitaeten createBescheinigungsanforderungModalitaeten() {
        return new BescheinigungsanforderungModalitaeten();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081031 .Kind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081031 .Kind }
     */
    public Portal2StAGeburt081031 .Kind createPortal2StAGeburt081031Kind() {
        return new Portal2StAGeburt081031 .Kind();
    }

    /**
     * Create an instance of {@link UrkundenanforderungArtDerBescheinigungG }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungArtDerBescheinigungG }
     */
    public UrkundenanforderungArtDerBescheinigungG createUrkundenanforderungArtDerBescheinigungG() {
        return new UrkundenanforderungArtDerBescheinigungG();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAntragstellerNatuerlichePersonPersonenstandsbescheinigung }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAntragstellerNatuerlichePersonPersonenstandsbescheinigung }
     */
    public UrkundenanforderungAntragstellerNatuerlichePersonPersonenstandsbescheinigung createUrkundenanforderungAntragstellerNatuerlichePersonPersonenstandsbescheinigung() {
        return new UrkundenanforderungAntragstellerNatuerlichePersonPersonenstandsbescheinigung();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081032 .Kind }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081032 .Kind }
     */
    public Portal2StAGeburt081032 .Kind createPortal2StAGeburt081032Kind() {
        return new Portal2StAGeburt081032 .Kind();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081033 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081033 }
     */
    public Portal2StAGeburt081033 createPortal2StAGeburt081033() {
        return new Portal2StAGeburt081033();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081060 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081060 }
     */
    public Portal2StAGeburt081060 createPortal2StAGeburt081060() {
        return new Portal2StAGeburt081060();
    }

    /**
     * Create an instance of {@link Erk2StABeteiligterGeburt }
     * 
     * @return
     *     the new instance of {@link Erk2StABeteiligterGeburt }
     */
    public Erk2StABeteiligterGeburt createErk2StABeteiligterGeburt() {
        return new Erk2StABeteiligterGeburt();
    }

    /**
     * Create an instance of {@link Erk2StANeuerEhegatte }
     * 
     * @return
     *     the new instance of {@link Erk2StANeuerEhegatte }
     */
    public Erk2StANeuerEhegatte createErk2StANeuerEhegatte() {
        return new Erk2StANeuerEhegatte();
    }

    /**
     * Create an instance of {@link Erk2StAKind }
     * 
     * @return
     *     the new instance of {@link Erk2StAKind }
     */
    public Erk2StAKind createErk2StAKind() {
        return new Erk2StAKind();
    }

    /**
     * Create an instance of {@link Erk2StAEhename }
     * 
     * @return
     *     the new instance of {@link Erk2StAEhename }
     */
    public Erk2StAEhename createErk2StAEhename() {
        return new Erk2StAEhename();
    }

    /**
     * Create an instance of {@link Erk2StAErklaerungGeburt }
     * 
     * @return
     *     the new instance of {@link Erk2StAErklaerungGeburt }
     */
    public Erk2StAErklaerungGeburt createErk2StAErklaerungGeburt() {
        return new Erk2StAErklaerungGeburt();
    }

    /**
     * Create an instance of {@link Erk2StAVAElternteil }
     * 
     * @return
     *     the new instance of {@link Erk2StAVAElternteil }
     */
    public Erk2StAVAElternteil createErk2StAVAElternteil() {
        return new Erk2StAVAElternteil();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081070 .Elternteil1 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081070 .Elternteil1 }
     */
    public Portal2StAGeburt081070 .Elternteil1 createPortal2StAGeburt081070Elternteil1() {
        return new Portal2StAGeburt081070 .Elternteil1();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081120 }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081120 }
     */
    public Portal2StAGeburt081120 createPortal2StAGeburt081120() {
        return new Portal2StAGeburt081120();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082020 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082020 }
     */
    public Portal2StAEhe082020 createPortal2StAEhe082020() {
        return new Portal2StAEhe082020();
    }

    /**
     * Create an instance of {@link Anm2StAAngabenEheschliessende }
     * 
     * @return
     *     the new instance of {@link Anm2StAAngabenEheschliessende }
     */
    public Anm2StAAngabenEheschliessende createAnm2StAAngabenEheschliessende() {
        return new Anm2StAAngabenEheschliessende();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082021 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082021 }
     */
    public Portal2StAEhe082021 createPortal2StAEhe082021() {
        return new Portal2StAEhe082021();
    }

    /**
     * Create an instance of {@link Anm2StAAngabenEheschliessendeAnmeldung }
     * 
     * @return
     *     the new instance of {@link Anm2StAAngabenEheschliessendeAnmeldung }
     */
    public Anm2StAAngabenEheschliessendeAnmeldung createAnm2StAAngabenEheschliessendeAnmeldung() {
        return new Anm2StAAngabenEheschliessendeAnmeldung();
    }

    /**
     * Create an instance of {@link Anm2StAArtDerBescheinigung }
     * 
     * @return
     *     the new instance of {@link Anm2StAArtDerBescheinigung }
     */
    public Anm2StAArtDerBescheinigung createAnm2StAArtDerBescheinigung() {
        return new Anm2StAArtDerBescheinigung();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082022 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082022 }
     */
    public Portal2StAEhe082022 createPortal2StAEhe082022() {
        return new Portal2StAEhe082022();
    }

    /**
     * Create an instance of {@link Anm2StAAngabenEheschliessendeEFZ }
     * 
     * @return
     *     the new instance of {@link Anm2StAAngabenEheschliessendeEFZ }
     */
    public Anm2StAAngabenEheschliessendeEFZ createAnm2StAAngabenEheschliessendeEFZ() {
        return new Anm2StAAngabenEheschliessendeEFZ();
    }

    /**
     * Create an instance of {@link Portal2StAAngabenEheschliessendeNachbeurkundung }
     * 
     * @return
     *     the new instance of {@link Portal2StAAngabenEheschliessendeNachbeurkundung }
     */
    public Portal2StAAngabenEheschliessendeNachbeurkundung createPortal2StAAngabenEheschliessendeNachbeurkundung() {
        return new Portal2StAAngabenEheschliessendeNachbeurkundung();
    }

    /**
     * Create an instance of {@link Anm2StAAngabenKinder }
     * 
     * @return
     *     the new instance of {@link Anm2StAAngabenKinder }
     */
    public Anm2StAAngabenKinder createAnm2StAAngabenKinder() {
        return new Anm2StAAngabenKinder();
    }

    /**
     * Create an instance of {@link Portal2StAEreignis }
     * 
     * @return
     *     the new instance of {@link Portal2StAEreignis }
     */
    public Portal2StAEreignis createPortal2StAEreignis() {
        return new Portal2StAEreignis();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082025 .Namensfuehrung }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082025 .Namensfuehrung }
     */
    public Portal2StAEhe082025 .Namensfuehrung createPortal2StAEhe082025Namensfuehrung() {
        return new Portal2StAEhe082025 .Namensfuehrung();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckEheurkunde }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckEheurkunde }
     */
    public CodeVerwendungszweckEheurkunde createCodeVerwendungszweckEheurkunde() {
        return new CodeVerwendungszweckEheurkunde();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082030 .BeurkundeteEhe }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082030 .BeurkundeteEhe }
     */
    public Portal2StAEhe082030 .BeurkundeteEhe createPortal2StAEhe082030BeurkundeteEhe() {
        return new Portal2StAEhe082030 .BeurkundeteEhe();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082031 .BeurkundeteEhe }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082031 .BeurkundeteEhe }
     */
    public Portal2StAEhe082031 .BeurkundeteEhe createPortal2StAEhe082031BeurkundeteEhe() {
        return new Portal2StAEhe082031 .BeurkundeteEhe();
    }

    /**
     * Create an instance of {@link UrkundenanforderungArtDerBescheinigungE }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungArtDerBescheinigungE }
     */
    public UrkundenanforderungArtDerBescheinigungE createUrkundenanforderungArtDerBescheinigungE() {
        return new UrkundenanforderungArtDerBescheinigungE();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082032 .BeurkundeteEhe }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082032 .BeurkundeteEhe }
     */
    public Portal2StAEhe082032 .BeurkundeteEhe createPortal2StAEhe082032BeurkundeteEhe() {
        return new Portal2StAEhe082032 .BeurkundeteEhe();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082033 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082033 }
     */
    public Portal2StAEhe082033 createPortal2StAEhe082033() {
        return new Portal2StAEhe082033();
    }

    /**
     * Create an instance of {@link Portal2StAEhe082060 }
     * 
     * @return
     *     the new instance of {@link Portal2StAEhe082060 }
     */
    public Portal2StAEhe082060 createPortal2StAEhe082060() {
        return new Portal2StAEhe082060();
    }

    /**
     * Create an instance of {@link Erk2StABeteiligterEhe }
     * 
     * @return
     *     the new instance of {@link Erk2StABeteiligterEhe }
     */
    public Erk2StABeteiligterEhe createErk2StABeteiligterEhe() {
        return new Erk2StABeteiligterEhe();
    }

    /**
     * Create an instance of {@link Erk2StAErklaerungEhe }
     * 
     * @return
     *     the new instance of {@link Erk2StAErklaerungEhe }
     */
    public Erk2StAErklaerungEhe createErk2StAErklaerungEhe() {
        return new Erk2StAErklaerungEhe();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckLPurkunde }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckLPurkunde }
     */
    public CodeVerwendungszweckLPurkunde createCodeVerwendungszweckLPurkunde() {
        return new CodeVerwendungszweckLPurkunde();
    }

    /**
     * Create an instance of {@link Portal2StALP083030 .BeurkundeteLP }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083030 .BeurkundeteLP }
     */
    public Portal2StALP083030 .BeurkundeteLP createPortal2StALP083030BeurkundeteLP() {
        return new Portal2StALP083030 .BeurkundeteLP();
    }

    /**
     * Create an instance of {@link Portal2StALP083031 .BeurkundeteLP }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083031 .BeurkundeteLP }
     */
    public Portal2StALP083031 .BeurkundeteLP createPortal2StALP083031BeurkundeteLP() {
        return new Portal2StALP083031 .BeurkundeteLP();
    }

    /**
     * Create an instance of {@link UrkundenanforderungArtDerBescheinigungL }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungArtDerBescheinigungL }
     */
    public UrkundenanforderungArtDerBescheinigungL createUrkundenanforderungArtDerBescheinigungL() {
        return new UrkundenanforderungArtDerBescheinigungL();
    }

    /**
     * Create an instance of {@link Portal2StALP083032 .BeurkundeteLP }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083032 .BeurkundeteLP }
     */
    public Portal2StALP083032 .BeurkundeteLP createPortal2StALP083032BeurkundeteLP() {
        return new Portal2StALP083032 .BeurkundeteLP();
    }

    /**
     * Create an instance of {@link Portal2StALP083033 }
     * 
     * @return
     *     the new instance of {@link Portal2StALP083033 }
     */
    public Portal2StALP083033 createPortal2StALP083033() {
        return new Portal2StALP083033();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .Verstorbener }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .Verstorbener }
     */
    public Portal2StASterbefall084010 .Verstorbener createPortal2StASterbefall084010Verstorbener() {
        return new Portal2StASterbefall084010 .Verstorbener();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .PartnerDesVerstorbenen }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .PartnerDesVerstorbenen }
     */
    public Portal2StASterbefall084010 .PartnerDesVerstorbenen createPortal2StASterbefall084010PartnerDesVerstorbenen() {
        return new Portal2StASterbefall084010 .PartnerDesVerstorbenen();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .Auskunftsgeber }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .Auskunftsgeber }
     */
    public Portal2StASterbefall084010 .Auskunftsgeber createPortal2StASterbefall084010Auskunftsgeber() {
        return new Portal2StASterbefall084010 .Auskunftsgeber();
    }

    /**
     * Create an instance of {@link CodeBestattungsart }
     * 
     * @return
     *     the new instance of {@link CodeBestattungsart }
     */
    public CodeBestattungsart createCodeBestattungsart() {
        return new CodeBestattungsart();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .ZahlDerUrkunden }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .ZahlDerUrkunden }
     */
    public Portal2StASterbefall084010 .ZahlDerUrkunden createPortal2StASterbefall084010ZahlDerUrkunden() {
        return new Portal2StASterbefall084010 .ZahlDerUrkunden();
    }

    /**
     * Create an instance of {@link Anz2StAEheVerstorbener }
     * 
     * @return
     *     the new instance of {@link Anz2StAEheVerstorbener }
     */
    public Anz2StAEheVerstorbener createAnz2StAEheVerstorbener() {
        return new Anz2StAEheVerstorbener();
    }

    /**
     * Create an instance of {@link Anz2StAAufloesungEheLPVerstorbener }
     * 
     * @return
     *     the new instance of {@link Anz2StAAufloesungEheLPVerstorbener }
     */
    public Anz2StAAufloesungEheLPVerstorbener createAnz2StAAufloesungEheLPVerstorbener() {
        return new Anz2StAAufloesungEheLPVerstorbener();
    }

    /**
     * Create an instance of {@link Portal2StASterbefallVerstorbenerEinrichtung }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefallVerstorbenerEinrichtung }
     */
    public Portal2StASterbefallVerstorbenerEinrichtung createPortal2StASterbefallVerstorbenerEinrichtung() {
        return new Portal2StASterbefallVerstorbenerEinrichtung();
    }

    /**
     * Create an instance of {@link Portal2StASterbefallVerstorbenerBestatter }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefallVerstorbenerBestatter }
     */
    public Portal2StASterbefallVerstorbenerBestatter createPortal2StASterbefallVerstorbenerBestatter() {
        return new Portal2StASterbefallVerstorbenerBestatter();
    }

    /**
     * Create an instance of {@link Portal2StASterbefallVerstorbenerPartnerBestatter }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefallVerstorbenerPartnerBestatter }
     */
    public Portal2StASterbefallVerstorbenerPartnerBestatter createPortal2StASterbefallVerstorbenerPartnerBestatter() {
        return new Portal2StASterbefallVerstorbenerPartnerBestatter();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 .Auskunftsgeber }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 .Auskunftsgeber }
     */
    public Portal2StASterbefall084021 .Auskunftsgeber createPortal2StASterbefall084021Auskunftsgeber() {
        return new Portal2StASterbefall084021 .Auskunftsgeber();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 .VolljaehrigeKinder }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 .VolljaehrigeKinder }
     */
    public Portal2StASterbefall084021 .VolljaehrigeKinder createPortal2StASterbefall084021VolljaehrigeKinder() {
        return new Portal2StASterbefall084021 .VolljaehrigeKinder();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 .MinderjaehrigeKinder }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 .MinderjaehrigeKinder }
     */
    public Portal2StASterbefall084021 .MinderjaehrigeKinder createPortal2StASterbefall084021MinderjaehrigeKinder() {
        return new Portal2StASterbefall084021 .MinderjaehrigeKinder();
    }

    /**
     * Create an instance of {@link Portal2StASterbefallVerstorbenerNachbeurkundung }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefallVerstorbenerNachbeurkundung }
     */
    public Portal2StASterbefallVerstorbenerNachbeurkundung createPortal2StASterbefallVerstorbenerNachbeurkundung() {
        return new Portal2StASterbefallVerstorbenerNachbeurkundung();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084025 .VolljaehrigeKinder }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084025 .VolljaehrigeKinder }
     */
    public Portal2StASterbefall084025 .VolljaehrigeKinder createPortal2StASterbefall084025VolljaehrigeKinder() {
        return new Portal2StASterbefall084025 .VolljaehrigeKinder();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084025 .MinderjaehrigeKinder }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084025 .MinderjaehrigeKinder }
     */
    public Portal2StASterbefall084025 .MinderjaehrigeKinder createPortal2StASterbefall084025MinderjaehrigeKinder() {
        return new Portal2StASterbefall084025 .MinderjaehrigeKinder();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckSterbeurkunde }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckSterbeurkunde }
     */
    public CodeVerwendungszweckSterbeurkunde createCodeVerwendungszweckSterbeurkunde() {
        return new CodeVerwendungszweckSterbeurkunde();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084030 .BeurkundeterSterbefall }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084030 .BeurkundeterSterbefall }
     */
    public Portal2StASterbefall084030 .BeurkundeterSterbefall createPortal2StASterbefall084030BeurkundeterSterbefall() {
        return new Portal2StASterbefall084030 .BeurkundeterSterbefall();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084032 .BeurkundeterSterbefall }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084032 .BeurkundeterSterbefall }
     */
    public Portal2StASterbefall084032 .BeurkundeterSterbefall createPortal2StASterbefall084032BeurkundeterSterbefall() {
        return new Portal2StASterbefall084032 .BeurkundeterSterbefall();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084033 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084033 }
     */
    public Portal2StASterbefall084033 createPortal2StASterbefall084033() {
        return new Portal2StASterbefall084033();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084040 }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084040 }
     */
    public Portal2StASterbefall084040 createPortal2StASterbefall084040() {
        return new Portal2StASterbefall084040();
    }

    /**
     * Create an instance of {@link TodesbescheinigungVerstorbener }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungVerstorbener }
     */
    public TodesbescheinigungVerstorbener createTodesbescheinigungVerstorbener() {
        return new TodesbescheinigungVerstorbener();
    }

    /**
     * Create an instance of {@link TodesbescheinigungLeichenschau }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungLeichenschau }
     */
    public TodesbescheinigungLeichenschau createTodesbescheinigungLeichenschau() {
        return new TodesbescheinigungLeichenschau();
    }

    /**
     * Create an instance of {@link CodeAGS }
     * 
     * @return
     *     the new instance of {@link CodeAGS }
     */
    public CodeAGS createCodeAGS() {
        return new CodeAGS();
    }

    /**
     * Create an instance of {@link CodeAGSCode }
     * 
     * @return
     *     the new instance of {@link CodeAGSCode }
     */
    public CodeAGSCode createCodeAGSCode() {
        return new CodeAGSCode();
    }

    /**
     * Create an instance of {@link CodeArtErklaerungEhe }
     * 
     * @return
     *     the new instance of {@link CodeArtErklaerungEhe }
     */
    public CodeArtErklaerungEhe createCodeArtErklaerungEhe() {
        return new CodeArtErklaerungEhe();
    }

    /**
     * Create an instance of {@link CodeArtErklaerungEheCode }
     * 
     * @return
     *     the new instance of {@link CodeArtErklaerungEheCode }
     */
    public CodeArtErklaerungEheCode createCodeArtErklaerungEheCode() {
        return new CodeArtErklaerungEheCode();
    }

    /**
     * Create an instance of {@link CodeArtNameWiederannahme }
     * 
     * @return
     *     the new instance of {@link CodeArtNameWiederannahme }
     */
    public CodeArtNameWiederannahme createCodeArtNameWiederannahme() {
        return new CodeArtNameWiederannahme();
    }

    /**
     * Create an instance of {@link CodeArtNameWiederannahmeCode }
     * 
     * @return
     *     the new instance of {@link CodeArtNameWiederannahmeCode }
     */
    public CodeArtNameWiederannahmeCode createCodeArtNameWiederannahmeCode() {
        return new CodeArtNameWiederannahmeCode();
    }

    /**
     * Create an instance of {@link CodeAufenthaltsrecht }
     * 
     * @return
     *     the new instance of {@link CodeAufenthaltsrecht }
     */
    public CodeAufenthaltsrecht createCodeAufenthaltsrecht() {
        return new CodeAufenthaltsrecht();
    }

    /**
     * Create an instance of {@link CodeAufenthaltsrechtCode }
     * 
     * @return
     *     the new instance of {@link CodeAufenthaltsrechtCode }
     */
    public CodeAufenthaltsrechtCode createCodeAufenthaltsrechtCode() {
        return new CodeAufenthaltsrechtCode();
    }

    /**
     * Create an instance of {@link CodeAufenthaltsstatus }
     * 
     * @return
     *     the new instance of {@link CodeAufenthaltsstatus }
     */
    public CodeAufenthaltsstatus createCodeAufenthaltsstatus() {
        return new CodeAufenthaltsstatus();
    }

    /**
     * Create an instance of {@link CodeAufenthaltsstatusCode }
     * 
     * @return
     *     the new instance of {@link CodeAufenthaltsstatusCode }
     */
    public CodeAufenthaltsstatusCode createCodeAufenthaltsstatusCode() {
        return new CodeAufenthaltsstatusCode();
    }

    /**
     * Create an instance of {@link CodeAusweisartCode }
     * 
     * @return
     *     the new instance of {@link CodeAusweisartCode }
     */
    public CodeAusweisartCode createCodeAusweisartCode() {
        return new CodeAusweisartCode();
    }

    /**
     * Create an instance of {@link CodeBeendigungsgrundFamilienstand }
     * 
     * @return
     *     the new instance of {@link CodeBeendigungsgrundFamilienstand }
     */
    public CodeBeendigungsgrundFamilienstand createCodeBeendigungsgrundFamilienstand() {
        return new CodeBeendigungsgrundFamilienstand();
    }

    /**
     * Create an instance of {@link CodeBeendigungsgrundFamilienstandCode }
     * 
     * @return
     *     the new instance of {@link CodeBeendigungsgrundFamilienstandCode }
     */
    public CodeBeendigungsgrundFamilienstandCode createCodeBeendigungsgrundFamilienstandCode() {
        return new CodeBeendigungsgrundFamilienstandCode();
    }

    /**
     * Create an instance of {@link CodeBeschlussart }
     * 
     * @return
     *     the new instance of {@link CodeBeschlussart }
     */
    public CodeBeschlussart createCodeBeschlussart() {
        return new CodeBeschlussart();
    }

    /**
     * Create an instance of {@link CodeBeschlussartCode }
     * 
     * @return
     *     the new instance of {@link CodeBeschlussartCode }
     */
    public CodeBeschlussartCode createCodeBeschlussartCode() {
        return new CodeBeschlussartCode();
    }

    /**
     * Create an instance of {@link CodeBestattungsartCode }
     * 
     * @return
     *     the new instance of {@link CodeBestattungsartCode }
     */
    public CodeBestattungsartCode createCodeBestattungsartCode() {
        return new CodeBestattungsartCode();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungEheregister }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungEheregister }
     */
    public CodeFamilienrechtlicheBezeichnungEheregister createCodeFamilienrechtlicheBezeichnungEheregister() {
        return new CodeFamilienrechtlicheBezeichnungEheregister();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungEheregisterCode }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungEheregisterCode }
     */
    public CodeFamilienrechtlicheBezeichnungEheregisterCode createCodeFamilienrechtlicheBezeichnungEheregisterCode() {
        return new CodeFamilienrechtlicheBezeichnungEheregisterCode();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungGeburtenregister }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungGeburtenregister }
     */
    public CodeFamilienrechtlicheBezeichnungGeburtenregister createCodeFamilienrechtlicheBezeichnungGeburtenregister() {
        return new CodeFamilienrechtlicheBezeichnungGeburtenregister();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungGeburtenregisterCode }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungGeburtenregisterCode }
     */
    public CodeFamilienrechtlicheBezeichnungGeburtenregisterCode createCodeFamilienrechtlicheBezeichnungGeburtenregisterCode() {
        return new CodeFamilienrechtlicheBezeichnungGeburtenregisterCode();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungLPregister }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungLPregister }
     */
    public CodeFamilienrechtlicheBezeichnungLPregister createCodeFamilienrechtlicheBezeichnungLPregister() {
        return new CodeFamilienrechtlicheBezeichnungLPregister();
    }

    /**
     * Create an instance of {@link CodeFamilienrechtlicheBezeichnungLPregisterCode }
     * 
     * @return
     *     the new instance of {@link CodeFamilienrechtlicheBezeichnungLPregisterCode }
     */
    public CodeFamilienrechtlicheBezeichnungLPregisterCode createCodeFamilienrechtlicheBezeichnungLPregisterCode() {
        return new CodeFamilienrechtlicheBezeichnungLPregisterCode();
    }

    /**
     * Create an instance of {@link CodeFamilienstandMeldewesen }
     * 
     * @return
     *     the new instance of {@link CodeFamilienstandMeldewesen }
     */
    public CodeFamilienstandMeldewesen createCodeFamilienstandMeldewesen() {
        return new CodeFamilienstandMeldewesen();
    }

    /**
     * Create an instance of {@link CodeFamilienstandMeldewesenCode }
     * 
     * @return
     *     the new instance of {@link CodeFamilienstandMeldewesenCode }
     */
    public CodeFamilienstandMeldewesenCode createCodeFamilienstandMeldewesenCode() {
        return new CodeFamilienstandMeldewesenCode();
    }

    /**
     * Create an instance of {@link CodeFamilienstandPersonenstandswesen }
     * 
     * @return
     *     the new instance of {@link CodeFamilienstandPersonenstandswesen }
     */
    public CodeFamilienstandPersonenstandswesen createCodeFamilienstandPersonenstandswesen() {
        return new CodeFamilienstandPersonenstandswesen();
    }

    /**
     * Create an instance of {@link CodeFamilienstandPersonenstandswesenCode }
     * 
     * @return
     *     the new instance of {@link CodeFamilienstandPersonenstandswesenCode }
     */
    public CodeFamilienstandPersonenstandswesenCode createCodeFamilienstandPersonenstandswesenCode() {
        return new CodeFamilienstandPersonenstandswesenCode();
    }

    /**
     * Create an instance of {@link CodeFehlerartCode }
     * 
     * @return
     *     the new instance of {@link CodeFehlerartCode }
     */
    public CodeFehlerartCode createCodeFehlerartCode() {
        return new CodeFehlerartCode();
    }

    /**
     * Create an instance of {@link CodeFehlerartEGSCode }
     * 
     * @return
     *     the new instance of {@link CodeFehlerartEGSCode }
     */
    public CodeFehlerartEGSCode createCodeFehlerartEGSCode() {
        return new CodeFehlerartEGSCode();
    }

    /**
     * Create an instance of {@link CodeIdentifizierungsart }
     * 
     * @return
     *     the new instance of {@link CodeIdentifizierungsart }
     */
    public CodeIdentifizierungsart createCodeIdentifizierungsart() {
        return new CodeIdentifizierungsart();
    }

    /**
     * Create an instance of {@link CodeIdentifizierungsartCode }
     * 
     * @return
     *     the new instance of {@link CodeIdentifizierungsartCode }
     */
    public CodeIdentifizierungsartCode createCodeIdentifizierungsartCode() {
        return new CodeIdentifizierungsartCode();
    }

    /**
     * Create an instance of {@link CodeNachrichtentyp }
     * 
     * @return
     *     the new instance of {@link CodeNachrichtentyp }
     */
    public CodeNachrichtentyp createCodeNachrichtentyp() {
        return new CodeNachrichtentyp();
    }

    /**
     * Create an instance of {@link CodeNamensart }
     * 
     * @return
     *     the new instance of {@link CodeNamensart }
     */
    public CodeNamensart createCodeNamensart() {
        return new CodeNamensart();
    }

    /**
     * Create an instance of {@link CodeNamensartCode }
     * 
     * @return
     *     the new instance of {@link CodeNamensartCode }
     */
    public CodeNamensartCode createCodeNamensartCode() {
        return new CodeNamensartCode();
    }

    /**
     * Create an instance of {@link CodeNamensfuehrungCode }
     * 
     * @return
     *     the new instance of {@link CodeNamensfuehrungCode }
     */
    public CodeNamensfuehrungCode createCodeNamensfuehrungCode() {
        return new CodeNamensfuehrungCode();
    }

    /**
     * Create an instance of {@link CodePersonenstandsrechtlicherTatbestand }
     * 
     * @return
     *     the new instance of {@link CodePersonenstandsrechtlicherTatbestand }
     */
    public CodePersonenstandsrechtlicherTatbestand createCodePersonenstandsrechtlicherTatbestand() {
        return new CodePersonenstandsrechtlicherTatbestand();
    }

    /**
     * Create an instance of {@link CodePersonenstandsrechtlicherTatbestandCode }
     * 
     * @return
     *     the new instance of {@link CodePersonenstandsrechtlicherTatbestandCode }
     */
    public CodePersonenstandsrechtlicherTatbestandCode createCodePersonenstandsrechtlicherTatbestandCode() {
        return new CodePersonenstandsrechtlicherTatbestandCode();
    }

    /**
     * Create an instance of {@link CodeRechtsgrundlage }
     * 
     * @return
     *     the new instance of {@link CodeRechtsgrundlage }
     */
    public CodeRechtsgrundlage createCodeRechtsgrundlage() {
        return new CodeRechtsgrundlage();
    }

    /**
     * Create an instance of {@link CodeRechtsgrundlageCode }
     * 
     * @return
     *     the new instance of {@link CodeRechtsgrundlageCode }
     */
    public CodeRechtsgrundlageCode createCodeRechtsgrundlageCode() {
        return new CodeRechtsgrundlageCode();
    }

    /**
     * Create an instance of {@link CodeRegisterart }
     * 
     * @return
     *     the new instance of {@link CodeRegisterart }
     */
    public CodeRegisterart createCodeRegisterart() {
        return new CodeRegisterart();
    }

    /**
     * Create an instance of {@link CodeSpracheUebersetzungshilfe }
     * 
     * @return
     *     the new instance of {@link CodeSpracheUebersetzungshilfe }
     */
    public CodeSpracheUebersetzungshilfe createCodeSpracheUebersetzungshilfe() {
        return new CodeSpracheUebersetzungshilfe();
    }

    /**
     * Create an instance of {@link CodeSpracheUebersetzungshilfeCode }
     * 
     * @return
     *     the new instance of {@link CodeSpracheUebersetzungshilfeCode }
     */
    public CodeSpracheUebersetzungshilfeCode createCodeSpracheUebersetzungshilfeCode() {
        return new CodeSpracheUebersetzungshilfeCode();
    }

    /**
     * Create an instance of {@link CodeStaat }
     * 
     * @return
     *     the new instance of {@link CodeStaat }
     */
    public CodeStaat createCodeStaat() {
        return new CodeStaat();
    }

    /**
     * Create an instance of {@link CodeStaatCode }
     * 
     * @return
     *     the new instance of {@link CodeStaatCode }
     */
    public CodeStaatCode createCodeStaatCode() {
        return new CodeStaatCode();
    }

    /**
     * Create an instance of {@link CodeStaatsangehoerigkeit }
     * 
     * @return
     *     the new instance of {@link CodeStaatsangehoerigkeit }
     */
    public CodeStaatsangehoerigkeit createCodeStaatsangehoerigkeit() {
        return new CodeStaatsangehoerigkeit();
    }

    /**
     * Create an instance of {@link CodeStaatsangehoerigkeitCode }
     * 
     * @return
     *     the new instance of {@link CodeStaatsangehoerigkeitCode }
     */
    public CodeStaatsangehoerigkeitCode createCodeStaatsangehoerigkeitCode() {
        return new CodeStaatsangehoerigkeitCode();
    }

    /**
     * Create an instance of {@link CodeStandesamtsnummer }
     * 
     * @return
     *     the new instance of {@link CodeStandesamtsnummer }
     */
    public CodeStandesamtsnummer createCodeStandesamtsnummer() {
        return new CodeStandesamtsnummer();
    }

    /**
     * Create an instance of {@link CodeStandesamtsnummerCode }
     * 
     * @return
     *     the new instance of {@link CodeStandesamtsnummerCode }
     */
    public CodeStandesamtsnummerCode createCodeStandesamtsnummerCode() {
        return new CodeStandesamtsnummerCode();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckEheurkundeCode }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckEheurkundeCode }
     */
    public CodeVerwendungszweckEheurkundeCode createCodeVerwendungszweckEheurkundeCode() {
        return new CodeVerwendungszweckEheurkundeCode();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckGeburtsurkundeCode }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckGeburtsurkundeCode }
     */
    public CodeVerwendungszweckGeburtsurkundeCode createCodeVerwendungszweckGeburtsurkundeCode() {
        return new CodeVerwendungszweckGeburtsurkundeCode();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckLPurkundeCode }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckLPurkundeCode }
     */
    public CodeVerwendungszweckLPurkundeCode createCodeVerwendungszweckLPurkundeCode() {
        return new CodeVerwendungszweckLPurkundeCode();
    }

    /**
     * Create an instance of {@link CodeVerwendungszweckSterbeurkundeCode }
     * 
     * @return
     *     the new instance of {@link CodeVerwendungszweckSterbeurkundeCode }
     */
    public CodeVerwendungszweckSterbeurkundeCode createCodeVerwendungszweckSterbeurkundeCode() {
        return new CodeVerwendungszweckSterbeurkundeCode();
    }

    /**
     * Create an instance of {@link CodeWahlEhename }
     * 
     * @return
     *     the new instance of {@link CodeWahlEhename }
     */
    public CodeWahlEhename createCodeWahlEhename() {
        return new CodeWahlEhename();
    }

    /**
     * Create an instance of {@link CodeWahlEhenameCode }
     * 
     * @return
     *     the new instance of {@link CodeWahlEhenameCode }
     */
    public CodeWahlEhenameCode createCodeWahlEhenameCode() {
        return new CodeWahlEhenameCode();
    }

    /**
     * Create an instance of {@link CodeWahlLPName }
     * 
     * @return
     *     the new instance of {@link CodeWahlLPName }
     */
    public CodeWahlLPName createCodeWahlLPName() {
        return new CodeWahlLPName();
    }

    /**
     * Create an instance of {@link CodeWahlLPNameCode }
     * 
     * @return
     *     the new instance of {@link CodeWahlLPNameCode }
     */
    public CodeWahlLPNameCode createCodeWahlLPNameCode() {
        return new CodeWahlLPNameCode();
    }

    /**
     * Create an instance of {@link AllgemeinerNamePersonenstandswesen }
     * 
     * @return
     *     the new instance of {@link AllgemeinerNamePersonenstandswesen }
     */
    public AllgemeinerNamePersonenstandswesen createAllgemeinerNamePersonenstandswesen() {
        return new AllgemeinerNamePersonenstandswesen();
    }

    /**
     * Create an instance of {@link AnschriftInland }
     * 
     * @return
     *     the new instance of {@link AnschriftInland }
     */
    public AnschriftInland createAnschriftInland() {
        return new AnschriftInland();
    }

    /**
     * Create an instance of {@link AnschriftInlandAusland }
     * 
     * @return
     *     the new instance of {@link AnschriftInlandAusland }
     */
    public AnschriftInlandAusland createAnschriftInlandAusland() {
        return new AnschriftInlandAusland();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Auskunftsgeber }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Auskunftsgeber }
     */
    public de.domap.xpsw.xpsw2505.Auskunftsgeber createAuskunftsgeber() {
        return new de.domap.xpsw.xpsw2505.Auskunftsgeber();
    }

    /**
     * Create an instance of {@link AuskunftsgeberNatuerlichePerson }
     * 
     * @return
     *     the new instance of {@link AuskunftsgeberNatuerlichePerson }
     */
    public AuskunftsgeberNatuerlichePerson createAuskunftsgeberNatuerlichePerson() {
        return new AuskunftsgeberNatuerlichePerson();
    }

    /**
     * Create an instance of {@link AuslandsanschriftStrukturiert }
     * 
     * @return
     *     the new instance of {@link AuslandsanschriftStrukturiert }
     */
    public AuslandsanschriftStrukturiert createAuslandsanschriftStrukturiert() {
        return new AuslandsanschriftStrukturiert();
    }

    /**
     * Create an instance of {@link Behoerdenbezeichnung }
     * 
     * @return
     *     the new instance of {@link Behoerdenbezeichnung }
     */
    public Behoerdenbezeichnung createBehoerdenbezeichnung() {
        return new Behoerdenbezeichnung();
    }

    /**
     * Create an instance of {@link BehoerdenbezeichnungFlexibel }
     * 
     * @return
     *     the new instance of {@link BehoerdenbezeichnungFlexibel }
     */
    public BehoerdenbezeichnungFlexibel createBehoerdenbezeichnungFlexibel() {
        return new BehoerdenbezeichnungFlexibel();
    }

    /**
     * Create an instance of {@link BerichtigungEreignisort }
     * 
     * @return
     *     the new instance of {@link BerichtigungEreignisort }
     */
    public BerichtigungEreignisort createBerichtigungEreignisort() {
        return new BerichtigungEreignisort();
    }

    /**
     * Create an instance of {@link BerichtigungZeitpunkt }
     * 
     * @return
     *     the new instance of {@link BerichtigungZeitpunkt }
     */
    public BerichtigungZeitpunkt createBerichtigungZeitpunkt() {
        return new BerichtigungZeitpunkt();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenQuelleintrag }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenQuelleintrag }
     */
    public BeurkundeteDatenQuelleintrag createBeurkundeteDatenQuelleintrag() {
        return new BeurkundeteDatenQuelleintrag();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenRegistereintrag }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenRegistereintrag }
     */
    public BeurkundeteDatenRegistereintrag createBeurkundeteDatenRegistereintrag() {
        return new BeurkundeteDatenRegistereintrag();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenRegistereintragFlexibel }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenRegistereintragFlexibel }
     */
    public BeurkundeteDatenRegistereintragFlexibel createBeurkundeteDatenRegistereintragFlexibel() {
        return new BeurkundeteDatenRegistereintragFlexibel();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenZeitraumQuelleintrag }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenZeitraumQuelleintrag }
     */
    public BeurkundeteDatenZeitraumQuelleintrag createBeurkundeteDatenZeitraumQuelleintrag() {
        return new BeurkundeteDatenZeitraumQuelleintrag();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenZeitraumRegistereintrag }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenZeitraumRegistereintrag }
     */
    public BeurkundeteDatenZeitraumRegistereintrag createBeurkundeteDatenZeitraumRegistereintrag() {
        return new BeurkundeteDatenZeitraumRegistereintrag();
    }

    /**
     * Create an instance of {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
     * 
     * @return
     *     the new instance of {@link BeurkundeteDatenZeitraumRegistereintragFlexibel }
     */
    public BeurkundeteDatenZeitraumRegistereintragFlexibel createBeurkundeteDatenZeitraumRegistereintragFlexibel() {
        return new BeurkundeteDatenZeitraumRegistereintragFlexibel();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Ehe }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Ehe }
     */
    public de.domap.xpsw.xpsw2505.Ehe createEhe() {
        return new de.domap.xpsw.xpsw2505.Ehe();
    }

    /**
     * Create an instance of {@link Ereignisort }
     * 
     * @return
     *     the new instance of {@link Ereignisort }
     */
    public Ereignisort createEreignisort() {
        return new Ereignisort();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Geburt }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Geburt }
     */
    public de.domap.xpsw.xpsw2505.Geburt createGeburt() {
        return new de.domap.xpsw.xpsw2505.Geburt();
    }

    /**
     * Create an instance of {@link IdentifikationFamilienbuch }
     * 
     * @return
     *     the new instance of {@link IdentifikationFamilienbuch }
     */
    public IdentifikationFamilienbuch createIdentifikationFamilienbuch() {
        return new IdentifikationFamilienbuch();
    }

    /**
     * Create an instance of {@link IdentifikationNachricht }
     * 
     * @return
     *     the new instance of {@link IdentifikationNachricht }
     */
    public IdentifikationNachricht createIdentifikationNachricht() {
        return new IdentifikationNachricht();
    }

    /**
     * Create an instance of {@link IdentifikationZieleintrag }
     * 
     * @return
     *     the new instance of {@link IdentifikationZieleintrag }
     */
    public IdentifikationZieleintrag createIdentifikationZieleintrag() {
        return new IdentifikationZieleintrag();
    }

    /**
     * Create an instance of {@link Nachlass }
     * 
     * @return
     *     the new instance of {@link Nachlass }
     */
    public Nachlass createNachlass() {
        return new Nachlass();
    }

    /**
     * Create an instance of {@link NachrichtenkopfG2G }
     * 
     * @return
     *     the new instance of {@link NachrichtenkopfG2G }
     */
    public NachrichtenkopfG2G createNachrichtenkopfG2G() {
        return new NachrichtenkopfG2G();
    }

    /**
     * Create an instance of {@link Nachweisdaten }
     * 
     * @return
     *     the new instance of {@link Nachweisdaten }
     */
    public Nachweisdaten createNachweisdaten() {
        return new Nachweisdaten();
    }

    /**
     * Create an instance of {@link NachweisdatenTodeserklaerung }
     * 
     * @return
     *     the new instance of {@link NachweisdatenTodeserklaerung }
     */
    public NachweisdatenTodeserklaerung createNachweisdatenTodeserklaerung() {
        return new NachweisdatenTodeserklaerung();
    }

    /**
     * Create an instance of {@link PersonNameAenderung }
     * 
     * @return
     *     the new instance of {@link PersonNameAenderung }
     */
    public PersonNameAenderung createPersonNameAenderung() {
        return new PersonNameAenderung();
    }

    /**
     * Create an instance of {@link PersonNameVeraenderung }
     * 
     * @return
     *     the new instance of {@link PersonNameVeraenderung }
     */
    public PersonNameVeraenderung createPersonNameVeraenderung() {
        return new PersonNameVeraenderung();
    }

    /**
     * Create an instance of {@link Quelleintrag }
     * 
     * @return
     *     the new instance of {@link Quelleintrag }
     */
    public Quelleintrag createQuelleintrag() {
        return new Quelleintrag();
    }

    /**
     * Create an instance of {@link Registereintrag }
     * 
     * @return
     *     the new instance of {@link Registereintrag }
     */
    public Registereintrag createRegistereintrag() {
        return new Registereintrag();
    }

    /**
     * Create an instance of {@link RegistereintragDatenabruf }
     * 
     * @return
     *     the new instance of {@link RegistereintragDatenabruf }
     */
    public RegistereintragDatenabruf createRegistereintragDatenabruf() {
        return new RegistereintragDatenabruf();
    }

    /**
     * Create an instance of {@link RegistereintragFlexibel }
     * 
     * @return
     *     the new instance of {@link RegistereintragFlexibel }
     */
    public RegistereintragFlexibel createRegistereintragFlexibel() {
        return new RegistereintragFlexibel();
    }

    /**
     * Create an instance of {@link StatistikAnschrift }
     * 
     * @return
     *     the new instance of {@link StatistikAnschrift }
     */
    public StatistikAnschrift createStatistikAnschrift() {
        return new StatistikAnschrift();
    }

    /**
     * Create an instance of {@link StatistikHinterbliebener }
     * 
     * @return
     *     the new instance of {@link StatistikHinterbliebener }
     */
    public StatistikHinterbliebener createStatistikHinterbliebener() {
        return new StatistikHinterbliebener();
    }

    /**
     * Create an instance of {@link StatistikKind }
     * 
     * @return
     *     the new instance of {@link StatistikKind }
     */
    public StatistikKind createStatistikKind() {
        return new StatistikKind();
    }

    /**
     * Create an instance of {@link StatistikMutter }
     * 
     * @return
     *     the new instance of {@link StatistikMutter }
     */
    public StatistikMutter createStatistikMutter() {
        return new StatistikMutter();
    }

    /**
     * Create an instance of {@link StatistikPartner }
     * 
     * @return
     *     the new instance of {@link StatistikPartner }
     */
    public StatistikPartner createStatistikPartner() {
        return new StatistikPartner();
    }

    /**
     * Create an instance of {@link StatistikVater }
     * 
     * @return
     *     the new instance of {@link StatistikVater }
     */
    public StatistikVater createStatistikVater() {
        return new StatistikVater();
    }

    /**
     * Create an instance of {@link StatistikVerstorbener }
     * 
     * @return
     *     the new instance of {@link StatistikVerstorbener }
     */
    public StatistikVerstorbener createStatistikVerstorbener() {
        return new StatistikVerstorbener();
    }

    /**
     * Create an instance of {@link Uhrzeit }
     * 
     * @return
     *     the new instance of {@link Uhrzeit }
     */
    public Uhrzeit createUhrzeit() {
        return new Uhrzeit();
    }

    /**
     * Create an instance of {@link UhrzeitPersonenstandswesenMitExakt }
     * 
     * @return
     *     the new instance of {@link UhrzeitPersonenstandswesenMitExakt }
     */
    public UhrzeitPersonenstandswesenMitExakt createUhrzeitPersonenstandswesenMitExakt() {
        return new UhrzeitPersonenstandswesenMitExakt();
    }

    /**
     * Create an instance of {@link Zieleintrag }
     * 
     * @return
     *     the new instance of {@link Zieleintrag }
     */
    public Zieleintrag createZieleintrag() {
        return new Zieleintrag();
    }

    /**
     * Create an instance of {@link Anm2StARegistereintrag }
     * 
     * @return
     *     the new instance of {@link Anm2StARegistereintrag }
     */
    public Anm2StARegistereintrag createAnm2StARegistereintrag() {
        return new Anm2StARegistereintrag();
    }

    /**
     * Create an instance of {@link Anz2StAEreignisort }
     * 
     * @return
     *     the new instance of {@link Anz2StAEreignisort }
     */
    public Anz2StAEreignisort createAnz2StAEreignisort() {
        return new Anz2StAEreignisort();
    }

    /**
     * Create an instance of {@link Anz2StAGeburtAngabenEreignis }
     * 
     * @return
     *     the new instance of {@link Anz2StAGeburtAngabenEreignis }
     */
    public Anz2StAGeburtAngabenEreignis createAnz2StAGeburtAngabenEreignis() {
        return new Anz2StAGeburtAngabenEreignis();
    }

    /**
     * Create an instance of {@link Erk2StABeteiligter }
     * 
     * @return
     *     the new instance of {@link Erk2StABeteiligter }
     */
    public Erk2StABeteiligter createErk2StABeteiligter() {
        return new Erk2StABeteiligter();
    }

    /**
     * Create an instance of {@link Erk2StABeteiligterGesetzlicherVertreter }
     * 
     * @return
     *     the new instance of {@link Erk2StABeteiligterGesetzlicherVertreter }
     */
    public Erk2StABeteiligterGesetzlicherVertreter createErk2StABeteiligterGesetzlicherVertreter() {
        return new Erk2StABeteiligterGesetzlicherVertreter();
    }

    /**
     * Create an instance of {@link Portal2StAAnschrift }
     * 
     * @return
     *     the new instance of {@link Portal2StAAnschrift }
     */
    public Portal2StAAnschrift createPortal2StAAnschrift() {
        return new Portal2StAAnschrift();
    }

    /**
     * Create an instance of {@link Portal2StAAnschriftMitOrt }
     * 
     * @return
     *     the new instance of {@link Portal2StAAnschriftMitOrt }
     */
    public Portal2StAAnschriftMitOrt createPortal2StAAnschriftMitOrt() {
        return new Portal2StAAnschriftMitOrt();
    }

    /**
     * Create an instance of {@link Portal2StARegistereintrag }
     * 
     * @return
     *     the new instance of {@link Portal2StARegistereintrag }
     */
    public Portal2StARegistereintrag createPortal2StARegistereintrag() {
        return new Portal2StARegistereintrag();
    }

    /**
     * Create an instance of {@link Portal2StASterbefallPerson }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefallPerson }
     */
    public Portal2StASterbefallPerson createPortal2StASterbefallPerson() {
        return new Portal2StASterbefallPerson();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAnschriftAntragsteller }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAnschriftAntragsteller }
     */
    public UrkundenanforderungAnschriftAntragsteller createUrkundenanforderungAnschriftAntragsteller() {
        return new UrkundenanforderungAnschriftAntragsteller();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAntragstellerJuristischePerson }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAntragstellerJuristischePerson }
     */
    public UrkundenanforderungAntragstellerJuristischePerson createUrkundenanforderungAntragstellerJuristischePerson() {
        return new UrkundenanforderungAntragstellerJuristischePerson();
    }

    /**
     * Create an instance of {@link UrkundenanforderungAntragstellerNatuerlichePerson }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungAntragstellerNatuerlichePerson }
     */
    public UrkundenanforderungAntragstellerNatuerlichePerson createUrkundenanforderungAntragstellerNatuerlichePerson() {
        return new UrkundenanforderungAntragstellerNatuerlichePerson();
    }

    /**
     * Create an instance of {@link UrkundenanforderungBeurkundetesEreignis }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungBeurkundetesEreignis }
     */
    public UrkundenanforderungBeurkundetesEreignis createUrkundenanforderungBeurkundetesEreignis() {
        return new UrkundenanforderungBeurkundetesEreignis();
    }

    /**
     * Create an instance of {@link UrkundenanforderungUebersetzungshilfe }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungUebersetzungshilfe }
     */
    public UrkundenanforderungUebersetzungshilfe createUrkundenanforderungUebersetzungshilfe() {
        return new UrkundenanforderungUebersetzungshilfe();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen.KostenErstesExemplar }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen.KostenErstesExemplar }
     */
    public UrkundenanforderungZahlungsinformationen.KostenErstesExemplar createUrkundenanforderungZahlungsinformationenKostenErstesExemplar() {
        return new UrkundenanforderungZahlungsinformationen.KostenErstesExemplar();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen.KostenWeiteresExemplar }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen.KostenWeiteresExemplar }
     */
    public UrkundenanforderungZahlungsinformationen.KostenWeiteresExemplar createUrkundenanforderungZahlungsinformationenKostenWeiteresExemplar() {
        return new UrkundenanforderungZahlungsinformationen.KostenWeiteresExemplar();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
     */
    public UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift createUrkundenanforderungZahlungsinformationenZahlungsartLastschrift() {
        return new UrkundenanforderungZahlungsinformationen.Zahlungsart.Lastschrift();
    }

    /**
     * Create an instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
     * 
     * @return
     *     the new instance of {@link UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
     */
    public UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse createUrkundenanforderungZahlungsinformationenZahlungsartVorkasse() {
        return new UrkundenanforderungZahlungsinformationen.Zahlungsart.Vorkasse();
    }

    /**
     * Create an instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
     * 
     * @return
     *     the new instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Lastschrift }
     */
    public BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Lastschrift createBescheinigungsanforderungZahlungsinformationenZahlungsartLastschrift() {
        return new BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Lastschrift();
    }

    /**
     * Create an instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
     * 
     * @return
     *     the new instance of {@link BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Vorkasse }
     */
    public BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Vorkasse createBescheinigungsanforderungZahlungsinformationenZahlungsartVorkasse() {
        return new BescheinigungsanforderungZahlungsinformationen.Zahlungsart.Vorkasse();
    }

    /**
     * Create an instance of {@link TodesbescheinigungSterbefall.Todestag.InnerTodestag }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungSterbefall.Todestag.InnerTodestag }
     */
    public TodesbescheinigungSterbefall.Todestag.InnerTodestag createTodesbescheinigungSterbefallTodestagInnerTodestag() {
        return new TodesbescheinigungSterbefall.Todestag.InnerTodestag();
    }

    /**
     * Create an instance of {@link TodesbescheinigungSterbefall.Todestag.Sterbezeitraum }
     * 
     * @return
     *     the new instance of {@link TodesbescheinigungSterbefall.Todestag.Sterbezeitraum }
     */
    public TodesbescheinigungSterbefall.Todestag.Sterbezeitraum createTodesbescheinigungSterbefallTodestagSterbezeitraum() {
        return new TodesbescheinigungSterbefall.Todestag.Sterbezeitraum();
    }

    /**
     * Create an instance of {@link Anz2StAEheVerstorbenerErweitert.Familienbuch }
     * 
     * @return
     *     the new instance of {@link Anz2StAEheVerstorbenerErweitert.Familienbuch }
     */
    public Anz2StAEheVerstorbenerErweitert.Familienbuch createAnz2StAEheVerstorbenerErweitertFamilienbuch() {
        return new Anz2StAEheVerstorbenerErweitert.Familienbuch();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084021 .Anzeigender.Namen }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084021 .Anzeigender.Namen }
     */
    public Portal2StASterbefall084021 .Anzeigender.Namen createPortal2StASterbefall084021AnzeigenderNamen() {
        return new Portal2StASterbefall084021 .Anzeigender.Namen();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084020 .Anzeigender.Namen }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084020 .Anzeigender.Namen }
     */
    public Portal2StASterbefall084020 .Anzeigender.Namen createPortal2StASterbefall084020AnzeigenderNamen() {
        return new Portal2StASterbefall084020 .Anzeigender.Namen();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall.Sterbeort }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall.Sterbeort }
     */
    public Portal2StASterbefall.Sterbeort createPortal2StASterbefallSterbeort() {
        return new Portal2StASterbefall.Sterbeort();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall.Todestag.InnerTodestag }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall.Todestag.InnerTodestag }
     */
    public Portal2StASterbefall.Todestag.InnerTodestag createPortal2StASterbefallTodestagInnerTodestag() {
        return new Portal2StASterbefall.Todestag.InnerTodestag();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall.Todestag.Sterbezeitraum }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall.Todestag.Sterbezeitraum }
     */
    public Portal2StASterbefall.Todestag.Sterbezeitraum createPortal2StASterbefallTodestagSterbezeitraum() {
        return new Portal2StASterbefall.Todestag.Sterbezeitraum();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .InnerTodestag.Todestag }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .InnerTodestag.Todestag }
     */
    public Portal2StASterbefall084010 .InnerTodestag.Todestag createPortal2StASterbefall084010InnerTodestagTodestag() {
        return new Portal2StASterbefall084010 .InnerTodestag.Todestag();
    }

    /**
     * Create an instance of {@link Portal2StASterbefall084010 .InnerTodestag.Sterbezeitraum }
     * 
     * @return
     *     the new instance of {@link Portal2StASterbefall084010 .InnerTodestag.Sterbezeitraum }
     */
    public Portal2StASterbefall084010 .InnerTodestag.Sterbezeitraum createPortal2StASterbefall084010InnerTodestagSterbezeitraum() {
        return new Portal2StASterbefall084010 .InnerTodestag.Sterbezeitraum();
    }

    /**
     * Create an instance of {@link Portal2StAGeburt081070 .Kind.Geburt.Geburtsangaben }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburt081070 .Kind.Geburt.Geburtsangaben }
     */
    public Portal2StAGeburt081070 .Kind.Geburt.Geburtsangaben createPortal2StAGeburt081070KindGeburtGeburtsangaben() {
        return new Portal2StAGeburt081070 .Kind.Geburt.Geburtsangaben();
    }

    /**
     * Create an instance of {@link Portal2StAGeburtNachbeurkundungKind.Ehe }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburtNachbeurkundungKind.Ehe }
     */
    public Portal2StAGeburtNachbeurkundungKind.Ehe createPortal2StAGeburtNachbeurkundungKindEhe() {
        return new Portal2StAGeburtNachbeurkundungKind.Ehe();
    }

    /**
     * Create an instance of {@link Portal2StAGeburtNachbeurkundungKind.Lp }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburtNachbeurkundungKind.Lp }
     */
    public Portal2StAGeburtNachbeurkundungKind.Lp createPortal2StAGeburtNachbeurkundungKindLp() {
        return new Portal2StAGeburtNachbeurkundungKind.Lp();
    }

    /**
     * Create an instance of {@link Portal2StAGeburtNachbeurkundungKind.Kinder }
     * 
     * @return
     *     the new instance of {@link Portal2StAGeburtNachbeurkundungKind.Kinder }
     */
    public Portal2StAGeburtNachbeurkundungKind.Kinder createPortal2StAGeburtNachbeurkundungKindKinder() {
        return new Portal2StAGeburtNachbeurkundungKind.Kinder();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Standard }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Standard }
     */
    public de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Standard createAnz2StATemplateGeburtsanzeigeMutterStandard() {
        return new de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Standard();
    }

    /**
     * Create an instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich }
     * 
     * @return
     *     the new instance of {@link de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich }
     */
    public de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich createAnz2StATemplateGeburtsanzeigeMutterVertraulich() {
        return new de.domap.xpsw.xpsw2505.Anz2StATemplateGeburtsanzeige.Mutter.Vertraulich();
    }

}
