//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Mit diesem Datentypen können Zahlungsinformationen in Portalnachrichten übermittelt werden.
 * 
 * <p>Java class for Portal2StA.Zahlungsinformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Portal2StA.Zahlungsinformation">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="zahlungErfolgt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="zahlungsreferenz" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Portal2StA.Zahlungsinformation", propOrder = {
    "zahlungErfolgt",
    "zahlungsreferenz"
})
public class Portal2StAZahlungsinformation {

    protected Boolean zahlungErfolgt;
    protected String zahlungsreferenz;

    /**
     * Gets the value of the zahlungErfolgt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZahlungErfolgt() {
        return zahlungErfolgt;
    }

    /**
     * Sets the value of the zahlungErfolgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZahlungErfolgt(Boolean value) {
        this.zahlungErfolgt = value;
    }

    /**
     * Gets the value of the zahlungsreferenz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZahlungsreferenz() {
        return zahlungsreferenz;
    }

    /**
     * Sets the value of the zahlungsreferenz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZahlungsreferenz(String value) {
        this.zahlungsreferenz = value;
    }

}
