//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import java.time.LocalDate;
import com.vertama.xpersonenstand.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Mit diesem Datentyp können Angaben zu Ort und Datum eines Ereignisses übermittelt werden.
 * 
 * <p>Java class for Portal2StA.Ereignis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Portal2StA.Ereignis">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="datum" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *         <element name="ort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="staat" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Portal2StA.Ereignis", propOrder = {
    "datum",
    "ort",
    "staat"
})
public class Portal2StAEreignis {

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate datum;
    @XmlElement(required = true)
    protected String ort;
    protected String staat;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(LocalDate value) {
        this.datum = value;
    }

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

    /**
     * Gets the value of the staat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaat() {
        return staat;
    }

    /**
     * Sets the value of the staat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaat(String value) {
        this.staat = value;
    }

}
