//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2505;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.vertama.xpersonenstand.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2505}Nachricht.G2G">
 *       <sequence>
 *         <element name="angabenEheschliessende" type="{http://xpsw.domap.de/xpsw2505}Anm2StA.AngabenEheschliessende.Anmeldung" maxOccurs="2" minOccurs="2"/>
 *         <element name="anzahlGemeinsamerKinder" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         <element name="wunschtermin" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum" maxOccurs="3" minOccurs="0"/>
 *         <element name="wunschzeit" type="{http://xpsw.domap.de/xpsw2505}UhrzeitPersonenstandswesen" maxOccurs="3" minOccurs="0"/>
 *         <element name="wunschort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="wunschraum" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="gemeinsamerFamilienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="bescheinigungsanforderung" type="{http://xpsw.domap.de/xpsw2505}Anm2StA.ArtDerBescheinigung" minOccurs="0"/>
 *         <element name="bearbeitungsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="anhang" type="{http://xpsw.domap.de/xpsw2505}AnhangInhalt" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "angabenEheschliessende",
    "anzahlGemeinsamerKinder",
    "wunschtermin",
    "wunschzeit",
    "wunschort",
    "wunschraum",
    "gemeinsamerFamilienname",
    "bescheinigungsanforderung",
    "bearbeitungsnummer",
    "anhang"
})
@XmlRootElement(name = "portal2StA.Ehe.082021")
public class Portal2StAEhe082021
    extends NachrichtG2G
{

    @XmlElement(required = true)
    protected List<Anm2StAAngabenEheschliessendeAnmeldung> angabenEheschliessende;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger anzahlGemeinsamerKinder;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected List<LocalDate> wunschtermin;
    protected List<String> wunschzeit;
    protected String wunschort;
    protected String wunschraum;
    protected String gemeinsamerFamilienname;
    protected Anm2StAArtDerBescheinigung bescheinigungsanforderung;
    protected String bearbeitungsnummer;
    protected List<AnhangInhalt> anhang;

    /**
     * Gets the value of the angabenEheschliessende property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the angabenEheschliessende property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAngabenEheschliessende().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Anm2StAAngabenEheschliessendeAnmeldung }
     * 
     * 
     * @return
     *     The value of the angabenEheschliessende property.
     */
    public List<Anm2StAAngabenEheschliessendeAnmeldung> getAngabenEheschliessende() {
        if (angabenEheschliessende == null) {
            angabenEheschliessende = new ArrayList<>();
        }
        return this.angabenEheschliessende;
    }

    /**
     * Gets the value of the anzahlGemeinsamerKinder property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAnzahlGemeinsamerKinder() {
        return anzahlGemeinsamerKinder;
    }

    /**
     * Sets the value of the anzahlGemeinsamerKinder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAnzahlGemeinsamerKinder(BigInteger value) {
        this.anzahlGemeinsamerKinder = value;
    }

    /**
     * Gets the value of the wunschtermin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the wunschtermin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWunschtermin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the wunschtermin property.
     */
    public List<LocalDate> getWunschtermin() {
        if (wunschtermin == null) {
            wunschtermin = new ArrayList<>();
        }
        return this.wunschtermin;
    }

    /**
     * Gets the value of the wunschzeit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the wunschzeit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWunschzeit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     * @return
     *     The value of the wunschzeit property.
     */
    public List<String> getWunschzeit() {
        if (wunschzeit == null) {
            wunschzeit = new ArrayList<>();
        }
        return this.wunschzeit;
    }

    /**
     * Gets the value of the wunschort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWunschort() {
        return wunschort;
    }

    /**
     * Sets the value of the wunschort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWunschort(String value) {
        this.wunschort = value;
    }

    /**
     * Gets the value of the wunschraum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWunschraum() {
        return wunschraum;
    }

    /**
     * Sets the value of the wunschraum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWunschraum(String value) {
        this.wunschraum = value;
    }

    /**
     * Gets the value of the gemeinsamerFamilienname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGemeinsamerFamilienname() {
        return gemeinsamerFamilienname;
    }

    /**
     * Sets the value of the gemeinsamerFamilienname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGemeinsamerFamilienname(String value) {
        this.gemeinsamerFamilienname = value;
    }

    /**
     * Gets the value of the bescheinigungsanforderung property.
     * 
     * @return
     *     possible object is
     *     {@link Anm2StAArtDerBescheinigung }
     *     
     */
    public Anm2StAArtDerBescheinigung getBescheinigungsanforderung() {
        return bescheinigungsanforderung;
    }

    /**
     * Sets the value of the bescheinigungsanforderung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anm2StAArtDerBescheinigung }
     *     
     */
    public void setBescheinigungsanforderung(Anm2StAArtDerBescheinigung value) {
        this.bescheinigungsanforderung = value;
    }

    /**
     * Gets the value of the bearbeitungsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBearbeitungsnummer() {
        return bearbeitungsnummer;
    }

    /**
     * Sets the value of the bearbeitungsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBearbeitungsnummer(String value) {
        this.bearbeitungsnummer = value;
    }

    /**
     * Gets the value of the anhang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anhang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnhang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnhangInhalt }
     * 
     * 
     * @return
     *     The value of the anhang property.
     */
    public List<AnhangInhalt> getAnhang() {
        if (anhang == null) {
            anhang = new ArrayList<>();
        }
        return this.anhang;
    }

}
