//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.time.LocalDate;
import com.vertama.xpersonenstand.adapters.LocalDateAdapter;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Dieser Datentyp dient zur Übermittlung von Angaben zu einem Ereignis im Rahmen einer Anzeige einer Geburt.
 * 
 * <p>Java class for Anz2StA.Geburt.AngabenEreignis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Anz2StA.Geburt.AngabenEreignis">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ort" type="{http://xpsw.domap.de/xpsw2511}Ereignisort"/>
 *         <element name="tag" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anz2StA.Geburt.AngabenEreignis", propOrder = {
    "ort",
    "tag"
})
@XmlSeeAlso({
    de.domap.xpsw.xpsw2511.Anz2StATemplateGeburtsanzeige.Geburtsangaben.class,
    de.domap.xpsw.xpsw2511.Portal2StAGeburt081021 .Geburtsangaben.class,
    de.domap.xpsw.xpsw2511.Portal2StAGeburt081025 .Geburtsangaben.class,
    de.domap.xpsw.xpsw2511.Portal2StAGeburtNachbeurkundungKind.Ehe.class,
    de.domap.xpsw.xpsw2511.Portal2StAGeburtNachbeurkundungKind.Lp.class,
    de.domap.xpsw.xpsw2511.EU2StAGeburt081023 .Geburtsangaben.class
})
public class Anz2StAGeburtAngabenEreignis {

    @XmlElement(required = true)
    protected Ereignisort ort;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate tag;

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setOrt(Ereignisort value) {
        this.ort = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(LocalDate value) {
        this.tag = value;
    }

}
