//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.rueckweisung._6.CodeFehlercodeXInneres;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="ursprungsnachricht" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         <element name="fehler" type="{http://www.osci.de/xinneres/rueckweisung/6}Code.Fehlercode.XInneres"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ursprungsnachricht",
    "fehler"
})
@XmlRootElement(name = "datenabruf2StA.Fehlernachricht.018060")
public class Datenabruf2StAFehlernachricht018060
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected byte[] ursprungsnachricht;
    @XmlElement(required = true)
    protected CodeFehlercodeXInneres fehler;

    /**
     * Gets the value of the ursprungsnachricht property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getUrsprungsnachricht() {
        return ursprungsnachricht;
    }

    /**
     * Sets the value of the ursprungsnachricht property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setUrsprungsnachricht(byte[] value) {
        this.ursprungsnachricht = value;
    }

    /**
     * Gets the value of the fehler property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFehlercodeXInneres }
     *     
     */
    public CodeFehlercodeXInneres getFehler() {
        return fehler;
    }

    /**
     * Sets the value of the fehler property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFehlercodeXInneres }
     *     
     */
    public void setFehler(CodeFehlercodeXInneres value) {
        this.fehler = value;
    }

}
