//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="registerunabhaengigeAngaben" type="{http://xpsw.domap.de/xpsw2511}Datenabruf2StA.Abruf.Allgemeines"/>
 *         <element name="abrufzweck" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="identifikationLPeintrag" type="{http://xpsw.domap.de/xpsw2511}Datenabruf2StA.Eintragsidentifikation.EheLP"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "registerunabhaengigeAngaben",
    "abrufzweck",
    "identifikationLPeintrag"
})
@XmlRootElement(name = "datenabruf2StA.AbrufLP.018030")
public class Datenabruf2StAAbrufLP018030
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected Datenabruf2StAAbrufAllgemeines registerunabhaengigeAngaben;
    @XmlElement(required = true)
    protected String abrufzweck;
    @XmlElement(required = true)
    protected Datenabruf2StAEintragsidentifikationEheLP identifikationLPeintrag;

    /**
     * Gets the value of the registerunabhaengigeAngaben property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAAbrufAllgemeines }
     *     
     */
    public Datenabruf2StAAbrufAllgemeines getRegisterunabhaengigeAngaben() {
        return registerunabhaengigeAngaben;
    }

    /**
     * Sets the value of the registerunabhaengigeAngaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAAbrufAllgemeines }
     *     
     */
    public void setRegisterunabhaengigeAngaben(Datenabruf2StAAbrufAllgemeines value) {
        this.registerunabhaengigeAngaben = value;
    }

    /**
     * Gets the value of the abrufzweck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbrufzweck() {
        return abrufzweck;
    }

    /**
     * Sets the value of the abrufzweck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbrufzweck(String value) {
        this.abrufzweck = value;
    }

    /**
     * Gets the value of the identifikationLPeintrag property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StAEintragsidentifikationEheLP }
     *     
     */
    public Datenabruf2StAEintragsidentifikationEheLP getIdentifikationLPeintrag() {
        return identifikationLPeintrag;
    }

    /**
     * Sets the value of the identifikationLPeintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StAEintragsidentifikationEheLP }
     *     
     */
    public void setIdentifikationLPeintrag(Datenabruf2StAEintragsidentifikationEheLP value) {
        this.identifikationLPeintrag = value;
    }

}
