//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp identifiziert den gesuchten Sterbeeintrag, entweder über die Eintragsnummer oder über die entsprechenden Suchdaten.
 * 
 * <p>Java class for Datenabruf2StA.Eintragsidentifikation.Sterbefall complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Datenabruf2StA.Eintragsidentifikation.Sterbefall">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="eintragsnummer" type="{http://xpsw.domap.de/xpsw2511}Datenabruf2StA.Registernummer"/>
 *         <element name="suchdaten" type="{http://xpsw.domap.de/xpsw2511}Datenabruf2StA.Suchdaten.Sterbefall"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datenabruf2StA.Eintragsidentifikation.Sterbefall", propOrder = {
    "eintragsnummer",
    "suchdaten"
})
public class Datenabruf2StAEintragsidentifikationSterbefall {

    protected Datenabruf2StARegisternummer eintragsnummer;
    protected Datenabruf2StASuchdatenSterbefall suchdaten;

    /**
     * Gets the value of the eintragsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StARegisternummer }
     *     
     */
    public Datenabruf2StARegisternummer getEintragsnummer() {
        return eintragsnummer;
    }

    /**
     * Sets the value of the eintragsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StARegisternummer }
     *     
     */
    public void setEintragsnummer(Datenabruf2StARegisternummer value) {
        this.eintragsnummer = value;
    }

    /**
     * Gets the value of the suchdaten property.
     * 
     * @return
     *     possible object is
     *     {@link Datenabruf2StASuchdatenSterbefall }
     *     
     */
    public Datenabruf2StASuchdatenSterbefall getSuchdaten() {
        return suchdaten;
    }

    /**
     * Sets the value of the suchdaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datenabruf2StASuchdatenSterbefall }
     *     
     */
    public void setSuchdaten(Datenabruf2StASuchdatenSterbefall value) {
        this.suchdaten = value;
    }

}
