//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.math.BigInteger;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import com.vertama.xpersonenstand.adapters.LocalDateAdapter;
import de.osci.xinneres.behoerde._7.BehoerdeMitAnschrift;
import de.xoev.schemata.basisnachricht.unqualified.g2g._1_1.KommunikationType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="geburtsangaben">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.AngabenEreignis">
 *                 <sequence>
 *                   <element name="uhrzeit" type="{http://xpsw.domap.de/xpsw2511}UhrzeitPersonenstandswesen"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="kind" type="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.Kind"/>
 *         <element name="mutter">
 *           <complexType>
 *             <complexContent>
 *               <extension base="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.Elternteil.Erweitert">
 *                 <sequence>
 *                   <element name="anzahlTotgeburten" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *                   <element name="geburtsdatumVorherigesKind" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum" minOccurs="0"/>
 *                   <element name="anzahlKinder" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                 </sequence>
 *               </extension>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="elternteil2" type="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.Elternteil.Erweitert" minOccurs="0"/>
 *         <element name="elternVerheiratet" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="ehe" type="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.AngabenEhe" minOccurs="0"/>
 *         <element name="vorangegangenesKind" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <sequence>
 *                   <element name="namen" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *                   <element name="geburt" type="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.AngabenEreignis"/>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="kontaktdaten" type="{http://xoev.de/schemata/basisnachricht/unqualified/g2g/1_1}KommunikationType" maxOccurs="unbounded"/>
 *         <element name="urkundenbestellung" type="{http://xpsw.domap.de/xpsw2511}Urkundenanforderung.ArtDerUrkunde.Basis"/>
 *         <element name="zahlungsinformation" type="{http://xpsw.domap.de/xpsw2511}Portal2StA.Zahlungsinformation" minOccurs="0"/>
 *         <element name="auftragsnummer" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="zuordnungGeburtsanzeige" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="zustimmungElterngeldstelle" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="zustaendigeElterngeldstelle" type="{http://www.osci.de/xinneres/behoerde/7}BehoerdeMitAnschrift" minOccurs="0"/>
 *         <element name="anhang" type="{http://xpsw.domap.de/xpsw2511}AnhangInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geburtsangaben",
    "kind",
    "mutter",
    "elternteil2",
    "elternVerheiratet",
    "ehe",
    "vorangegangenesKind",
    "kontaktdaten",
    "urkundenbestellung",
    "zahlungsinformation",
    "auftragsnummer",
    "zuordnungGeburtsanzeige",
    "zustimmungElterngeldstelle",
    "zustaendigeElterngeldstelle",
    "anhang"
})
@XmlRootElement(name = "portal2StA.Geburt.081021")
public class Portal2StAGeburt081021
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected Portal2StAGeburt081021 .Geburtsangaben geburtsangaben;
    @XmlElement(required = true)
    protected Anz2StAGeburtKind kind;
    @XmlElement(required = true)
    protected Portal2StAGeburt081021 .Mutter mutter;
    protected Anz2StAGeburtElternteilErweitert elternteil2;
    protected Boolean elternVerheiratet;
    protected Anz2StAGeburtAngabenEhe ehe;
    protected Portal2StAGeburt081021 .VorangegangenesKind vorangegangenesKind;
    @XmlElement(required = true)
    protected List<KommunikationType> kontaktdaten;
    @XmlElement(required = true)
    protected UrkundenanforderungArtDerUrkundeBasis urkundenbestellung;
    protected Portal2StAZahlungsinformation zahlungsinformation;
    @XmlElement(required = true)
    protected String auftragsnummer;
    protected String zuordnungGeburtsanzeige;
    protected Boolean zustimmungElterngeldstelle;
    protected BehoerdeMitAnschrift zustaendigeElterngeldstelle;
    protected List<AnhangInformation> anhang;

    /**
     * Gets the value of the geburtsangaben property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StAGeburt081021 .Geburtsangaben }
     *     
     */
    public Portal2StAGeburt081021 .Geburtsangaben getGeburtsangaben() {
        return geburtsangaben;
    }

    /**
     * Sets the value of the geburtsangaben property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StAGeburt081021 .Geburtsangaben }
     *     
     */
    public void setGeburtsangaben(Portal2StAGeburt081021 .Geburtsangaben value) {
        this.geburtsangaben = value;
    }

    /**
     * Gets the value of the kind property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StAGeburtKind }
     *     
     */
    public Anz2StAGeburtKind getKind() {
        return kind;
    }

    /**
     * Sets the value of the kind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StAGeburtKind }
     *     
     */
    public void setKind(Anz2StAGeburtKind value) {
        this.kind = value;
    }

    /**
     * Gets the value of the mutter property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StAGeburt081021 .Mutter }
     *     
     */
    public Portal2StAGeburt081021 .Mutter getMutter() {
        return mutter;
    }

    /**
     * Sets the value of the mutter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StAGeburt081021 .Mutter }
     *     
     */
    public void setMutter(Portal2StAGeburt081021 .Mutter value) {
        this.mutter = value;
    }

    /**
     * Gets the value of the elternteil2 property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StAGeburtElternteilErweitert }
     *     
     */
    public Anz2StAGeburtElternteilErweitert getElternteil2() {
        return elternteil2;
    }

    /**
     * Sets the value of the elternteil2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StAGeburtElternteilErweitert }
     *     
     */
    public void setElternteil2(Anz2StAGeburtElternteilErweitert value) {
        this.elternteil2 = value;
    }

    /**
     * Gets the value of the elternVerheiratet property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isElternVerheiratet() {
        return elternVerheiratet;
    }

    /**
     * Sets the value of the elternVerheiratet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setElternVerheiratet(Boolean value) {
        this.elternVerheiratet = value;
    }

    /**
     * Gets the value of the ehe property.
     * 
     * @return
     *     possible object is
     *     {@link Anz2StAGeburtAngabenEhe }
     *     
     */
    public Anz2StAGeburtAngabenEhe getEhe() {
        return ehe;
    }

    /**
     * Sets the value of the ehe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anz2StAGeburtAngabenEhe }
     *     
     */
    public void setEhe(Anz2StAGeburtAngabenEhe value) {
        this.ehe = value;
    }

    /**
     * Gets the value of the vorangegangenesKind property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StAGeburt081021 .VorangegangenesKind }
     *     
     */
    public Portal2StAGeburt081021 .VorangegangenesKind getVorangegangenesKind() {
        return vorangegangenesKind;
    }

    /**
     * Sets the value of the vorangegangenesKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StAGeburt081021 .VorangegangenesKind }
     *     
     */
    public void setVorangegangenesKind(Portal2StAGeburt081021 .VorangegangenesKind value) {
        this.vorangegangenesKind = value;
    }

    /**
     * Gets the value of the kontaktdaten property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the kontaktdaten property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKontaktdaten().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KommunikationType }
     * 
     * 
     * @return
     *     The value of the kontaktdaten property.
     */
    public List<KommunikationType> getKontaktdaten() {
        if (kontaktdaten == null) {
            kontaktdaten = new ArrayList<>();
        }
        return this.kontaktdaten;
    }

    /**
     * Gets the value of the urkundenbestellung property.
     * 
     * @return
     *     possible object is
     *     {@link UrkundenanforderungArtDerUrkundeBasis }
     *     
     */
    public UrkundenanforderungArtDerUrkundeBasis getUrkundenbestellung() {
        return urkundenbestellung;
    }

    /**
     * Sets the value of the urkundenbestellung property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrkundenanforderungArtDerUrkundeBasis }
     *     
     */
    public void setUrkundenbestellung(UrkundenanforderungArtDerUrkundeBasis value) {
        this.urkundenbestellung = value;
    }

    /**
     * Gets the value of the zahlungsinformation property.
     * 
     * @return
     *     possible object is
     *     {@link Portal2StAZahlungsinformation }
     *     
     */
    public Portal2StAZahlungsinformation getZahlungsinformation() {
        return zahlungsinformation;
    }

    /**
     * Sets the value of the zahlungsinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Portal2StAZahlungsinformation }
     *     
     */
    public void setZahlungsinformation(Portal2StAZahlungsinformation value) {
        this.zahlungsinformation = value;
    }

    /**
     * Gets the value of the auftragsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuftragsnummer() {
        return auftragsnummer;
    }

    /**
     * Sets the value of the auftragsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuftragsnummer(String value) {
        this.auftragsnummer = value;
    }

    /**
     * Gets the value of the zuordnungGeburtsanzeige property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZuordnungGeburtsanzeige() {
        return zuordnungGeburtsanzeige;
    }

    /**
     * Sets the value of the zuordnungGeburtsanzeige property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZuordnungGeburtsanzeige(String value) {
        this.zuordnungGeburtsanzeige = value;
    }

    /**
     * Gets the value of the zustimmungElterngeldstelle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isZustimmungElterngeldstelle() {
        return zustimmungElterngeldstelle;
    }

    /**
     * Sets the value of the zustimmungElterngeldstelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setZustimmungElterngeldstelle(Boolean value) {
        this.zustimmungElterngeldstelle = value;
    }

    /**
     * Gets the value of the zustaendigeElterngeldstelle property.
     * 
     * @return
     *     possible object is
     *     {@link BehoerdeMitAnschrift }
     *     
     */
    public BehoerdeMitAnschrift getZustaendigeElterngeldstelle() {
        return zustaendigeElterngeldstelle;
    }

    /**
     * Sets the value of the zustaendigeElterngeldstelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BehoerdeMitAnschrift }
     *     
     */
    public void setZustaendigeElterngeldstelle(BehoerdeMitAnschrift value) {
        this.zustaendigeElterngeldstelle = value;
    }

    /**
     * Gets the value of the anhang property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anhang property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnhang().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnhangInformation }
     * 
     * 
     * @return
     *     The value of the anhang property.
     */
    public List<AnhangInformation> getAnhang() {
        if (anhang == null) {
            anhang = new ArrayList<>();
        }
        return this.anhang;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.AngabenEreignis">
     *       <sequence>
     *         <element name="uhrzeit" type="{http://xpsw.domap.de/xpsw2511}UhrzeitPersonenstandswesen"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "uhrzeit"
    })
    public static class Geburtsangaben
        extends Anz2StAGeburtAngabenEreignis
    {

        @XmlElement(required = true)
        protected String uhrzeit;

        /**
         * Gets the value of the uhrzeit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUhrzeit() {
            return uhrzeit;
        }

        /**
         * Sets the value of the uhrzeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUhrzeit(String value) {
            this.uhrzeit = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <extension base="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.Elternteil.Erweitert">
     *       <sequence>
     *         <element name="anzahlTotgeburten" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
     *         <element name="geburtsdatumVorherigesKind" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum" minOccurs="0"/>
     *         <element name="anzahlKinder" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *       </sequence>
     *     </extension>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "anzahlTotgeburten",
        "geburtsdatumVorherigesKind",
        "anzahlKinder"
    })
    public static class Mutter
        extends Anz2StAGeburtElternteilErweitert
    {

        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger anzahlTotgeburten;
        @XmlElement(type = String.class)
        @XmlJavaTypeAdapter(LocalDateAdapter.class)
        @XmlSchemaType(name = "date")
        protected LocalDate geburtsdatumVorherigesKind;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger anzahlKinder;

        /**
         * Gets the value of the anzahlTotgeburten property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAnzahlTotgeburten() {
            return anzahlTotgeburten;
        }

        /**
         * Sets the value of the anzahlTotgeburten property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAnzahlTotgeburten(BigInteger value) {
            this.anzahlTotgeburten = value;
        }

        /**
         * Gets the value of the geburtsdatumVorherigesKind property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public LocalDate getGeburtsdatumVorherigesKind() {
            return geburtsdatumVorherigesKind;
        }

        /**
         * Sets the value of the geburtsdatumVorherigesKind property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeburtsdatumVorherigesKind(LocalDate value) {
            this.geburtsdatumVorherigesKind = value;
        }

        /**
         * Gets the value of the anzahlKinder property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAnzahlKinder() {
            return anzahlKinder;
        }

        /**
         * Sets the value of the anzahlKinder property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAnzahlKinder(BigInteger value) {
            this.anzahlKinder = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <sequence>
     *         <element name="namen" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
     *         <element name="geburt" type="{http://xpsw.domap.de/xpsw2511}Anz2StA.Geburt.AngabenEreignis"/>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "namen",
        "geburt"
    })
    public static class VorangegangenesKind {

        @XmlElement(required = true)
        protected PersonName namen;
        @XmlElement(required = true)
        protected Anz2StAGeburtAngabenEreignis geburt;

        /**
         * Gets the value of the namen property.
         * 
         * @return
         *     possible object is
         *     {@link PersonName }
         *     
         */
        public PersonName getNamen() {
            return namen;
        }

        /**
         * Sets the value of the namen property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonName }
         *     
         */
        public void setNamen(PersonName value) {
            this.namen = value;
        }

        /**
         * Gets the value of the geburt property.
         * 
         * @return
         *     possible object is
         *     {@link Anz2StAGeburtAngabenEreignis }
         *     
         */
        public Anz2StAGeburtAngabenEreignis getGeburt() {
            return geburt;
        }

        /**
         * Sets the value of the geburt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Anz2StAGeburtAngabenEreignis }
         *     
         */
        public void setGeburt(Anz2StAGeburtAngabenEreignis value) {
            this.geburt = value;
        }

    }

}
