//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.datum._2.TeilbekanntesDatumMitUnbekannt;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.G2GXP">
 *       <sequence>
 *         <element name="standesamtsnummer" type="{http://xpsw.domap.de/xpsw2511}Code.Standesamtsnummer"/>
 *         <element name="vornamen" type="{http://xpsw.domap.de/xpsw2511}AllgemeinerName.Personenstandswesen"/>
 *         <element name="geburtsnameVorErklaerung" type="{http://xpsw.domap.de/xpsw2511}AllgemeinerName.Personenstandswesen"/>
 *         <element name="geburtsnameNachErklaerung" type="{http://xpsw.domap.de/xpsw2511}AllgemeinerName.Personenstandswesen"/>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatumMitUnbekannt" minOccurs="0"/>
 *         <element name="geburtsort" type="{http://xpsw.domap.de/xpsw2511}Ereignisort" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "standesamtsnummer",
    "vornamen",
    "geburtsnameVorErklaerung",
    "geburtsnameNachErklaerung",
    "geburtsdatum",
    "geburtsort"
})
@XmlRootElement(name = "stA1B.Familienrecht.025010")
public class StA1BFamilienrecht025010
    extends NachrichtG2GXP
{

    @XmlElement(required = true)
    protected CodeStandesamtsnummer standesamtsnummer;
    @XmlElement(required = true)
    protected AllgemeinerNamePersonenstandswesen vornamen;
    @XmlElement(required = true)
    protected AllgemeinerNamePersonenstandswesen geburtsnameVorErklaerung;
    @XmlElement(required = true)
    protected AllgemeinerNamePersonenstandswesen geburtsnameNachErklaerung;
    protected TeilbekanntesDatumMitUnbekannt geburtsdatum;
    protected Ereignisort geburtsort;

    /**
     * Gets the value of the standesamtsnummer property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStandesamtsnummer }
     *     
     */
    public CodeStandesamtsnummer getStandesamtsnummer() {
        return standesamtsnummer;
    }

    /**
     * Sets the value of the standesamtsnummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStandesamtsnummer }
     *     
     */
    public void setStandesamtsnummer(CodeStandesamtsnummer value) {
        this.standesamtsnummer = value;
    }

    /**
     * Gets the value of the vornamen property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public AllgemeinerNamePersonenstandswesen getVornamen() {
        return vornamen;
    }

    /**
     * Sets the value of the vornamen property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public void setVornamen(AllgemeinerNamePersonenstandswesen value) {
        this.vornamen = value;
    }

    /**
     * Gets the value of the geburtsnameVorErklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public AllgemeinerNamePersonenstandswesen getGeburtsnameVorErklaerung() {
        return geburtsnameVorErklaerung;
    }

    /**
     * Sets the value of the geburtsnameVorErklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public void setGeburtsnameVorErklaerung(AllgemeinerNamePersonenstandswesen value) {
        this.geburtsnameVorErklaerung = value;
    }

    /**
     * Gets the value of the geburtsnameNachErklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public AllgemeinerNamePersonenstandswesen getGeburtsnameNachErklaerung() {
        return geburtsnameNachErklaerung;
    }

    /**
     * Sets the value of the geburtsnameNachErklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public void setGeburtsnameNachErklaerung(AllgemeinerNamePersonenstandswesen value) {
        this.geburtsnameNachErklaerung = value;
    }

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public TeilbekanntesDatumMitUnbekannt getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public void setGeburtsdatum(TeilbekanntesDatumMitUnbekannt value) {
        this.geburtsdatum = value;
    }

    /**
     * Gets the value of the geburtsort property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getGeburtsort() {
        return geburtsort;
    }

    /**
     * Sets the value of the geburtsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setGeburtsort(Ereignisort value) {
        this.geburtsort = value;
    }

}
