//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Mit diesem Datentyp werden die benötigten Daten der Eheschließenden, bzw. der Lebenspartner, bei einer Anmeldung zur Eheschließung, bzw. einer Anmeldung zur Begründung einer Lebenspartnerschaft, übermittelt.
 * 
 * <p>Java class for StA2StA.AnmeldedatenPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2StA.AnmeldedatenPerson">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namen" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="familienrechtlicheBezeichnung" type="{http://xpsw.domap.de/xpsw2511}Code.FamilienrechtlicheBezeichnungEheregister"/>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *         <element name="geburtseintrag" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Registereintrag"/>
 *         <element name="fuehrungsort" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="familienstand" type="{http://xpsw.domap.de/xpsw2511}Code.FamilienstandPersonenstandswesen"/>
 *         <element name="staatsangehoerigkeitNachgewiesen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="effektiveStaatsangehoerigkeit" type="{http://xpsw.domap.de/xpsw2511}Code.Staatsangehoerigkeit" minOccurs="0"/>
 *         <element name="weitereStaatsangehoerigkeit" type="{http://xpsw.domap.de/xpsw2511}Code.Staatsangehoerigkeit" minOccurs="0"/>
 *         <element name="sonderstatus" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="anschrift" type="{http://xpsw.domap.de/xpsw2511}Anschrift.InlandAusland"/>
 *         <element name="familienbuch.vorehe" type="{http://xpsw.domap.de/xpsw2511}Identifikation.Familienbuch" minOccurs="0"/>
 *         <element name="letzteVorehe" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Registereintrag" minOccurs="0"/>
 *         <element name="letzteLebenspartnerschaft" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Registereintrag" minOccurs="0"/>
 *         <element name="heimatortSchweiz" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2StA.AnmeldedatenPerson", propOrder = {
    "namen",
    "familienrechtlicheBezeichnung",
    "geschlecht",
    "geburtseintrag",
    "fuehrungsort",
    "familienstand",
    "staatsangehoerigkeitNachgewiesen",
    "effektiveStaatsangehoerigkeit",
    "weitereStaatsangehoerigkeit",
    "sonderstatus",
    "anschrift",
    "familienbuchVorehe",
    "letzteVorehe",
    "letzteLebenspartnerschaft",
    "heimatortSchweiz"
})
public class StA2StAAnmeldedatenPerson {

    @XmlElement(required = true)
    protected PersonName namen;
    @XmlElement(required = true)
    protected CodeFamilienrechtlicheBezeichnungEheregister familienrechtlicheBezeichnung;
    @XmlElement(required = true)
    protected CodeGeschlecht geschlecht;
    @XmlElement(required = true)
    protected BeurkundeteDatenRegistereintrag geburtseintrag;
    protected String fuehrungsort;
    @XmlElement(required = true)
    protected CodeFamilienstandPersonenstandswesen familienstand;
    protected Boolean staatsangehoerigkeitNachgewiesen;
    protected CodeStaatsangehoerigkeit effektiveStaatsangehoerigkeit;
    protected CodeStaatsangehoerigkeit weitereStaatsangehoerigkeit;
    protected String sonderstatus;
    @XmlElement(required = true)
    protected AnschriftInlandAusland anschrift;
    @XmlElement(name = "familienbuch.vorehe")
    protected IdentifikationFamilienbuch familienbuchVorehe;
    protected BeurkundeteDatenRegistereintrag letzteVorehe;
    protected BeurkundeteDatenRegistereintrag letzteLebenspartnerschaft;
    protected String heimatortSchweiz;

    /**
     * Gets the value of the namen property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNamen() {
        return namen;
    }

    /**
     * Sets the value of the namen property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNamen(PersonName value) {
        this.namen = value;
    }

    /**
     * Gets the value of the familienrechtlicheBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFamilienrechtlicheBezeichnungEheregister }
     *     
     */
    public CodeFamilienrechtlicheBezeichnungEheregister getFamilienrechtlicheBezeichnung() {
        return familienrechtlicheBezeichnung;
    }

    /**
     * Sets the value of the familienrechtlicheBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFamilienrechtlicheBezeichnungEheregister }
     *     
     */
    public void setFamilienrechtlicheBezeichnung(CodeFamilienrechtlicheBezeichnungEheregister value) {
        this.familienrechtlicheBezeichnung = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlecht(CodeGeschlecht value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the geburtseintrag property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public BeurkundeteDatenRegistereintrag getGeburtseintrag() {
        return geburtseintrag;
    }

    /**
     * Sets the value of the geburtseintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public void setGeburtseintrag(BeurkundeteDatenRegistereintrag value) {
        this.geburtseintrag = value;
    }

    /**
     * Gets the value of the fuehrungsort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuehrungsort() {
        return fuehrungsort;
    }

    /**
     * Sets the value of the fuehrungsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuehrungsort(String value) {
        this.fuehrungsort = value;
    }

    /**
     * Gets the value of the familienstand property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFamilienstandPersonenstandswesen }
     *     
     */
    public CodeFamilienstandPersonenstandswesen getFamilienstand() {
        return familienstand;
    }

    /**
     * Sets the value of the familienstand property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFamilienstandPersonenstandswesen }
     *     
     */
    public void setFamilienstand(CodeFamilienstandPersonenstandswesen value) {
        this.familienstand = value;
    }

    /**
     * Gets the value of the staatsangehoerigkeitNachgewiesen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStaatsangehoerigkeitNachgewiesen() {
        return staatsangehoerigkeitNachgewiesen;
    }

    /**
     * Sets the value of the staatsangehoerigkeitNachgewiesen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStaatsangehoerigkeitNachgewiesen(Boolean value) {
        this.staatsangehoerigkeitNachgewiesen = value;
    }

    /**
     * Gets the value of the effektiveStaatsangehoerigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public CodeStaatsangehoerigkeit getEffektiveStaatsangehoerigkeit() {
        return effektiveStaatsangehoerigkeit;
    }

    /**
     * Sets the value of the effektiveStaatsangehoerigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public void setEffektiveStaatsangehoerigkeit(CodeStaatsangehoerigkeit value) {
        this.effektiveStaatsangehoerigkeit = value;
    }

    /**
     * Gets the value of the weitereStaatsangehoerigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public CodeStaatsangehoerigkeit getWeitereStaatsangehoerigkeit() {
        return weitereStaatsangehoerigkeit;
    }

    /**
     * Sets the value of the weitereStaatsangehoerigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStaatsangehoerigkeit }
     *     
     */
    public void setWeitereStaatsangehoerigkeit(CodeStaatsangehoerigkeit value) {
        this.weitereStaatsangehoerigkeit = value;
    }

    /**
     * Gets the value of the sonderstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSonderstatus() {
        return sonderstatus;
    }

    /**
     * Sets the value of the sonderstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSonderstatus(String value) {
        this.sonderstatus = value;
    }

    /**
     * Gets the value of the anschrift property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public AnschriftInlandAusland getAnschrift() {
        return anschrift;
    }

    /**
     * Sets the value of the anschrift property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public void setAnschrift(AnschriftInlandAusland value) {
        this.anschrift = value;
    }

    /**
     * Gets the value of the familienbuchVorehe property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifikationFamilienbuch }
     *     
     */
    public IdentifikationFamilienbuch getFamilienbuchVorehe() {
        return familienbuchVorehe;
    }

    /**
     * Sets the value of the familienbuchVorehe property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifikationFamilienbuch }
     *     
     */
    public void setFamilienbuchVorehe(IdentifikationFamilienbuch value) {
        this.familienbuchVorehe = value;
    }

    /**
     * Gets the value of the letzteVorehe property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public BeurkundeteDatenRegistereintrag getLetzteVorehe() {
        return letzteVorehe;
    }

    /**
     * Sets the value of the letzteVorehe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public void setLetzteVorehe(BeurkundeteDatenRegistereintrag value) {
        this.letzteVorehe = value;
    }

    /**
     * Gets the value of the letzteLebenspartnerschaft property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public BeurkundeteDatenRegistereintrag getLetzteLebenspartnerschaft() {
        return letzteLebenspartnerschaft;
    }

    /**
     * Sets the value of the letzteLebenspartnerschaft property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenRegistereintrag }
     *     
     */
    public void setLetzteLebenspartnerschaft(BeurkundeteDatenRegistereintrag value) {
        this.letzteLebenspartnerschaft = value;
    }

    /**
     * Gets the value of the heimatortSchweiz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeimatortSchweiz() {
        return heimatortSchweiz;
    }

    /**
     * Sets the value of the heimatortSchweiz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeimatortSchweiz(String value) {
        this.heimatortSchweiz = value;
    }

}
