//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.time.LocalDate;
import com.vertama.xpersonenstand.adapters.LocalDateAdapter;
import de.osci.xinneres.idnr._2.PlausibilisierteIdentifikationsnummer;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Dieser abstrakte Datentyp dient als Vorlage zur Ableitung von Nachrichten zur Übernahme eines geänderten Lebenspartnerschaftsnamens durch das gemeinsame Kind.
 * 
 * <p>Java class for StA2StA.Familienrecht.Template.LPnamensaenderung.Eltern2Kind complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2StA.Familienrecht.Template.LPnamensaenderung.Eltern2Kind">
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2StA">
 *       <sequence>
 *         <element name="datumDerWirksamkeit" type="{http://www.osci.de/xinneres/datum/2}Tagesdatum"/>
 *         <element name="nameLebenspartner1" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="identifikationsnummerLP1" type="{http://www.osci.de/xinneres/idnr/2}PlausibilisierteIdentifikationsnummer" minOccurs="0"/>
 *         <element name="nameLebenspartner2" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="identifikationsnummerLP2" type="{http://www.osci.de/xinneres/idnr/2}PlausibilisierteIdentifikationsnummer" minOccurs="0"/>
 *         <element name="wahlLPName" type="{http://xpsw.domap.de/xpsw2511}Code.Wahl.LPName"/>
 *         <element name="anschriftDesKindes" type="{http://xpsw.domap.de/xpsw2511}Anschrift.Inland" minOccurs="0"/>
 *         <element name="lebenspartnerschaftsname" type="{http://xpsw.domap.de/xpsw2511}AllgemeinerName.Personenstandswesen"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2StA.Familienrecht.Template.LPnamensaenderung.Eltern2Kind", propOrder = {
    "datumDerWirksamkeit",
    "nameLebenspartner1",
    "identifikationsnummerLP1",
    "nameLebenspartner2",
    "identifikationsnummerLP2",
    "wahlLPName",
    "anschriftDesKindes",
    "lebenspartnerschaftsname"
})
@XmlSeeAlso({
    StA2StAFamilienrecht016070 .class,
    StA2StALP013050 .class
})
public abstract class StA2StAFamilienrechtTemplateLPnamensaenderungEltern2Kind
    extends NachrichtStA2StA
{

    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate datumDerWirksamkeit;
    @XmlElement(required = true)
    protected PersonName nameLebenspartner1;
    protected PlausibilisierteIdentifikationsnummer identifikationsnummerLP1;
    @XmlElement(required = true)
    protected PersonName nameLebenspartner2;
    protected PlausibilisierteIdentifikationsnummer identifikationsnummerLP2;
    @XmlElement(required = true)
    protected CodeWahlLPName wahlLPName;
    protected AnschriftInland anschriftDesKindes;
    @XmlElement(required = true)
    protected AllgemeinerNamePersonenstandswesen lebenspartnerschaftsname;

    /**
     * Gets the value of the datumDerWirksamkeit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getDatumDerWirksamkeit() {
        return datumDerWirksamkeit;
    }

    /**
     * Sets the value of the datumDerWirksamkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatumDerWirksamkeit(LocalDate value) {
        this.datumDerWirksamkeit = value;
    }

    /**
     * Gets the value of the nameLebenspartner1 property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNameLebenspartner1() {
        return nameLebenspartner1;
    }

    /**
     * Sets the value of the nameLebenspartner1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNameLebenspartner1(PersonName value) {
        this.nameLebenspartner1 = value;
    }

    /**
     * Gets the value of the identifikationsnummerLP1 property.
     * 
     * @return
     *     possible object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public PlausibilisierteIdentifikationsnummer getIdentifikationsnummerLP1() {
        return identifikationsnummerLP1;
    }

    /**
     * Sets the value of the identifikationsnummerLP1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public void setIdentifikationsnummerLP1(PlausibilisierteIdentifikationsnummer value) {
        this.identifikationsnummerLP1 = value;
    }

    /**
     * Gets the value of the nameLebenspartner2 property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNameLebenspartner2() {
        return nameLebenspartner2;
    }

    /**
     * Sets the value of the nameLebenspartner2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNameLebenspartner2(PersonName value) {
        this.nameLebenspartner2 = value;
    }

    /**
     * Gets the value of the identifikationsnummerLP2 property.
     * 
     * @return
     *     possible object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public PlausibilisierteIdentifikationsnummer getIdentifikationsnummerLP2() {
        return identifikationsnummerLP2;
    }

    /**
     * Sets the value of the identifikationsnummerLP2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public void setIdentifikationsnummerLP2(PlausibilisierteIdentifikationsnummer value) {
        this.identifikationsnummerLP2 = value;
    }

    /**
     * Gets the value of the wahlLPName property.
     * 
     * @return
     *     possible object is
     *     {@link CodeWahlLPName }
     *     
     */
    public CodeWahlLPName getWahlLPName() {
        return wahlLPName;
    }

    /**
     * Sets the value of the wahlLPName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeWahlLPName }
     *     
     */
    public void setWahlLPName(CodeWahlLPName value) {
        this.wahlLPName = value;
    }

    /**
     * Gets the value of the anschriftDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftDesKindes() {
        return anschriftDesKindes;
    }

    /**
     * Sets the value of the anschriftDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftDesKindes(AnschriftInland value) {
        this.anschriftDesKindes = value;
    }

    /**
     * Gets the value of the lebenspartnerschaftsname property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public AllgemeinerNamePersonenstandswesen getLebenspartnerschaftsname() {
        return lebenspartnerschaftsname;
    }

    /**
     * Sets the value of the lebenspartnerschaftsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public void setLebenspartnerschaftsname(AllgemeinerNamePersonenstandswesen value) {
        this.lebenspartnerschaftsname = value;
    }

}
