//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Container enthält Angaben zur Person im Kontext der Berichtigungen von Standesämtern an Meldebehörden.
 * 
 * <p>Java class for StA2MB.Berichtigung.AngabenPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2MB.Berichtigung.AngabenPerson">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="namen" type="{http://xpsw.domap.de/xpsw2511}StA2MB.PersonName.Flexibel"/>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2MB.Berichtigung.AngabenPerson", propOrder = {
    "namen",
    "geschlecht"
})
public class StA2MBBerichtigungAngabenPerson {

    @XmlElement(required = true)
    protected StA2MBPersonNameFlexibel namen;
    @XmlElement(required = true)
    protected CodeGeschlecht geschlecht;

    /**
     * Gets the value of the namen property.
     * 
     * @return
     *     possible object is
     *     {@link StA2MBPersonNameFlexibel }
     *     
     */
    public StA2MBPersonNameFlexibel getNamen() {
        return namen;
    }

    /**
     * Sets the value of the namen property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2MBPersonNameFlexibel }
     *     
     */
    public void setNamen(StA2MBPersonNameFlexibel value) {
        this.namen = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlecht(CodeGeschlecht value) {
        this.geschlecht = value;
    }

}
