//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2MB">
 *       <sequence>
 *         <element name="eintragungHinweisPar4Abs3StAG" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         <element name="namensfuehrungNichtNachgewiesen" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eintragungHinweisPar4Abs3StAG",
    "namensfuehrungNichtNachgewiesen"
})
@XmlRootElement(name = "stA2MB.Geburt.031050")
public class StA2MBGeburt031050
    extends NachrichtStA2MB
{

    protected Boolean eintragungHinweisPar4Abs3StAG;
    protected Boolean namensfuehrungNichtNachgewiesen;

    /**
     * Gets the value of the eintragungHinweisPar4Abs3StAG property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEintragungHinweisPar4Abs3StAG() {
        return eintragungHinweisPar4Abs3StAG;
    }

    /**
     * Sets the value of the eintragungHinweisPar4Abs3StAG property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEintragungHinweisPar4Abs3StAG(Boolean value) {
        this.eintragungHinweisPar4Abs3StAG = value;
    }

    /**
     * Gets the value of the namensfuehrungNichtNachgewiesen property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNamensfuehrungNichtNachgewiesen() {
        return namensfuehrungNichtNachgewiesen;
    }

    /**
     * Sets the value of the namensfuehrungNichtNachgewiesen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNamensfuehrungNichtNachgewiesen(Boolean value) {
        this.namensfuehrungNichtNachgewiesen = value;
    }

}
