//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.datum._2.TeilbekanntesDatumMitUnbekannt;
import de.osci.xinneres.idnr._2.PlausibilisierteIdentifikationsnummer;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp enthält die zu übermittelnden Elemente für Nachrichten zum Eheeintrag der Vorehe oder zum Eintrag einer vorangegangenen Lebenspartnerschaft, die aufgrund einer erneuten Eheschließung zu übermitteln sind.
 * 
 * <p>Java class for StA2StA.VoreheOderLP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2StA.VoreheOderLP">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="neuerEheeintragOderLPEintrag" type="{http://xpsw.domap.de/xpsw2511}BeurkundeteDaten.Quelleintrag"/>
 *         <element name="betroffenerEhegatteOderLP" type="{http://xpsw.domap.de/xpsw2511}PersonName"/>
 *         <element name="identifikationsnummerBetroffenerEhegatteOderLP" type="{http://www.osci.de/xinneres/idnr/2}PlausibilisierteIdentifikationsnummer" minOccurs="0"/>
 *         <element name="geburtsdatumBetroffenerEhegatteOderLP" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatumMitUnbekannt" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2StA.VoreheOderLP", propOrder = {
    "neuerEheeintragOderLPEintrag",
    "betroffenerEhegatteOderLP",
    "identifikationsnummerBetroffenerEhegatteOderLP",
    "geburtsdatumBetroffenerEhegatteOderLP"
})
public class StA2StAVoreheOderLP {

    @XmlElement(required = true)
    protected BeurkundeteDatenQuelleintrag neuerEheeintragOderLPEintrag;
    @XmlElement(required = true)
    protected PersonName betroffenerEhegatteOderLP;
    protected PlausibilisierteIdentifikationsnummer identifikationsnummerBetroffenerEhegatteOderLP;
    protected TeilbekanntesDatumMitUnbekannt geburtsdatumBetroffenerEhegatteOderLP;

    /**
     * Gets the value of the neuerEheeintragOderLPEintrag property.
     * 
     * @return
     *     possible object is
     *     {@link BeurkundeteDatenQuelleintrag }
     *     
     */
    public BeurkundeteDatenQuelleintrag getNeuerEheeintragOderLPEintrag() {
        return neuerEheeintragOderLPEintrag;
    }

    /**
     * Sets the value of the neuerEheeintragOderLPEintrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeurkundeteDatenQuelleintrag }
     *     
     */
    public void setNeuerEheeintragOderLPEintrag(BeurkundeteDatenQuelleintrag value) {
        this.neuerEheeintragOderLPEintrag = value;
    }

    /**
     * Gets the value of the betroffenerEhegatteOderLP property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getBetroffenerEhegatteOderLP() {
        return betroffenerEhegatteOderLP;
    }

    /**
     * Sets the value of the betroffenerEhegatteOderLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setBetroffenerEhegatteOderLP(PersonName value) {
        this.betroffenerEhegatteOderLP = value;
    }

    /**
     * Gets the value of the identifikationsnummerBetroffenerEhegatteOderLP property.
     * 
     * @return
     *     possible object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public PlausibilisierteIdentifikationsnummer getIdentifikationsnummerBetroffenerEhegatteOderLP() {
        return identifikationsnummerBetroffenerEhegatteOderLP;
    }

    /**
     * Sets the value of the identifikationsnummerBetroffenerEhegatteOderLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public void setIdentifikationsnummerBetroffenerEhegatteOderLP(PlausibilisierteIdentifikationsnummer value) {
        this.identifikationsnummerBetroffenerEhegatteOderLP = value;
    }

    /**
     * Gets the value of the geburtsdatumBetroffenerEhegatteOderLP property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public TeilbekanntesDatumMitUnbekannt getGeburtsdatumBetroffenerEhegatteOderLP() {
        return geburtsdatumBetroffenerEhegatteOderLP;
    }

    /**
     * Sets the value of the geburtsdatumBetroffenerEhegatteOderLP property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public void setGeburtsdatumBetroffenerEhegatteOderLP(TeilbekanntesDatumMitUnbekannt value) {
        this.geburtsdatumBetroffenerEhegatteOderLP = value;
    }

}
