//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}StA2StA.Familienrecht.Template.Namensaenderung.Eltern2Kind">
 *       <sequence>
 *         <element name="geschlechtNeu" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geschlechtNeu"
})
@XmlRootElement(name = "stA2StA.Geburt.011030")
public class StA2StAGeburt011030
    extends StA2StAFamilienrechtTemplateNamensaenderungEltern2Kind
{

    protected CodeGeschlecht geschlechtNeu;

    /**
     * Gets the value of the geschlechtNeu property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlechtNeu() {
        return geschlechtNeu;
    }

    /**
     * Sets the value of the geschlechtNeu property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlechtNeu(CodeGeschlecht value) {
        this.geschlechtNeu = value;
    }

}
