//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import java.util.ArrayList;
import java.util.List;
import de.osci.xinneres.idnr._2.PlausibilisierteIdentifikationsnummer;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <extension base="{http://xpsw.domap.de/xpsw2511}Nachricht.StA2StA">
 *       <sequence>
 *         <element name="geburtsnameNeu" type="{http://xpsw.domap.de/xpsw2511}AllgemeinerName.Personenstandswesen"/>
 *         <element name="nameElternteil" type="{http://xpsw.domap.de/xpsw2511}PersonName" minOccurs="0"/>
 *         <element name="identifikationsnummerElternteil" type="{http://www.osci.de/xinneres/idnr/2}PlausibilisierteIdentifikationsnummer" minOccurs="0"/>
 *         <element name="anschriftDesKindes" type="{http://xpsw.domap.de/xpsw2511}Anschrift.Inland" minOccurs="0"/>
 *         <element name="erklaerung" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="einwilligungKind" type="{http://xpsw.domap.de/xpsw2511}StA2StA.Erklaerung.Einwilligung.MitAnschrift" minOccurs="0"/>
 *         <element name="einwilligungAndererElternteil" type="{http://xpsw.domap.de/xpsw2511}StA2StA.Erklaerung.Einwilligung.MitAnschrift" minOccurs="0"/>
 *         <element name="anhaenge" type="{http://xpsw.domap.de/xpsw2511}AnhangInformation" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geburtsnameNeu",
    "nameElternteil",
    "identifikationsnummerElternteil",
    "anschriftDesKindes",
    "erklaerung",
    "einwilligungKind",
    "einwilligungAndererElternteil",
    "anhaenge"
})
@XmlRootElement(name = "stA2StA.Erklaerung.011240")
public class StA2StAErklaerung011240
    extends NachrichtStA2StA
{

    @XmlElement(required = true)
    protected AllgemeinerNamePersonenstandswesen geburtsnameNeu;
    protected PersonName nameElternteil;
    protected PlausibilisierteIdentifikationsnummer identifikationsnummerElternteil;
    protected AnschriftInland anschriftDesKindes;
    @XmlElement(required = true)
    protected String erklaerung;
    protected StA2StAErklaerungEinwilligungMitAnschrift einwilligungKind;
    protected StA2StAErklaerungEinwilligungMitAnschrift einwilligungAndererElternteil;
    protected List<AnhangInformation> anhaenge;

    /**
     * Gets the value of the geburtsnameNeu property.
     * 
     * @return
     *     possible object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public AllgemeinerNamePersonenstandswesen getGeburtsnameNeu() {
        return geburtsnameNeu;
    }

    /**
     * Sets the value of the geburtsnameNeu property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllgemeinerNamePersonenstandswesen }
     *     
     */
    public void setGeburtsnameNeu(AllgemeinerNamePersonenstandswesen value) {
        this.geburtsnameNeu = value;
    }

    /**
     * Gets the value of the nameElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getNameElternteil() {
        return nameElternteil;
    }

    /**
     * Sets the value of the nameElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setNameElternteil(PersonName value) {
        this.nameElternteil = value;
    }

    /**
     * Gets the value of the identifikationsnummerElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public PlausibilisierteIdentifikationsnummer getIdentifikationsnummerElternteil() {
        return identifikationsnummerElternteil;
    }

    /**
     * Sets the value of the identifikationsnummerElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlausibilisierteIdentifikationsnummer }
     *     
     */
    public void setIdentifikationsnummerElternteil(PlausibilisierteIdentifikationsnummer value) {
        this.identifikationsnummerElternteil = value;
    }

    /**
     * Gets the value of the anschriftDesKindes property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInland }
     *     
     */
    public AnschriftInland getAnschriftDesKindes() {
        return anschriftDesKindes;
    }

    /**
     * Sets the value of the anschriftDesKindes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInland }
     *     
     */
    public void setAnschriftDesKindes(AnschriftInland value) {
        this.anschriftDesKindes = value;
    }

    /**
     * Gets the value of the erklaerung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErklaerung() {
        return erklaerung;
    }

    /**
     * Sets the value of the erklaerung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErklaerung(String value) {
        this.erklaerung = value;
    }

    /**
     * Gets the value of the einwilligungKind property.
     * 
     * @return
     *     possible object is
     *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
     *     
     */
    public StA2StAErklaerungEinwilligungMitAnschrift getEinwilligungKind() {
        return einwilligungKind;
    }

    /**
     * Sets the value of the einwilligungKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
     *     
     */
    public void setEinwilligungKind(StA2StAErklaerungEinwilligungMitAnschrift value) {
        this.einwilligungKind = value;
    }

    /**
     * Gets the value of the einwilligungAndererElternteil property.
     * 
     * @return
     *     possible object is
     *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
     *     
     */
    public StA2StAErklaerungEinwilligungMitAnschrift getEinwilligungAndererElternteil() {
        return einwilligungAndererElternteil;
    }

    /**
     * Sets the value of the einwilligungAndererElternteil property.
     * 
     * @param value
     *     allowed object is
     *     {@link StA2StAErklaerungEinwilligungMitAnschrift }
     *     
     */
    public void setEinwilligungAndererElternteil(StA2StAErklaerungEinwilligungMitAnschrift value) {
        this.einwilligungAndererElternteil = value;
    }

    /**
     * Gets the value of the anhaenge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the anhaenge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnhaenge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnhangInformation }
     * 
     * 
     * @return
     *     The value of the anhaenge property.
     */
    public List<AnhangInformation> getAnhaenge() {
        if (anhaenge == null) {
            anhaenge = new ArrayList<>();
        }
        return this.anhaenge;
    }

}
