//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.datum._2.TeilbekanntesDatumMitUnbekannt;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Die Klasse beinhaltet Geburtsdatum und Geburtsort einer Person.
 * 
 * <p>Java class for StA2AB.AngabenZurGeburt complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="StA2AB.AngabenZurGeburt">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="geburtsdatum" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatumMitUnbekannt"/>
 *         <element name="geburtsort" type="{http://xpsw.domap.de/xpsw2511}Ereignisort"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StA2AB.AngabenZurGeburt", propOrder = {
    "geburtsdatum",
    "geburtsort"
})
public class StA2ABAngabenZurGeburt {

    @XmlElement(required = true)
    protected TeilbekanntesDatumMitUnbekannt geburtsdatum;
    @XmlElement(required = true)
    protected Ereignisort geburtsort;

    /**
     * Gets the value of the geburtsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public TeilbekanntesDatumMitUnbekannt getGeburtsdatum() {
        return geburtsdatum;
    }

    /**
     * Sets the value of the geburtsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatumMitUnbekannt }
     *     
     */
    public void setGeburtsdatum(TeilbekanntesDatumMitUnbekannt value) {
        this.geburtsdatum = value;
    }

    /**
     * Gets the value of the geburtsort property.
     * 
     * @return
     *     possible object is
     *     {@link Ereignisort }
     *     
     */
    public Ereignisort getGeburtsort() {
        return geburtsort;
    }

    /**
     * Sets the value of the geburtsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ereignisort }
     *     
     */
    public void setGeburtsort(Ereignisort value) {
        this.geburtsort = value;
    }

}
