//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.domap.xpsw.xpsw2511;

import de.osci.xinneres.datum._2.TeilbekanntesDatum;
import de.osci.xinneres.geschlecht._1.CodeGeschlecht;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Mit diesem Datentyp können die Angaben zum Verstorbenen übermittelt werden.
 * 
 * <p>Java class for Todesbescheinigung.Verstorbener complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="Todesbescheinigung.Verstorbener">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="vorname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="familienname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC"/>
 *         <element name="geburtsname" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="letzterWohnort" type="{http://xpsw.domap.de/xpsw2511}Anschrift.InlandAusland" minOccurs="0"/>
 *         <element name="tagDerGeburt" type="{http://www.osci.de/xinneres/datum/2}TeilbekanntesDatum" minOccurs="0"/>
 *         <element name="ortDerGeburt" type="{urn:xoev-de:kosit:xoev:datentyp:din-91379_2022-08}datatypeC" minOccurs="0"/>
 *         <element name="geschlecht" type="{http://www.osci.de/xinneres/geschlecht/1}Code.Geschlecht"/>
 *         <element name="identifizierung" type="{http://xpsw.domap.de/xpsw2511}Code.Identifizierungsart" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Todesbescheinigung.Verstorbener", propOrder = {
    "vorname",
    "familienname",
    "geburtsname",
    "letzterWohnort",
    "tagDerGeburt",
    "ortDerGeburt",
    "geschlecht",
    "identifizierung"
})
public class TodesbescheinigungVerstorbener {

    protected String vorname;
    @XmlElement(required = true)
    protected String familienname;
    protected String geburtsname;
    protected AnschriftInlandAusland letzterWohnort;
    protected TeilbekanntesDatum tagDerGeburt;
    protected String ortDerGeburt;
    @XmlElement(required = true)
    protected CodeGeschlecht geschlecht;
    protected CodeIdentifizierungsart identifizierung;

    /**
     * Gets the value of the vorname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVorname() {
        return vorname;
    }

    /**
     * Sets the value of the vorname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVorname(String value) {
        this.vorname = value;
    }

    /**
     * Gets the value of the familienname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFamilienname() {
        return familienname;
    }

    /**
     * Sets the value of the familienname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFamilienname(String value) {
        this.familienname = value;
    }

    /**
     * Gets the value of the geburtsname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeburtsname() {
        return geburtsname;
    }

    /**
     * Sets the value of the geburtsname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeburtsname(String value) {
        this.geburtsname = value;
    }

    /**
     * Gets the value of the letzterWohnort property.
     * 
     * @return
     *     possible object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public AnschriftInlandAusland getLetzterWohnort() {
        return letzterWohnort;
    }

    /**
     * Sets the value of the letzterWohnort property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnschriftInlandAusland }
     *     
     */
    public void setLetzterWohnort(AnschriftInlandAusland value) {
        this.letzterWohnort = value;
    }

    /**
     * Gets the value of the tagDerGeburt property.
     * 
     * @return
     *     possible object is
     *     {@link TeilbekanntesDatum }
     *     
     */
    public TeilbekanntesDatum getTagDerGeburt() {
        return tagDerGeburt;
    }

    /**
     * Sets the value of the tagDerGeburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeilbekanntesDatum }
     *     
     */
    public void setTagDerGeburt(TeilbekanntesDatum value) {
        this.tagDerGeburt = value;
    }

    /**
     * Gets the value of the ortDerGeburt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrtDerGeburt() {
        return ortDerGeburt;
    }

    /**
     * Sets the value of the ortDerGeburt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrtDerGeburt(String value) {
        this.ortDerGeburt = value;
    }

    /**
     * Gets the value of the geschlecht property.
     * 
     * @return
     *     possible object is
     *     {@link CodeGeschlecht }
     *     
     */
    public CodeGeschlecht getGeschlecht() {
        return geschlecht;
    }

    /**
     * Sets the value of the geschlecht property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeGeschlecht }
     *     
     */
    public void setGeschlecht(CodeGeschlecht value) {
        this.geschlecht = value;
    }

    /**
     * Gets the value of the identifizierung property.
     * 
     * @return
     *     possible object is
     *     {@link CodeIdentifizierungsart }
     *     
     */
    public CodeIdentifizierungsart getIdentifizierung() {
        return identifizierung;
    }

    /**
     * Sets the value of the identifizierung property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeIdentifizierungsart }
     *     
     */
    public void setIdentifizierung(CodeIdentifizierungsart value) {
        this.identifizierung = value;
    }

}
